import json
from gen_unit_utils import make_unit, write_ts_unit

# ==============================================================================
# UNIT 5: WONDERS OF VIET NAM
# ==============================================================================
u5_vocab = [
    {"id": "u5-v1", "word": "spectacular", "phonetic": "/spɛkˈtækjʊlə/", "partOfSpeech": "adjective", "vietnameseMeaning": "ngoạn mục, hùng vĩ tuyệt đẹp", "englishExample": "Ha Long Bay offers spectacular panoramic views of thousands of limestone karsts.", "vietnameseExample": "Vịnh Hạ Long mang đến tầm nhìn toàn cảnh ngoạn mục của hàng ngàn đảo đá vôi."},
    {"id": "u5-v2", "word": "stalactite", "phonetic": "/ˈstæləktaɪt/", "partOfSpeech": "noun", "vietnameseMeaning": "nhũ đá (rủ từ trần hang động xuống)", "englishExample": "Phong Nha Cave boasts breathtaking stalactites formed over millions of years.", "vietnameseExample": "Động Phong Nha sở hữu những thạch nhũ tuyệt đẹp được hình thành qua hàng triệu năm."},
    {"id": "u5-v3", "word": "stalagmite", "phonetic": "/ˈstæləɡmaɪt/", "partOfSpeech": "noun", "vietnameseMeaning": "măng đá (mọc từ sàn hang động lên)", "englishExample": "Giant limestone stalagmites rise majestically from the floor of Son Doong Cave.", "vietnameseExample": "Những măng đá vôi khổng lồ mọc lên uy nghiêm từ nền hang Sơn Đoòng."},
    {"id": "u5-v4", "word": "citadel", "phonetic": "/ˈsɪtədl/", "partOfSpeech": "noun", "vietnameseMeaning": "thành quách, kinh thành cổ", "englishExample": "The Imperial Citadel of Thang Long is a priceless World Cultural Heritage site.", "vietnameseExample": "Hoàng thành Thăng Long là khu di sản văn hóa thế giới vô giá."},
    {"id": "u5-v5", "word": "limestone karst", "phonetic": "/ˈlaɪmstəʊn kɑːst/", "partOfSpeech": "noun", "vietnameseMeaning": "địa hình karst núi đá vôi", "englishExample": "Trang An Landscape Complex is famous for towering limestone karsts and submerged caves.", "vietnameseExample": "Quần thể danh thắng Tràng An nổi tiếng với những dãy núi đá vôi sừng sững và hang động ngập nước."},
    {"id": "u5-v6", "word": "cavern", "phonetic": "/ˈkævən/", "partOfSpeech": "noun", "vietnameseMeaning": "hang động lớn kỳ vĩ", "englishExample": "Son Doong is recognized as the world's largest subterranean natural cavern.", "vietnameseExample": "Sơn Đoòng được công nhận là hang động tự nhiên ngầm dưới lòng đất lớn nhất thế giới."},
    {"id": "u5-v7", "word": "picturesque", "phonetic": "/ˌpɪkʧəˈrɛsk/", "partOfSpeech": "adjective", "vietnameseMeaning": "đẹp như tranh vẽ, hữu tình", "englishExample": "The picturesque terraced fields in Mu Cang Chai attract photographers worldwide.", "vietnameseExample": "Những thửa ruộng bậc thang đẹp như tranh vẽ ở Mù Cang Chải thu hút nhiếp ảnh gia toàn thế giới."},
    {"id": "u5-v8", "word": "geological", "phonetic": "/ˌʤɪəˈlɒʤɪkəl/", "partOfSpeech": "adjective", "vietnameseMeaning": "thuộc về địa chất học", "englishExample": "Dong Van Karst Plateau is of immense geological and educational value.", "vietnameseExample": "Cao nguyên đá Đồng Văn có giá trị địa chất và giáo dục vô cùng to lớn."},
    {"id": "u5-v9", "word": "biodiversity", "phonetic": "/ˌbaɪəʊdaɪˈvɜːsɪti/", "partOfSpeech": "noun", "vietnameseMeaning": "sự đa dạng sinh học", "englishExample": "Cat Tien National Park preserves the rich biodiversity of tropical rainforest flora and fauna.", "vietnameseExample": "Vườn quốc gia Cát Tiên bảo tồn sự đa dạng sinh học trù phú của hệ động thực vật rừng mưa nhiệt đới."},
    {"id": "u5-v10", "word": "preserve", "phonetic": "/prɪˈzɜːv/", "partOfSpeech": "verb", "vietnameseMeaning": "bảo tồn, giữ gìn nguyên vẹn", "englishExample": "Eco-tourism policies aim to preserve natural wonders without harming wildlife habitats.", "vietnameseExample": "Các chính sách du lịch sinh thái nhằm gìn giữ các kỳ quan thiên nhiên mà không gây hại đến môi trường hoang dã."},
    {"id": "u5-v11", "word": "complex", "phonetic": "/ˈkɒmplɛks/", "partOfSpeech": "noun", "vietnameseMeaning": "quần thể kiến trúc hoặc danh thắng", "englishExample": "The Complex of Hue Monuments reflects royal architectural elegance of the Nguyen Dynasty.", "vietnameseExample": "Quần thể di tích Cố đô Huế phản ánh sự thanh lịch kiến trúc hoàng gia của triều Nguyễn."},
    {"id": "u5-v12", "word": "impersonal passive", "phonetic": "/ɪmˈpɜːsənl ˈpæsɪv/", "partOfSpeech": "noun", "vietnameseMeaning": "câu bị động khách quan (It is said that...)", "englishExample": "It is believed that Ha Long Bay was created by celestial dragons descending to Earth.", "vietnameseExample": "Người ta tin rằng Vịnh Hạ Long được tạo nên bởi đàn rồng trời giáng thế."},
    {"id": "u5-v13", "word": "monument", "phonetic": "/ˈmɒnjʊmənt/", "partOfSpeech": "noun", "vietnameseMeaning": "đài tưởng niệm, công trình di tích", "englishExample": "Ancient stone monuments in My Son Sanctuary depict Hindu religious mythology.", "vietnameseExample": "Những công trình di tích bằng đá cổ ở Thánh địa Mỹ Sơn khắc họa thần thoại tôn giáo Ấn Độ giáo."},
    {"id": "u5-v14", "word": "magnificent", "phonetic": "/mæɡˈnɪfɪsnt/", "partOfSpeech": "adjective", "vietnameseMeaning": "tráng lệ, lộng lẫy", "englishExample": "Ban Gioc Waterfall creates a magnificent curtain of cascading white water.", "vietnameseExample": "Thác Bản Giốc tạo nên một bức rèm nước trắng xóa tuôn chảy tráng lệ."},
    {"id": "u5-v15", "word": "sanctuary", "phonetic": "/ˈsæŋktjʊəri/", "partOfSpeech": "noun", "vietnameseMeaning": "thánh địa linh thiêng, khu bảo tồn", "englishExample": "My Son Sanctuary was the spiritual and political capital of the Champa Kingdom.", "vietnameseExample": "Thánh địa Mỹ Sơn từng là thủ đô tâm linh và chính trị của Vương quốc Chăm Pa."},
    {"id": "u5-v16", "word": "scenic", "phonetic": "/ˈsiːnɪk/", "partOfSpeech": "adjective", "vietnameseMeaning": "có cảnh quan thiên nhiên tuyệt đẹp", "englishExample": "Taking a boat trip along the scenic Ngo Dong River in Tam Coc is an unforgettable experience.", "vietnameseExample": "Đi thuyền dọc theo dòng sông Ngô Đồng thơ mộng ở Tam Cốc là một trải nghiệm không thể nào quên."},
    {"id": "u5-v17", "word": "flora and fauna", "phonetic": "/ˈflɔːrə ænd ˈfɔːnə/", "partOfSpeech": "noun", "vietnameseMeaning": "hệ thực vật và động vật", "englishExample": "Phong Nha-Ke Bang is home to numerous endemic species of flora and fauna.", "vietnameseExample": "Phong Nha - Kẻ Bàng là ngôi nhà của nhiều loài động thực vật đặc hữu."},
    {"id": "u5-v18", "word": "breathtaking", "phonetic": "/ˈbrɛθˌteɪkɪŋ/", "partOfSpeech": "adjective", "vietnameseMeaning": "đẹp đến nín thở, ngỡ ngàng", "englishExample": "The summit of Fansipan Peak offers breathtaking views of shifting white cloud oceans.", "vietnameseExample": "Đỉnh Fansipan mang lại tầm nhìn đẹp ngỡ ngàng của những biển mây trắng bồng bềnh."},
    {"id": "u5-v19", "word": "heritage site", "phonetic": "/ˈhɛrɪtɪʤ saɪt/", "partOfSpeech": "noun", "vietnameseMeaning": "khu di sản được công nhận", "englishExample": "Hoi An Ancient Town was designated as a UNESCO World Heritage site in 1999.", "vietnameseExample": "Đô thị cổ Hội An được công nhận là Di sản Thế giới của UNESCO vào năm 1999."},
    {"id": "u5-v20", "word": "recommend", "phonetic": "/ˌrɛkəˈmɛnd/", "partOfSpeech": "verb", "vietnameseMeaning": "khuyên bảo, giới thiệu đề xuất", "englishExample": "Travel experts recommend visiting the caves during the dry season between March and August.", "vietnameseExample": "Các chuyên gia du lịch khuyên nên tham quan hang động vào mùa khô từ tháng 3 đến tháng 8."}
]

u5_grammar_info = {
    "title": "Bị Động Khách Quan (Impersonal Passive) & Cấu Trúc Đề Xuất (Suggest + V-ing / That Clause)",
    "summary": "Bị động khách quan dùng để thuật lại ý kiến, niềm tin của số đông (It is said/believed/reported that...). Cấu trúc Suggest dùng để đưa ra lời gợi ý hoặc đề xuất giải pháp.",
    "formulaBox": [
        "Impersonal Passive: It + is/was + V3/ed (said, believed, reported, claimed, estimated, known) + THAT + S + V",
        "Ví dụ: It is claimed that Son Doong Cave has its own internal weather system.",
        "Suggest + V-ing: S + suggest + V-ing (She suggested visiting Ha Long Bay by boat).",
        "Suggest + That clause: S + suggest + THAT + S + (should) + V-bare (The guide suggested that we should wear comfortable sneakers)."
    ],
    "usagePoints": [
        {"title": "1. Câu bị động khách quan diễn đạt thông tin du lịch", "detail": "Dùng để giới thiệu danh lam thắng cảnh một cách trang trọng, học thuật.", "example": "It is estimated that Trang An receives millions of travelers every year."},
        {"title": "2. Động từ trong mệnh đề sau Suggest", "detail": "Động từ luôn ở dạng nguyên thể không 'to' (V-bare) dù chủ ngữ là số ít hay số nhiều (that he visit / that we explore).", "example": "The teacher suggested that every student prepare a presentation on Hue Citadel."}
    ]
}

u5_grammar_exs = [
    {"id": "u5-g1", "question": "It is _____ that Ha Long Bay contains nearly two thousand limestone islets.", "options": ["A. reported", "B. reporting", "C. report", "D. reports"], "correctAnswer": "A. reported", "explanation": "Cấu trúc bị động khách quan: 'It is reported that...' (Người ta báo cáo rằng...)."},
    {"id": "u5-g2", "question": "The tour guide suggested _____ Son Doong Cave during the sunny dry season.", "options": ["A. visiting", "B. visit", "C. to visit", "D. visited"], "correctAnswer": "A. visiting", "explanation": "Cấu trúc 'suggest + V-ing' (suggested visiting)."},
    {"id": "u5-g3", "question": "It is _____ that ancient Cham artisans built My Son temples without using chemical mortar.", "options": ["A. believed", "B. believing", "C. believe", "D. believes"], "correctAnswer": "A. believed", "explanation": "'It is believed that...' (Người ta tin rằng...)."},
    {"id": "u5-g4", "question": "The eco-tourism committee suggested that visitors _____ not litter plastic bottles in national parks.", "options": ["A. should", "B. ought", "C. must", "D. will"], "correctAnswer": "A. should", "explanation": "Cấu trúc 'suggest that S + (should) + V-bare'."},
    {"id": "u5-g5", "question": "It is _____ that the subterranean river inside Phong Nha Cave stretches over seven kilometers.", "options": ["A. estimated", "B. estimating", "C. estimate", "D. estimates"], "correctAnswer": "A. estimated", "explanation": "'It is estimated that...' (Người ta ước tính rằng...)."},
    {"id": "u5-g6", "question": "I suggest that Lan _____ her camera to capture the breathtaking sunset in Trang An.", "options": ["A. bring", "B. brings", "C. brought", "D. is bringing"], "correctAnswer": "A. bring", "explanation": "Sau 'suggest that S + (should) + V-bare', động từ luôn là nguyên thể không 'to' ('bring')."},
    {"id": "u5-g7", "question": "It is _____ that the Imperial Citadel of Thang Long was established over a thousand years ago.", "options": ["A. known", "B. know", "C. knowing", "D. knew"], "correctAnswer": "A. known", "explanation": "'It is known that...' (Ai cũng biết rằng...)."},
    {"id": "u5-g8", "question": "My teacher suggested _____ a documentary film about the geological marvels of Dong Van Plateau.", "options": ["A. watching", "B. to watch", "C. watch", "D. watched"], "correctAnswer": "A. watching", "explanation": "'suggest + V-ing' (suggested watching)."},
    {"id": "u5-g9", "question": "It is _____ that the Perfume Pagoda complex attracts millions of pilgrims during spring.", "options": ["A. said", "B. say", "C. saying", "D. says"], "correctAnswer": "A. said", "explanation": "'It is said that...' (Người ta nói rằng...)."},
    {"id": "u5-g10", "question": "The park ranger suggested that we _____ quiet while observing endangered wild langurs.", "options": ["A. remain", "B. remains", "C. remained", "D. are remaining"], "correctAnswer": "A. remain", "explanation": "'suggested that we remain' (V-bare sau suggest that)."},
    {"id": "u5-g11", "question": "It is _____ that Son Doong Cave has its own internal jungle and cloud formations.", "options": ["A. claimed", "B. claim", "C. claiming", "D. claims"], "correctAnswer": "A. claimed", "explanation": "'It is claimed that...' (Được khẳng định rằng...)."},
    {"id": "u5-g12", "question": "She suggested _____ traditional local cuisines at Hoi An night market.", "options": ["A. tasting", "B. to taste", "C. taste", "D. tasted"], "correctAnswer": "A. tasting", "explanation": "'suggest + V-ing' (suggested tasting)."},
    {"id": "u5-g13", "question": "It was _____ that thousands of royal artifacts were excavated beneath the Thang Long Citadel.", "options": ["A. discovered", "B. discover", "C. discovering", "D. discovers"], "correctAnswer": "A. discovered", "explanation": "'It was discovered that...' (Người ta phát hiện ra rằng...)."},
    {"id": "u5-g14", "question": "We suggested that the city council _____ the restoration of ancient mossy fortress walls.", "options": ["A. accelerate", "B. accelerates", "C. accelerated", "D. will accelerate"], "correctAnswer": "A. accelerate", "explanation": "'suggested that the council accelerate' (thức giả định V-bare)."},
    {"id": "u5-g15", "question": "It is _____ that the limestone towers of Ha Long Bay took over five hundred million years to form.", "options": ["A. understood", "B. understand", "C. understanding", "D. understands"], "correctAnswer": "A. understood", "explanation": "'It is understood that...' (Được hiểu rằng...)."},
    {"id": "u5-g16", "question": "Minh suggested _____ electric shuttle buses instead of diesel cars to protect the scenic resort.", "options": ["A. using", "B. to use", "C. use", "D. used"], "correctAnswer": "A. using", "explanation": "'suggest + V-ing' (suggested using)."},
    {"id": "u5-g17", "question": "It is _____ that Ban Gioc is one of the most majestic border waterfalls on Earth.", "options": ["A. acknowledged", "B. acknowledge", "C. acknowledging", "D. acknowledges"], "correctAnswer": "A. acknowledged", "explanation": "'It is acknowledged that...' (Được công nhận rộng rãi rằng...)."},
    {"id": "u5-g18", "question": "The geologists suggested that tourists _____ touching sensitive cave stalactites.", "options": ["A. avoid", "B. avoids", "C. avoided", "D. avoiding"], "correctAnswer": "A. avoid", "explanation": "'suggested that tourists avoid' (V-bare)."},
    {"id": "u5-g19", "question": "It is _____ that over three hundred limestone caverns exist within Phong Nha-Ke Bang.", "options": ["A. recorded", "B. record", "C. recording", "D. records"], "correctAnswer": "A. recorded", "explanation": "'It is recorded that...' (Được ghi nhận rằng...)."},
    {"id": "u5-g20", "question": "Our biology teacher suggested that we _____ a research project on tropical biodiversity.", "options": ["A. conduct", "B. conducts", "C. conducted", "D. are conducting"], "correctAnswer": "A. conduct", "explanation": "'suggested that we conduct' (V-bare sau that clause)."}
]

u5_listening_info = {
    "audioTitle": "Khám Phá Hang Sơn Đoòng - Kỳ Quan Hang Động Lớn Nhất Thế Giới (Exploring Son Doong Cave)",
    "audioDuration": "3:25",
    "audioScriptSpeaker": "Expedition Leader Mr. Ho Khanh & British Explorer Howard",
    "transcriptText": "Howard: Mr. Ho Khanh, it is widely acknowledged that you first discovered the entrance to Son Doong Cave in 1991!\nMr. Ho Khanh: Yes, Howard! While trekking in the dense jungle of Phong Nha-Ke Bang, I stumbled upon a giant cavern opening emitting cool mist and a roaring subterranean river.\nHoward: It is estimated that Son Doong is large enough to house an entire forty-story skyscraper block!\nMr. Ho Khanh: Absolutely! The main cavern is more than five kilometers long and two hundred meters high. Inside, there are giant stalagmites towering over seventy meters and a pristine subterranean rainforest called the 'Garden of Edam'.\nHoward: We suggest that every visitor undergo rigorous fitness training before embarking on this challenging expedition.",
    "vietnameseTranslation": "Howard: Thưa ông Hồ Khanh, ai cũng biết rằng ông chính là người đầu tiên phát hiện ra lối vào hang Sơn Đoòng vào năm 1991!\nÔng Hồ Khanh: Đúng vậy, Howard! Khi đang đi rừng trong cánh rừng rậm rạp của Phong Nha - Kẻ Bàng, tôi tình cờ phát hiện ra một vòm hang khổng lồ tỏa ra làn sương mát lạnh và tiếng ầm vang của một dòng sông ngầm dưới lòng đất.\nHoward: Người ta ước tính rằng hang Sơn Đoòng đủ lớn để chứa cả một khối nhà chọc trời bốn mươi tầng!\nÔng Hồ Khanh: Hoàn toàn chính xác! Khoang hang chính dài hơn năm cây số và cao hai trăm mét. Bên trong có những cột măng đá khổng lồ cao hơn bảy mươi mét và một khu rừng mưa nhiệt đới nguyên sinh dưới lòng đất mang tên 'Vườn Địa Đàng'.\nHoward: Chúng tôi đề xuất rằng mọi du khách cần trải qua khóa rèn luyện thể lực nghiêm ngặt trước khi tham gia chuyến thám hiểm đầy thử thách này."
}

u5_listening_qs = [
    {"id": "u5-l1", "question": "When did Mr. Ho Khanh first discover the entrance to Son Doong Cave?", "options": ["A. In 1991", "B. In 1850", "C. In 2020", "D. In 1945"], "correctAnswerIndex": 0, "explanation": "Trong bài nghe: 'first discovered the entrance to Son Doong Cave in 1991!'"},
    {"id": "u5-l2", "question": "What clues helped Mr. Ho Khanh find the cave entrance in the jungle?", "options": ["A. Cool mist emitting from the opening and the roaring sound of a subterranean river", "B. A giant electric neon sign", "C. A paved highway", "D. A wooden bridge"], "correctAnswerIndex": 0, "explanation": "Trong bài nghe: 'emitting cool mist and a roaring subterranean river.'"},
    {"id": "u5-l3", "question": "How large is Son Doong Cave compared to modern buildings?", "options": ["A. It can house an entire forty-story skyscraper block", "B. It is smaller than a one-room house", "C. It can only hold three people", "D. It is as tiny as a tent"], "correctAnswerIndex": 0, "explanation": "Trong bài nghe: 'large enough to house an entire forty-story skyscraper block!'"},
    {"id": "u5-l4", "question": "What is the name of the pristine subterranean rainforest inside Son Doong?", "options": ["A. Garden of Edam", "B. Royal Garden", "C. Amazon Green", "D. Sahara Park"], "correctAnswerIndex": 0, "explanation": "Trong bài nghe: 'pristine subterranean rainforest called the 'Garden of Edam'.'"},
    {"id": "u5-l5", "question": "How high are the giant limestone stalagmites inside Son Doong?", "options": ["A. Over seventy meters", "B. Only two centimeters", "C. Five inches", "D. Exactly one meter"], "correctAnswerIndex": 0, "explanation": "Trong bài nghe: 'giant stalagmites towering over seventy meters.'"},
    {"id": "u5-l6", "question": "What does explorer Howard suggest before embarking on the expedition?", "options": ["A. Undergoing rigorous physical fitness training", "B. Bringing a heavy television", "C. Wearing high heels", "D. Eating fast food only"], "correctAnswerIndex": 0, "explanation": "Trong bài nghe: 'We suggest that every visitor undergo rigorous fitness training.'"},
    {"id": "u5-l7", "question": "Where is Son Doong Cave situated?", "options": ["A. In the dense jungle of Phong Nha-Ke Bang National Park", "B. In the center of Ho Chi Minh City", "C. On the sea surface of Nha Trang", "D. At the peak of Ba Vi mountain"], "correctAnswerIndex": 0, "explanation": "Trong bài nghe: 'dense jungle of Phong Nha-Ke Bang.'"},
    {"id": "u5-l8", "question": "How long is the main passage of Son Doong Cave?", "options": ["A. More than five kilometers", "B. Ten meters", "C. One hundred meters", "D. Fifty kilometers"], "correctAnswerIndex": 0, "explanation": "Trong bài nghe: 'The main cavern is more than five kilometers long.'"}
]

u5_listening_fibs = [
    {"id": "u5-f1", "sentenceWithBlank": "Son Doong can house a forty-story _____ block.", "correctWord": "skyscraper", "hint": "Tòa nhà chọc trời cao tầng"},
    {"id": "u5-f2", "sentenceWithBlank": "The cave was discovered in nineteen ninety-_____.", "correctWord": "one", "hint": "Số 1 trong năm 1991 (one)"},
    {"id": "u5-f3", "sentenceWithBlank": "Giant stalagmites tower over seventy _____ high.", "correctWord": "meters", "hint": "Đơn vị đo độ cao (mét)"},
    {"id": "u5-f4", "sentenceWithBlank": "Visitors must undergo rigorous _____ preparation.", "correctWord": "fitness", "hint": "Thể lực và sức khỏe dẻo dai"}
]

u5_speaking = [
    {"id": "u5-s1", "targetSentence": "Ha Long Bay is world-renowned for its thousands of spectacular limestone karsts and emerald waters.", "ipa": "/hɑː lɒŋ beɪ ɪz wɜːld-rɪˈnaʊnd fɔːr ɪts ˈθaʊzəndz ɒv spɛkˈtækjʊlə ˈlaɪmstəʊn kɑːsts ænd ˈɛmərəld ˈwɔːtəz/", "vietnameseMeaning": "Vịnh Hạ Long nổi tiếng khắp thế giới với hàng ngàn đảo đá vôi kỳ vĩ và làn nước xanh như ngọc bích.", "contextSituation": "Thuyết minh giới thiệu danh thắng Vịnh Hạ Long.", "keyPhonicsFocus": "Phát âm chuẩn tính từ 'spectacular' /spɛkˈtækjʊlə/ và 'emerald'.", "sampleAudioText": "Ha Long Bay is world-renowned for its thousands of spectacular limestone karsts and emerald waters."},
    {"id": "u5-s2", "targetSentence": "It is believed that Son Doong Cave was sculpted by underground river flows over millions of years.", "ipa": "/ɪt ɪz bɪˈliːvd ðæt ʃɒn dɒŋ keɪv wɒz ˈskʌlptɪd baɪ ˌʌndəˈɡraʊnd ˈrɪvə fləʊz ˈəʊvə ˈmɪljənz ɒv jɪəz/", "vietnameseMeaning": "Người ta tin rằng Hang Sơn Đoòng đã được kiến tạo bởi các dòng sông ngầm chảy qua hàng triệu năm.", "contextSituation": "Giới thiệu cơ chế địa chất hình thành hang Sơn Đoòng.", "keyPhonicsFocus": "Phát âm chuẩn cấu trúc 'It is believed that' và động từ 'sculpted'.", "sampleAudioText": "It is believed that Son Doong Cave was sculpted by underground river flows over millions of years."},
    {"id": "u5-s3", "targetSentence": "The park rangers suggested that tourists should not touch delicate stalactites inside the cave.", "ipa": "/ðə pɑːk ˈreɪnʤəz səˈʤɛstɪd ðæt ˈtʊərɪsts ʃʊd nɒt tʌʧ ˈdɛlɪkɪt ˈstæləktaɪts ɪnˈsaɪd ðə keɪv/", "vietnameseMeaning": "Các nhân viên kiểm lâm đề xuất du khách không nên chạm tay vào các nhũ đá mỏng manh trong hang.", "contextSituation": "Nhắc nhở quy tắc bảo tồn hang động.", "keyPhonicsFocus": "Phát âm chuẩn từ 'stalactites' /ˈstæləktaɪts/ và 'delicate'.", "sampleAudioText": "The park rangers suggested that tourists should not touch delicate stalactites inside the cave."},
    {"id": "u5-s4", "targetSentence": "Trang An Landscape Complex in Ninh Binh was designated as a mixed UNESCO World Heritage site.", "ipa": "/trɑːŋ æn ˈlænskeɪp ˈkɒmplɛks ɪn nɪn bɪn wɒz ˈdɛzɪɡneɪtɪd æz ə mɪkst juːˈnɛskəʊ wɜːld ˈhɛrɪtɪʤ saɪt/", "vietnameseMeaning": "Quần thể danh thắng Tràng An ở Ninh Bình được công nhận là Di sản Thế giới hỗn hợp của UNESCO.", "contextSituation": "Nêu vị thế di sản văn hóa và thiên nhiên của Tràng An.", "keyPhonicsFocus": "Phát âm chuẩn từ 'designated' /ˈdɛzɪɡneɪtɪd/ và 'complex'.", "sampleAudioText": "Trang An Landscape Complex in Ninh Binh was designated as a mixed UNESCO World Heritage site."},
    {"id": "u5-s5", "targetSentence": "It is reported that thousands of rare animal species flourish within Cat Tien National Park.", "ipa": "/ɪt ɪz rɪˈpɔːtɪd ðæt ˈθaʊzəndz ɒv reər ˈænɪməl ˈspiːʃiːz ˈflʌrɪʃ wɪˈðɪn kæt tjɛn ˈnæʃənl pɑːk/", "vietnameseMeaning": "Người ta báo cáo rằng hàng ngàn loài động vật quý hiếm đang sinh sống phát triển trong Vườn quốc gia Cát Tiên.", "contextSituation": "Nói về sự trù phú của hệ sinh thái rừng nhiệt đới.", "keyPhonicsFocus": "Phát âm chuẩn cụm từ 'It is reported that' và 'flourish'.", "sampleAudioText": "It is reported that thousands of rare animal species flourish within Cat Tien National Park."},
    {"id": "u5-s6", "targetSentence": "I suggest taking a peaceful wooden sampan boat tour through the scenic water caves of Tam Coc.", "ipa": "/aɪ səˈʤɛst ˈteɪkɪŋ ə ˈpiːsfʊl ˈwʊdn ˈsæmpæn bəʊt tʊə θruː ðə ˈsiːnɪk ˈwɔːtə keɪvz ɒv tæm kɒk/", "vietnameseMeaning": "Tôi gợi ý đi tour thuyền gỗ ba lá thanh bình qua các hang nước thơ mộng ở Tam Cốc.", "contextSituation": "Gợi ý trải nghiệm du lịch Ninh Bình.", "keyPhonicsFocus": "Phát âm chuẩn cấu trúc 'suggest taking' và tính từ 'scenic'.", "sampleAudioText": "I suggest taking a peaceful wooden sampan boat tour through the scenic water caves of Tam Coc."},
    {"id": "u5-s7", "targetSentence": "Ban Gioc Waterfall on the northern border presents a breathtaking cascade of roaring white water.", "ipa": "/bɑːn ɡjɒk ˈwɔːtəfɔːl ɒn ðə ˈnɔːðən ˈbɔːdə prɪˈzɛnts ə ˈbrɛθˌteɪkɪŋ kæsˈkeɪd ɒv ˈrɔːrɪŋ waɪt ˈwɔːtə/", "vietnameseMeaning": "Thác Bản Giốc ở biên giới phía Bắc tạo nên một dòng thác trắng xóa gầm vang đẹp ngỡ ngàng.", "contextSituation": "Miêu tả sự hùng vĩ của thác Bản Giốc Cao Bằng.", "keyPhonicsFocus": "Phát âm chuẩn từ 'cascade' /kæsˈkeɪd/ và 'breathtaking'.", "sampleAudioText": "Ban Gioc Waterfall on the northern border presents a breathtaking cascade of roaring white water."},
    {"id": "u5-s8", "targetSentence": "It is estimated that the ancient stone structures of My Son Sanctuary date back to the fourth century.", "ipa": "/ɪt ɪz ˈɛstɪmeɪtɪd ðæt ði ˈeɪnʃənt stəʊn ˈstrʌkʧəz ɒv miː sɒn ˈsæŋktjʊəri deɪt bæk tuː ðə fɔːθ ˈsɛnʧʊri/", "vietnameseMeaning": "Người ta ước tính rằng các công trình kiến trúc đá cổ của Thánh địa Mỹ Sơn có từ thế kỷ thứ tư.", "contextSituation": "Thuyết minh về niên đại lịch sử của Mỹ Sơn.", "keyPhonicsFocus": "Phát âm chuẩn cấu trúc 'It is estimated that' và 'sanctuary'.", "sampleAudioText": "It is estimated that the ancient stone structures of My Son Sanctuary date back to the fourth century."},
    {"id": "u5-s9", "targetSentence": "Environmentalists suggest establishing stricter marine reserves to safeguard coral reefs in Phu Quoc.", "ipa": "/ɪnˌvaɪərənˈmɛntəlɪsts səˈʤɛst ɪsˈtæblɪʃɪŋ ˈstrɪktə məˈriːn rɪˈzɜːvz tuː ˈseɪfɡɑːd ˈkɒrəl riːfs ɪn fuː kwɒk/", "vietnameseMeaning": "Các nhà môi trường đề xuất thành lập các khu bảo tồn biển nghiêm ngặt hơn để bảo vệ rạn san hô ở Phú Quốc.", "contextSituation": "Kêu gọi bảo vệ hệ sinh thái biển đảo.", "keyPhonicsFocus": "Phát âm chuẩn từ 'marine reserves' /məˈriːn rɪˈzɜːvz/.", "sampleAudioText": "Environmentalists suggest establishing stricter marine reserves to safeguard coral reefs in Phu Quoc."},
    {"id": "u5-s10", "targetSentence": "The Imperial Citadel of Hue reflects the pinnacle of royal architecture and Confucian philosophy.", "ipa": "/ði ɪmˈpɪərɪəl ˈsɪtədl ɒv hjuː rɪˈflɛkts ðə ˈpɪnəkl ɒv ˈrɔɪəl ˈɑːkɪtɛkʧər ænd kənˈfjuːʃən fɪˈlɒsəfi/", "vietnameseMeaning": "Hoàng thành Huế phản ánh đỉnh cao của kiến trúc cung đình và triết lý Nho giáo.", "contextSituation": "Giới thiệu giá trị tư tưởng của Cố đô Huế.", "keyPhonicsFocus": "Phát âm chuẩn danh từ 'pinnacle' /ˈpɪnəkl/ và 'architecture'.", "sampleAudioText": "The Imperial Citadel of Hue reflects the pinnacle of royal architecture and Confucian philosophy."},
    {"id": "u5-s11", "targetSentence": "It is claimed that the mineral mud baths in Nha Trang possess natural therapeutic benefits.", "ipa": "/ɪt ɪz kleɪmd ðæt ðə ˈmɪnərəl mʌd bɑːðz ɪn njɑː træŋ pəˈzɛs ˈnæʧrəl ˌθɛrəˈpjuːtɪk ˈbɛnɪfɪts/", "vietnameseMeaning": "Người ta khẳng định rằng tắm bùn khoáng ở Nha Trang mang lại những lợi ích trị liệu tự nhiên cho sức khỏe.", "contextSituation": "Quảng bá dịch vụ du lịch nghỉ dưỡng chăm sóc sức khỏe.", "keyPhonicsFocus": "Phát âm chuẩn từ 'therapeutic' /ˌθɛrəˈpjuːtɪk/.", "sampleAudioText": "It is claimed that the mineral mud baths in Nha Trang possess natural therapeutic benefits."},
    {"id": "u5-s12", "targetSentence": "Local guides suggest that hikers hire experienced local porters when conquering Mount Fansipan.", "ipa": "/ˈləʊkəl ɡaɪdz səˈʤɛst ðæt ˈhaɪkəz ˈhaɪər ɪksˈpɪərɪənst ˈləʊkəl ˈpɔːtəz wɛn ˈkɒŋkərɪŋ maʊnt ˈfænsɪpæn/", "vietnameseMeaning": "Hướng dẫn viên địa phương khuyên người leo núi nên thuê người khuân vác bản địa giàu kinh nghiệm khi chinh phục đỉnh Fansipan.", "contextSituation": "Lời khuyên an toàn khi leo núi mạo hiểm.", "keyPhonicsFocus": "Phát âm chuẩn động từ 'conquering' /ˈkɒŋkərɪŋ/ và 'porters'.", "sampleAudioText": "Local guides suggest that hikers hire experienced local porters when conquering Mount Fansipan."},
    {"id": "u5-s13", "targetSentence": "Picturesque yellow mustard flower valleys turn Moc Chau plateau into a magical springtime wonderland.", "ipa": "/ˌpɪkʧəˈrɛsk ˈjɛləʊ ˈmʌstəd ˈflaʊə ˈvæliz tɜːn mɒk ʧaʊ plæˈtəʊ ˈɪntuː ə ˈmæʤɪkəl ˈsprɪŋtaɪm ˈwʌndəlænd/", "vietnameseMeaning": "Những thung lũng hoa cải vàng đẹp như tranh vẽ biến cao nguyên Mộc Châu thành xứ sở thần tiên mùa xuân kỳ diệu.", "contextSituation": "Miêu tả mùa hoa cao nguyên Tây Bắc.", "keyPhonicsFocus": "Phát âm chuẩn từ 'plateau' /ˈplætəʊ/ và 'picturesque'.", "sampleAudioText": "Picturesque yellow mustard flower valleys turn Moc Chau plateau into a magical springtime wonderland."},
    {"id": "u5-s14", "targetSentence": "It is acknowledged that eco-tourism must balance economic prosperity with wildlife preservation.", "ipa": "/ɪt ɪz əkˈnɒlɪʤd ðæt ˈiːkəʊ-ˈtʊərɪzəm mʌst ˈbæləns ˌiːkəˈnɒmɪk prɒsˈpɛrɪti wɪð ˈwaɪldlaɪf ˌprɛzəˈveɪʃən/", "vietnameseMeaning": "Ai cũng thừa nhận rằng du lịch sinh thái phải cân bằng giữa phát triển kinh tế và bảo tồn thiên nhiên hoang dã.", "contextSituation": "Khẳng định nguyên tắc phát triển du lịch bền vững.", "keyPhonicsFocus": "Phát âm chuẩn từ 'prosperity' /prɒsˈpɛrɪti/.", "sampleAudioText": "It is acknowledged that eco-tourism must balance economic prosperity with wildlife preservation."},
    {"id": "u5-s15", "targetSentence": "Our geography teacher suggested doing a case study on the geological formation of Dong Van Karst Plateau.", "ipa": "/ˈaʊə ʤɪˈɒɡrəfi ˈtiːʧə səˈʤɛstɪd ˈduːɪŋ ə keɪs ˈstʌdi ɒn ðə ˌʤɪəˈlɒʤɪkəl fɔːˈmeɪʃən ɒv dɒŋ væn kɑːst plæˈtəʊ/", "vietnameseMeaning": "Cô giáo địa lý gợi ý thực hiện một bài nghiên cứu tình huống về sự hình thành địa chất của Cao nguyên đá Đồng Văn.", "contextSituation": "Định hướng dự án nghiên cứu học tập.", "keyPhonicsFocus": "Phát âm chuẩn cụm từ 'geological formation' /ˌʤɪəˈlɒʤɪkəl fɔːˈmeɪʃən/.", "sampleAudioText": "Our geography teacher suggested doing a case study on the geological formation of Dong Van Karst Plateau."},
    {"id": "u5-s16", "targetSentence": "It is known that Cu Chi Tunnels represent an astonishing underground defense network constructed during wartime.", "ipa": "/ɪt ɪz nəʊn ðæt kuː ʧiː ˈtʌnlz ˌrɛprɪˈzɛnt ən əsˈtɒnɪʃɪŋ ˌʌndəˈɡraʊnd dɪˈfɛns ˈnɛtwɜːk kənˈstrʌktɪd ˈdjʊərɪŋ ˈwɔːtaɪm/", "vietnameseMeaning": "Ai cũng biết rằng Địa đạo Củ Chi là một mạng lưới phòng thủ ngầm đáng kinh ngạc được xây dựng trong chiến tranh.", "contextSituation": "Thuyết minh về di tích lịch sử Địa đạo Củ Chi.", "keyPhonicsFocus": "Phát âm chuẩn từ 'astonishing' /əsˈtɒnɪʃɪŋ/ và 'network'.", "sampleAudioText": "It is known that Cu Chi Tunnels represent an astonishing underground defense network constructed during wartime."},
    {"id": "u5-s17", "targetSentence": "Travel experts suggest booking train tickets early to experience the breathtaking Hai Van Pass scenic railway.", "ipa": "/ˈtrævl ˈɛkspɜːts səˈʤɛst ˈbʊkɪŋ treɪn ˈtɪkɪts ˈɜːli tuː ɪksˈpɪərɪəns ðə ˈbrɛθˌteɪkɪŋ haɪ væn pɑːs ˈsiːnɪk ˈreɪlweɪ/", "vietnameseMeaning": "Các chuyên gia du lịch khuyên nên đặt vé tàu sớm để trải nghiệm tuyến đường sắt ngắm cảnh đèo Hải Vân đẹp ngỡ ngàng.", "contextSituation": "Gợi ý trải nghiệm cung đường đèo Hải Vân.", "keyPhonicsFocus": "Phát âm chuẩn từ 'booking' /ˈbʊkɪŋ/ và 'breathtaking'.", "sampleAudioText": "Travel experts suggest booking train tickets early to experience the breathtaking Hai Van Pass scenic railway."},
    {"id": "u5-s18", "targetSentence": "It is recognized that preserving our pristine natural wonders ensures a thriving eco-tourism industry.", "ipa": "/ɪt ɪz ˈrɛkəɡnaɪzd ðæt prɪˈzɜːvɪŋ ˈaʊə ˈprɪstiːn ˈnæʧrəl ˈwʌndəz ɪnˈʃʊəz ə ˈθraɪvɪŋ ˈiːkəʊ-ˈtʊərɪzəm ˈɪndəstri/", "vietnameseMeaning": "Mọi người đều nhận thức rằng gìn giữ các kỳ quan thiên nhiên nguyên sơ sẽ đảm bảo một ngành du lịch sinh thái phát triển mạnh mẽ.", "contextSituation": "Nêu mối liên hệ giữa bảo tồn và du lịch sinh thái.", "keyPhonicsFocus": "Phát âm chuẩn tính từ 'pristine' /ˈprɪstiːn/ và 'thriving'.", "sampleAudioText": "It is recognized that preserving our pristine natural wonders ensures a thriving eco-tourism industry."},
    {"id": "u5-s19", "targetSentence": "The ancient mossy brick towers of Po Nagar in Nha Trang stand as a testament to maritime history.", "ipa": "/ði ˈeɪnʃənt ˈmɒsi brɪk ˈtaʊəz ɒv pəʊ ˈnæɡɑːr ɪn njɑː træŋ stænd æz ə ˈtɛstəmənt tuː ˈmærɪtaɪm ˈhɪstəri/", "vietnameseMeaning": "Những tháp gạch rêu phong cổ kính Po Nagar ở Nha Trang sừng sững như một minh chứng cho lịch sử hàng hải.", "contextSituation": "Giới thiệu Tháp Bà Po Nagar.", "keyPhonicsFocus": "Phát âm chuẩn danh từ 'testament' /ˈtɛstəmənt/ và 'maritime'.", "sampleAudioText": "The ancient mossy brick towers of Po Nagar in Nha Trang stand as a testament to maritime history."},
    {"id": "u5-s20", "targetSentence": "Let us cherish and actively protect the glorious natural and cultural wonders of Viet Nam.", "ipa": "/lɛt ʌs ˈʧɛrɪʃ ænd ˈæktɪvli prəˈtɛkt ðə ˈɡlɔːrɪəs ˈnæʧrəl ænd ˈkʌlʧərəl ˈwʌndəz ɒv ˌvjɛt ˈnɑːm/", "vietnameseMeaning": "Chúng ta hãy cùng nhau trân trọng và tích cực bảo vệ những kỳ quan thiên nhiên và văn hóa rực rỡ của Việt Nam.", "contextSituation": "Thông điệp kết luận đầy tự hào dân tộc.", "keyPhonicsFocus": "Phát âm chuẩn động từ 'cherish' /ˈʧɛrɪʃ/ và tính từ 'glorious'.", "sampleAudioText": "Let us cherish and actively protect the glorious natural and cultural wonders of Viet Nam."}
]

u5_reading_info = {
    "title": "Quần Thể Danh Thắng Tràng An: Kiệt Tác Địa Chất & Di Sản Kép Của Nhân Loại",
    "topic": "Kỳ quan thiên nhiên & Quần thể di sản Tràng An - Ninh Bình",
    "passageText": "Nestled in the southern margin of the Red River Delta, the Trang An Landscape Complex in Ninh Binh Province is celebrated as one of the most mesmerizing karst geological marvels in Southeast Asia. In 2014, UNESCO officially inscribed Trang An as Viet Nam's first dual World Cultural and Natural Heritage site, acknowledging its outstanding universal aesthetic and archaeological values.\n\nGeologically, Trang An presents a dramatic landscape of sheer limestone tower karsts soaring abruptly above emerald valley basins and winding waterways. Over millions of years of chemical weathering and tectonic uplift, subterranean rivers carved a labyrinth of submerged caverns adorned with delicate stalactites and stalagmites. Traveling through these cool, echoing cave passages aboard traditional rowed sampans evokes a sense of tranquil wonder.\n\nBeyond its sheer natural splendor, Trang An holds profound archaeological significance. Excavations inside limestone cliff caves revealed prehistoric human settlements dating back over thirty thousand years. These ancient hunter-gatherers adapted ingeniously to fluctuating sea levels and glacial climatic shifts. Today, stringent conservation regulations ensure that sustainable eco-tourism safeguards this pristine ecosystem while providing rewarding livelihoods for local boat-rowing communities.",
    "keyVocabularyHighlights": [
        {"word": "dual Heritage site", "meaning": "di sản thế giới hỗn hợp (cả văn hóa lẫn thiên nhiên)"},
        {"word": "submerged caverns", "meaning": "các hang động ngập nước kỳ bí"},
        {"word": "prehistoric human settlements", "meaning": "các di chỉ định cư của người tiền sử"},
        {"word": "stringent conservation regulations", "meaning": "các quy định bảo tồn nghiêm ngặt"}
    ]
}

u5_reading_qs = [
    {"id": "u5-r1", "question": "Where is the Trang An Landscape Complex situated?", "options": ["A. In Ninh Binh Province, southern margin of the Red River Delta", "B. In the center of Da Nang City", "C. In the Mekong Delta floating markets", "D. On Phu Quoc Island"], "correctAnswerIndex": 0, "explanation": "Trong đoạn 1: 'in the southern margin of the Red River Delta, the Trang An Landscape Complex in Ninh Binh Province.'"},
    {"id": "u5-r2", "question": "Why was Trang An designated as a dual UNESCO World Heritage site in 2014?", "options": ["A. Because of its outstanding cultural and natural values", "B. Because it was the biggest modern port", "C. Because it has many tall skyscrapers", "D. Because of its gold mining factories"], "correctAnswerIndex": 0, "explanation": "Trong đoạn 1: 'inscribed Trang An as Viet Nam's first dual World Cultural and Natural Heritage site.'"},
    {"id": "u5-r3", "question": "What geological features dominate the scenery of Trang An?", "options": ["A. Sheer limestone tower karsts, emerald waters, and submerged caves", "B. Dry sandy deserts", "C. Active volcanic craters", "D. Frozen glaciers"], "correctAnswerIndex": 0, "explanation": "Trong đoạn 2: 'sheer limestone tower karsts soaring abruptly above emerald valley basins and winding waterways.'"},
    {"id": "u5-r4", "question": "How do visitors explore the water cave labyrinth in Trang An?", "options": ["A. Aboard traditional rowed sampan boats", "B. By flying jet planes", "C. By driving large buses inside caves", "D. By swimming with iron boots"], "correctAnswerIndex": 0, "explanation": "Trong đoạn 2: 'aboard traditional rowed sampans.'"},
    {"id": "u5-r5", "question": "How far back do prehistoric human settlements found in Trang An caves date?", "options": ["A. Over thirty thousand years", "B. Exactly two years", "C. Ten years", "D. Fifty years"], "correctAnswerIndex": 0, "explanation": "Trong đoạn 3: 'prehistoric human settlements dating back over thirty thousand years.'"},
    {"id": "u5-r6", "question": "How did ancient hunter-gatherers in Trang An adapt to their environment?", "options": ["A. They adapted ingeniously to fluctuating sea levels and climatic shifts", "B. They built modern concrete roads", "C. They moved to another continent completely", "D. They destroyed the limestone mountains"], "correctAnswerIndex": 0, "explanation": "Trong đoạn 3: 'adapted ingeniously to fluctuating sea levels and glacial climatic shifts.'"},
    {"id": "u5-r7", "question": "Which word in paragraph 1 is closest in meaning to 'mesmerizing'?", "options": ["A. Spellbinding, fascinating, and enchanting", "B. Extremely boring", "C. Ugly", "D. Ordinary"], "correctAnswerIndex": 0, "explanation": "'Mesmerizing' có nghĩa là quyến rũ, lôi cuốn làm mê đắm lòng người."},
    {"id": "u5-r8", "question": "Which word in paragraph 3 is closest in meaning to 'stringent'?", "options": ["A. Strict, rigorous, and demanding", "B. Loose and careless", "C. Optional", "D. Temporary"], "correctAnswerIndex": 0, "explanation": "'Stringent regulations' mang nghĩa các quy định, luật lệ nghiêm ngặt."},
    {"id": "u5-r9", "question": "How does eco-tourism in Trang An benefit local residents?", "options": ["A. By providing rewarding livelihoods for boat-rowing communities", "B. By taking away all their land", "C. By forbidding them from living in Ninh Binh", "D. By forcing them to build factories"], "correctAnswerIndex": 0, "explanation": "Trong đoạn 3: 'providing rewarding livelihoods for local boat-rowing communities.'"},
    {"id": "u5-r10", "question": "What is the best overall title for this reading passage?", "options": ["A. The History of Modern Industrial Machinery", "B. Trang An Landscape Complex: A Geological Masterpiece & Dual World Heritage", "C. How to Build a Motorboat", "D. Desert Landscapes Around the World"], "correctAnswerIndex": 1, "explanation": "Bài đọc ca ngợi vẻ đẹp địa chất kỳ vĩ và giá trị di sản kép của Quần thể danh thắng Tràng An."}
]

u5_writing_prompts = [
    {
        "id": "u5-w1",
        "title": "Đề 1: Write a paragraph describing a natural wonder of Viet Nam (60-80 words)",
        "description": "Viết một đoạn văn giới thiệu về một kỳ quan thiên nhiên nổi tiếng của Việt Nam (Vịnh Hạ Long, Hang Sơn Đoòng, Động Phong Nha, Thác Bản Giốc...).",
        "suggestedOutline": [
            "Introduction: Name and location of the natural wonder.",
            "Body: Describe its spectacular features (limestone karsts, emerald water, caves, flora & fauna).",
            "Conclusion: Explain why it is a must-visit destination for travelers."
        ],
        "usefulPhrases": [
            "One of the most spectacular natural wonders in Viet Nam is...",
            "It is celebrated for its towering limestone karsts and...",
            "It is estimated that thousands of tourists visit this marvel every year...",
            "Visiting this site is an unforgettable journey into majestic nature."
        ],
        "wordLimit": "60 - 80 từ",
        "sampleGrade10Response": "One of the most breathtaking natural wonders in Viet Nam is Ha Long Bay, situated in Quang Ninh Province. It is world-renowned for its thousands of towering limestone karsts rising majestically from emerald green waters. Over millions of years, subterranean erosion has sculpted spectacular caves such as Sung Sot Cave and Thien Cung Cave. Traveling on a cruise boat allows tourists to admire stunning islands and sunset vistas. Ha Long Bay is truly an unforgettable national treasure."
    },
    {
        "id": "u5-w2",
        "title": "Đề 2: Write a paragraph suggesting ways to protect our natural heritage sites (60-80 words)",
        "description": "Viết một đoạn văn đề xuất các biện pháp bảo vệ danh lam thắng cảnh và di sản thiên nhiên quốc gia.",
        "suggestedOutline": [
            "Introduction: State the urgency of preserving natural heritage sites.",
            "Body: Suggest 2 practical actions (banning single-use plastic, setting visitor capacity limits).",
            "Conclusion: Reaffirm that everyone should travel responsibly."
        ],
        "usefulPhrases": [
            "To safeguard our precious natural wonders, several actions should be taken...",
            "First, authorities should ban single-use plastics and fine illegal littering...",
            "Second, I suggest that tourism managers limit daily visitor capacity to prevent overcrowding...",
            "Practicing responsible eco-tourism will keep our heritage pristine for future generations."
        ],
        "wordLimit": "60 - 80 từ",
        "sampleGrade10Response": "To protect our pristine natural heritage sites, several proactive measures should be implemented. First, park authorities should strictly prohibit single-use plastics and impose heavy fines on littering tourists. Second, I suggest that site managers limit daily visitor numbers to prevent ecological damage to delicate stalactites and marine coral reefs. Educating travelers on responsible eco-tourism is equally vital. By protecting these natural wonders, we ensure they remain vibrant for generations to come."
    },
    {
        "id": "u5-w3",
        "title": "Đề 3: Write a paragraph giving travel tips for visiting a famous cave (60-80 words)",
        "description": "Viết một đoạn văn đưa ra các lời khuyên hữu ích cho du khách chuẩn bị đi thám hiểm hang động (Phong Nha, Sơn Đoòng, Hang Én...).",
        "suggestedOutline": [
            "Introduction: Introduce the cave destination and when to visit.",
            "Body: Give practical tips (wearing anti-slip shoes, bringing headlights, not touching stalactites).",
            "Conclusion: Wish travelers a safe and thrilling expedition."
        ],
        "usefulPhrases": [
            "If you plan to explore a limestone cavern like Phong Nha Cave, keep these tips in mind...",
            "First, you should wear sturdy anti-slip trekking shoes and bring a powerful flashlight...",
            "Furthermore, guides suggest that visitors never touch sensitive stalactites...",
            "Following these safety guidelines ensures an exhilarating and memorable journey."
        ],
        "wordLimit": "60 - 80 từ",
        "sampleGrade10Response": "If you plan to explore the spectacular caves in Phong Nha-Ke Bang, keep these helpful tips in mind. First, you should visit during the dry season from March to August to avoid subterranean river flooding. Second, wear sturdy anti-slip hiking shoes and bring waterproof headlamps. Tour guides strongly suggest that hikers avoid touching ancient stalactites to prevent surface erosion. Following these safety guidelines ensures an exhilarating and respectful cave expedition."
    },
    {
        "id": "u5-w4",
        "title": "Đề 4: Write a paragraph about a historical citadel or complex you admire (60-80 words)",
        "description": "Viết một đoạn văn giới thiệu về một khu di tích lịch sử hoàng thành hoặc cố đô (Hoàng thành Thăng Long, Cố đô Huế, Thành nhà Hồ...).",
        "suggestedOutline": [
            "Introduction: Name the historical citadel and its location.",
            "Body: Describe its unique royal architecture, stone walls, and historical role.",
            "Conclusion: Express your pride in our ancestors' architectural genius."
        ],
        "usefulPhrases": [
            "The Imperial Citadel of Hue is an awe-inspiring historical complex...",
            "It was built by the Nguyen Dynasty along the poetic Huong River...",
            "The citadel features grand palaces, fortified stone gates, and serene royal tombs...",
            "I feel immense pride when contemplating our ancestors' architectural brilliance."
        ],
        "wordLimit": "60 - 80 từ",
        "sampleGrade10Response": "The Imperial Citadel of Hue is an awe-inspiring historical complex located along the poetic Huong River. Built during the Nguyen Dynasty, it served as the royal and administrative capital of feudal Viet Nam. The complex showcases fortified stone ramparts, majestic palaces, and ornate lotus ponds arranged according to oriental feng-shui principles. Walking through its ancient gates gives visitors a deep connection with royal history. I feel immense pride in our ancestors' architectural brilliance."
    },
    {
        "id": "u5-w5",
        "title": "Đề 5: Write a paragraph expressing your pride in Vietnamese heritage (60-80 words)",
        "description": "Viết một đoạn văn bày tỏ niềm tự hào về vẻ đẹp đất nước và di sản văn hóa - thiên nhiên Việt Nam.",
        "suggestedOutline": [
            "Introduction: Express deep love and pride for Viet Nam's diverse landscapes.",
            "Body: Mention famous landmarks (Ha Long Bay, Phong Nha, terraced fields, ancient towns).",
            "Conclusion: Promise to promote and protect our national identity."
        ],
        "usefulPhrases": [
            "Viet Nam is blessed with an abundance of world-class cultural and natural marvels...",
            "From the majestic karst towers of Ha Long to the ancient alleys of Hoi An...",
            "Every heritage site embodies our ancestors' resilience and artistic mastery...",
            "As young citizens, we are determined to promote our country's beauty worldwide."
        ],
        "wordLimit": "60 - 80 từ",
        "sampleGrade10Response": "Viet Nam is blessed with an incredible abundance of world-class cultural and natural wonders. From the majestic limestone towers of Ha Long Bay to the ancient lantern-lit alleys of Hoi An, each destination tells a story of enduring beauty and resilience. These heritage sites not only attract global travelers but also instill immense national pride in our hearts. As young students, we are determined to protect these treasures and promote our nation's rich culture to international friends."
    }
]

unit5 = make_unit(5, "Unit 5: Wonders of Viet Nam", "Kỳ quan thiên nhiên & Danh lam thắng cảnh Việt Nam", "Khám phá các kỳ quan thiên nhiên, hang động kỳ vĩ, bị động khách quan (It is said that...) và cấu trúc Suggest.", "Ngữ âm: Trọng âm câu bị động khách quan và ngữ điệu câu đề xuất Suggest", "Compass", u5_vocab, u5_grammar_info, u5_grammar_exs, u5_listening_info, u5_listening_qs, u5_listening_fibs, u5_speaking, u5_reading_info, u5_reading_qs, u5_writing_prompts)
write_ts_unit(5, unit5)

print("Unit 5 generated successfully!")
