import json
from gen_unit_utils import make_unit, write_ts_unit

# ==============================================================================
# UNIT 6: VIET NAM: THEN AND NOW
# ==============================================================================
u6_vocab = [
    {"id": "u6-v1", "word": "modernization", "phonetic": "/ˌmɒdənaɪˈzeɪʃən/", "partOfSpeech": "noun", "vietnameseMeaning": "quá trình hiện đại hóa đất nước", "englishExample": "Rapid modernization has elevated the living standards of millions of Vietnamese citizens.", "vietnameseExample": "Hiện đại hóa nhanh chóng đã nâng cao mức sống của hàng triệu người dân Việt Nam."},
    {"id": "u6-v2", "word": "infrastructure", "phonetic": "/ˈɪnfrəˌstrʌkʧə/", "partOfSpeech": "noun", "vietnameseMeaning": "cơ sở hạ tầng (cầu đường, bến cảng, mạng lưới điện)", "englishExample": "Modern bridges and elevated highways have drastically shortened interprovincial travel times.", "vietnameseExample": "Những cây cầu hiện đại và đường cao tốc trên cao đã rút ngắn đáng kể thời gian di chuyển liên tỉnh."},
    {"id": "u6-v3", "word": "flyover", "phonetic": "/ˈflaɪˌəʊvə/", "partOfSpeech": "noun", "vietnameseMeaning": "cầu vượt cạn giao thông đô thị", "englishExample": "Urban flyovers were constructed at major intersections to relieve severe traffic congestion.", "vietnameseExample": "Các cầu vượt đô thị đã được xây dựng tại những nút giao lớn để giải tỏa ùn tắc giao thông nghiêm trọng."},
    {"id": "u6-v4", "word": "elevated railway", "phonetic": "/ˈɛlɪveɪtɪd ˈreɪlweɪ/", "partOfSpeech": "noun", "vietnameseMeaning": "tuyến đường sắt đô thị trên cao", "englishExample": "The Cat Linh - Ha Dong elevated railway operates swiftly and punctually.", "vietnameseExample": "Tuyến đường sắt trên cao Cát Linh - Hà Đông vận hành nhanh chóng và đúng giờ."},
    {"id": "u6-v5", "word": "transformation", "phonetic": "/ˌtrænsfəˈmeɪʃən/", "partOfSpeech": "noun", "vietnameseMeaning": "sự chuyển mình, biến đổi vượt bậc", "englishExample": "Ha Noi has undergone a remarkable socioeconomic transformation over the past three decades.", "vietnameseExample": "Hà Nội đã trải qua một sự chuyển mình kinh tế - xã hội đáng kinh ngạc trong ba thập kỷ qua."},
    {"id": "u6-v6", "word": "thatched hut", "phonetic": "/θæʧt hʌt/", "partOfSpeech": "noun", "vietnameseMeaning": "ngôi nhà mái tranh vách đất xưa", "englishExample": "In the 1970s, many rural families lived in simple thatched huts with earthen floors.", "vietnameseExample": "Vào thập niên 1970, nhiều gia đình nông thôn sống trong những ngôi nhà tranh đơn sơ với nền đất nện."},
    {"id": "u6-v7", "word": "high-rise apartment", "phonetic": "/haɪ raɪz əˈpɑːtmənt/", "partOfSpeech": "noun", "vietnameseMeaning": "căn hộ chung cư cao tầng", "englishExample": "Modern high-rise apartments provide convenient amenities like gyms, supermarkets, and swimming pools.", "vietnameseExample": "Các căn hộ chung cư cao tầng hiện đại cung cấp nhiều tiện ích tiện lợi như phòng gym, siêu thị và hồ bơi."},
    {"id": "u6-v8", "word": "trolleybus", "phonetic": "/ˈtrɒlibʌs/", "partOfSpeech": "noun", "vietnameseMeaning": "xe buýt điện bánh lốp thời xưa", "englishExample": "Decades ago, trolleybuses running along electric wires were a common sight in the capital.", "vietnameseExample": "Nhiều thập kỷ trước, những chiếc xe buýt điện chạy dọc theo dây điện trên cao từng là hình ảnh quen thuộc ở thủ đô."},
    {"id": "u6-v9", "word": "pedestrian bridge", "phonetic": "/pɪˈdɛstrɪən brɪʤ/", "partOfSpeech": "noun", "vietnameseMeaning": "cầu vượt bộ hành cho người đi bộ", "englishExample": "Pedestrian bridges ensure safe road crossing over busy six-lane urban avenues.", "vietnameseExample": "Cầu vượt bộ hành đảm bảo việc qua đường an toàn trên các đại lộ sáu làn xe đông đúc."},
    {"id": "u6-v10", "word": "subsidy economy", "phonetic": "/ˈsʌbsɪdi ɪˈkɒnəmi/", "partOfSpeech": "noun", "vietnameseMeaning": "nền kinh tế thời bao cấp", "englishExample": "Under the subsidy economy, goods and commodities were strictly rationed.", "vietnameseExample": "Trong nền kinh tế thời bao cấp, hàng hóa và nhu yếu phẩm được phân phối theo định mức nghiêm ngặt."},
    {"id": "u6-v11", "word": "technological breakthrough", "phonetic": "/ˌtɛknəˈlɒʤɪkəl ˈbreɪkθruː/", "partOfSpeech": "noun", "vietnameseMeaning": "bước đột phá công nghệ", "englishExample": "Smartphones and 5G networks represent major technological breakthroughs in daily communication.", "vietnameseExample": "Điện thoại thông minh và mạng 5G đại diện cho những bước đột phá công nghệ lớn trong giao tiếp hàng ngày."},
    {"id": "u6-v12", "word": "underpass", "phonetic": "/ˈʌndəpɑːs/", "partOfSpeech": "noun", "vietnameseMeaning": "hầm chui giao thông đô thị", "englishExample": "The newly built underpass at Kim Lien junction solved chronic rush-hour gridlock.", "vietnameseExample": "Hầm chui mới xây tại nút giao Kim Liên đã giải quyết triệt để tình trạng kẹt xe kinh niên trong giờ cao điểm."},
    {"id": "u6-v13", "word": "nuclear family", "phonetic": "/ˈnjuːklɪə ˈfæmɪli/", "partOfSpeech": "noun", "vietnameseMeaning": "gia đình hạt nhân (chỉ gồm cha mẹ và con cái)", "englishExample": "The transition from extended families to nuclear families is common in modern urban centers.", "vietnameseExample": "Sự chuyển dịch từ đại gia đình sang mô hình gia đình hạt nhân là điều phổ biến ở các đô thị hiện đại."},
    {"id": "u6-v14", "word": "telecommunication", "phonetic": "/ˌtɛlɪkəˌmjuːnɪˈkeɪʃən/", "partOfSpeech": "noun", "vietnameseMeaning": "ngành viễn thông và thông tin liên lạc", "englishExample": "Advanced telecommunication allows remote students to access global digital courses.", "vietnameseExample": "Viễn thông tiên tiến cho phép học sinh vùng sâu vùng xa tiếp cận các khóa học kỹ thuật số toàn cầu."},
    {"id": "u6-v15", "word": "pave", "phonetic": "/peɪv/", "partOfSpeech": "verb", "vietnameseMeaning": "trải nhựa, lát gạch mặt đường", "englishExample": "Rural dirt pathways were paved with smooth concrete under the new countryside program.", "vietnameseExample": "Những con đường đất lầy lội ở nông thôn đã được bê tông hóa phẳng phiu trong chương trình nông thôn mới."},
    {"id": "u6-v16", "word": "equipped", "phonetic": "/ɪˈkwɪpt/", "partOfSpeech": "adjective", "vietnameseMeaning": "được trang bị đầy đủ trang thiết bị", "englishExample": "Modern classrooms are fully equipped with interactive smartboards and high-speed Wi-Fi.", "vietnameseExample": "Các lớp học hiện đại được trang bị đầy đủ bảng thông minh tương tác và Wi-Fi tốc độ cao."},
    {"id": "u6-v17", "word": "drastic", "phonetic": "/ˈdræstɪk/", "partOfSpeech": "adjective", "vietnameseMeaning": "mạnh mẽ, quyết liệt, đáng kể", "englishExample": "There has been a drastic improvement in public healthcare access across the country.", "vietnameseExample": "Đã có sự cải thiện mạnh mẽ, rõ rệt trong việc tiếp cận dịch vụ y tế công cộng trên cả nước."},
    {"id": "u6-v18", "word": "generation gap", "phonetic": "/ˌʤɛnəˈreɪʃən ɡæp/", "partOfSpeech": "noun", "vietnameseMeaning": "khoảng cách thế hệ trong suy nghĩ và lối sống", "englishExample": "Open family dialogues help bridge the generation gap between teenagers and grandparents.", "vietnameseExample": "Những cuộc trò chuyện cởi mở trong gia đình giúp xóa nhòa khoảng cách thế hệ giữa tuổi teen và ông bà."},
    {"id": "u6-v19", "word": "diligence", "phonetic": "/ˈdɪlɪʤəns/", "partOfSpeech": "noun", "vietnameseMeaning": "sự siêng năng, cần cù chịu khó", "englishExample": "Our ancestors' resilience and diligence laid the solid foundations for today's prosperity.", "vietnameseExample": "Sự kiên cường và cần cù của thế hệ cha ông đã đặt nền móng vững chắc cho sự thịnh vượng hôm nay."},
    {"id": "u6-v20", "word": "flourish", "phonetic": "/ˈflʌrɪʃ/", "partOfSpeech": "verb", "vietnameseMeaning": "phát triển rực rỡ, phồn vinh", "englishExample": "Both traditional craft villages and high-tech industrial parks flourish side by side.", "vietnameseExample": "Cả các làng nghề truyền thống lẫn các khu công nghiệp công nghệ cao đều đang cùng nhau phát triển rực rỡ."}
]

u6_grammar_info = {
    "title": "Thì Quá Khứ Hoàn Thành (Past Perfect Tense) & Cấu Trúc Tính Từ + To-V / That Clause",
    "summary": "Thì Quá khứ hoàn thành (had + V3/ed) diễn tả hành động xảy ra và hoàn tất trước một thời điểm hoặc hành động khác trong quá khứ. Cấu trúc Tính từ + To-infinitive / That clause diễn tả cảm xúc, nhận định hoặc đánh giá.",
    "formulaBox": [
        "Past Perfect: S + had + V3/ed (By 1990, the city had dismantled the old tramcar lines).",
        "Liên từ thời gian: Before / By the time + S + V(quá khứ đơn), S + had + V3/ed",
        "After + S + had + V3/ed, S + V(quá khứ đơn)",
        "Adjective + To-infinitive: It + is/was + Adj + (for sb) + TO-V (It was difficult to travel across rivers).",
        "Adjective + That clause: S + be + Adj (glad, proud, certain, surprised) + THAT + S + V (We are proud that Viet Nam has developed rapidly)."
    ],
    "usagePoints": [
        {"title": "1. Quá khứ hoàn thành trong mạch tường thuật lịch sử", "detail": "Diễn tả các sự kiện diễn ra trước một mốc lịch sử trong quá khứ.", "example": "By the time the new expressway was opened, villagers had used bumpy dirt roads for decades."},
        {"title": "2. Tính từ chỉ cảm xúc và nhận định", "detail": "It is exciting to witness urban growth. / We are delighted that ancient heritage is preserved.", "example": "It is essential for youngsters to understand national history."}
    ]
}

u6_grammar_exs = [
    {"id": "u6-g1", "question": "By the time the new highway was completed, commuters _____ through muddy dirt roads for years.", "options": ["A. had travelled", "B. have travelled", "C. travel", "D. are travelling"], "correctAnswer": "A. had travelled", "explanation": "Hành động xảy ra trước mốc 'was completed' trong quá khứ: dùng Past Perfect 'had travelled'."},
    {"id": "u6-g2", "question": "It was impossible _____ across the deep river before modern suspension bridges were constructed.", "options": ["A. to cross", "B. crossing", "C. crossed", "D. cross"], "correctAnswer": "A. to cross", "explanation": "Cấu trúc: 'It was + Adj + to-V' (impossible to cross)."},
    {"id": "u6-g3", "question": "We are extremely proud _____ our hometown has transformed into a green, smart city.", "options": ["A. that", "B. to", "C. of", "D. with"], "correctAnswer": "A. that", "explanation": "Cấu trúc: 'S + be + proud + THAT + clause'."},
    {"id": "u6-g4", "question": "After the government _____ the rural electrification project, every household had lighting.", "options": ["A. had finished", "B. finishes", "C. has finished", "D. will finish"], "correctAnswer": "A. had finished", "explanation": "Sau 'After' là hành động xảy ra trước: 'had finished'."},
    {"id": "u6-g5", "question": "It is very convenient for citizens _____ around the capital using the elevated metro railway.", "options": ["A. to travel", "B. travel", "C. travelling", "D. travelled"], "correctAnswer": "A. to travel", "explanation": "Cấu trúc: 'It is + Adj + for sb + TO-V' (to travel)."},
    {"id": "u6-g6", "question": "Before they moved to the high-rise apartment, they _____ in a small thatched house for twenty years.", "options": ["A. had lived", "B. lived", "C. have lived", "D. are living"], "correctAnswer": "A. had lived", "explanation": "Hành động sống trong nhà tranh xảy ra trước mốc 'moved': 'had lived'."},
    {"id": "u6-g7", "question": "Grandfather was delighted _____ his grandchildren were eager to learn traditional crafts.", "options": ["A. that", "B. what", "C. which", "D. whose"], "correctAnswer": "A. that", "explanation": "Cấu trúc: 'S + was delighted + THAT + clause'."},
    {"id": "u6-g8", "question": "It was difficult for rural students _____ high-quality learning materials fifty years ago.", "options": ["A. to access", "B. accessing", "C. accessed", "D. access"], "correctAnswer": "A. to access", "explanation": "Cấu trúc 'It was difficult for students to access'."},
    {"id": "u6-g9", "question": "By 1986, the country _____ through challenging economic subsidy phases.", "options": ["A. had passed", "B. has passed", "C. passes", "D. was passing"], "correctAnswer": "A. had passed", "explanation": "Mốc thời gian 'By 1986' trong quá khứ kết hợp với Quá khứ hoàn thành: 'had passed'."},
    {"id": "u6-g10", "question": "The elders are relieved _____ the historic communal house was restored authentically.", "options": ["A. that", "B. to", "C. for", "D. with"], "correctAnswer": "A. that", "explanation": "'S + be + relieved + THAT + clause'."},
    {"id": "u6-g11", "question": "It is essential for teenagers _____ the significant sacrifices of past generations.", "options": ["A. to understand", "B. understanding", "C. understood", "D. understand"], "correctAnswer": "A. to understand", "explanation": "'It is essential for sb to understand'."},
    {"id": "u6-g12", "question": "The tramcar system _____ already disappeared when I was born in 2005.", "options": ["A. had", "B. has", "C. was", "D. is"], "correctAnswer": "A. had", "explanation": "Hành động biến mất trước khi sinh ra: 'had already disappeared'."},
    {"id": "u6-g13", "question": "My parents were amazed _____ the old dirt alleys had been paved with smooth concrete.", "options": ["A. that", "B. which", "C. what", "D. why"], "correctAnswer": "A. that", "explanation": "'amazed that + clause'."},
    {"id": "u6-g14", "question": "It is exciting _____ how modern technology reshapes agriculture in Vietnamese villages.", "options": ["A. to witness", "B. witnessing", "C. witnessed", "D. witness"], "correctAnswer": "A. to witness", "explanation": "'It is exciting to witness'."},
    {"id": "u6-g15", "question": "When my mother arrived at the station, the steam train _____ departed twenty minutes earlier.", "options": ["A. had", "B. has", "C. was", "D. is"], "correctAnswer": "A. had", "explanation": "Chuyến tàu đã rời đi trước: 'had departed'."},
    {"id": "u6-g16", "question": "We were surprised _____ how quickly the smart urban area had been erected.", "options": ["A. that", "B. to", "C. for", "D. on"], "correctAnswer": "A. that", "explanation": "'surprised that + clause'."},
    {"id": "u6-g17", "question": "It was necessary for villagers _____ rainwater during long dry seasons in the past.", "options": ["A. to collect", "B. collecting", "C. collected", "D. collect"], "correctAnswer": "A. to collect", "explanation": "'It was necessary to collect'."},
    {"id": "u6-g18", "question": "By the end of last decade, telecommunication companies _____ high-speed broadband to remote islands.", "options": ["A. had brought", "B. have brought", "C. bring", "D. were bringing"], "correctAnswer": "A. had brought", "explanation": "'By the end of last decade' + Past Perfect: 'had brought'."},
    {"id": "u6-g19", "question": "Historians are certain _____ ancient Thang Long played a pivotal geopolitical role.", "options": ["A. that", "B. which", "C. what", "D. whose"], "correctAnswer": "A. that", "explanation": "'certain that + clause'."},
    {"id": "u6-g20", "question": "It is inspiring _____ younger generations actively upholding family values.", "options": ["A. to see", "B. seeing", "C. saw", "D. seen"], "correctAnswer": "A. to see", "explanation": "'It is inspiring to see'."}
]

u6_listening_info = {
    "audioTitle": "Hà Nội Xưa Và Nay: Cuộc Trò Chuyện Xuyên Thế Hệ (Ha Noi: Then and Now)",
    "audioDuration": "3:22",
    "audioScriptSpeaker": "Elderly Resident Mr. Binh & High School Student Lan",
    "transcriptText": "Lan: Grandpa Binh, how has Ha Noi changed compared to when you were a teenager in the 1970s?\nMr. Binh: Oh Lan, the transformation is truly astonishing! Back then, most citizens rode simple bicycles or walked barefoot. The entire city only had a few two-story buildings, and the rhythmic chiming of electric tramcars echoed through the streets.\nLan: Had modern flyovers and elevated railways been built back then?\nMr. Binh: Not at all! By 1990, the city had dismantled the old tram tracks. Today, we have magnificent bridges spanning the Red River, air-conditioned metro trains, and towering skyscrapers like Landmark 72.\nLan: Are you pleased with all these modernization projects, Grandpa?\nMr. Binh: I am delighted that living conditions have improved so drastically, though I still cherish the peaceful tranquility of the old days.",
    "vietnameseTranslation": "Lan: Ông Bình ơi, Hà Nội đã thay đổi như thế nào so với thời ông còn là một thiếu niên vào thập niên 1970 ạ?\nÔng Bình: Ôi Lan à, sự chuyển mình thực sự đáng kinh ngạc! Hồi đó, hầu hết người dân chỉ đi xe đạp cọc cạch hoặc đi bộ chân trần. Cả thành phố chỉ có vài ngôi nhà hai tầng, và tiếng chuông leng keng của những chuyến tàu điện vang vọng khắp các con phố.\nLan: Hồi đó đã có cầu vượt hiện đại và đường sắt trên cao chưa ạ?\nÔng Bình: Chưa hề có đâu cháu! Đến năm 1990, thành phố đã dỡ bỏ các đường ray tàu điện cũ. Ngày nay, chúng ta có những cây cầu nguy nga bắc qua sông Hồng, những chuyến tàu điện metro mát lạnh điều hòa, và các tòa nhà chọc trời như Landmark 72.\nLan: Ông có hài lòng với tất cả những dự án hiện đại hóa này không ạ?\nÔng Bình: Ông rất vui mừng vì điều kiện sống đã được cải thiện rõ rệt, dù trong lòng ông vẫn luôn trân trọng sự thanh bình tĩnh lặng của những ngày xưa cũ."
}

u6_listening_qs = [
    {"id": "u6-l1", "question": "What primary means of transportation did Hanoians use in the 1970s?", "options": ["A. Simple bicycles and walking", "B. Luxury sports cars", "C. High-speed metro trains", "D. Commercial airplanes"], "correctAnswerIndex": 0, "explanation": "Trong bài nghe: 'most citizens rode simple bicycles or walked barefoot.'"},
    {"id": "u6-l2", "question": "What memorable sound echoed through Ha Noi streets in the past?", "options": ["A. The rhythmic chiming of electric tramcars", "B. Loud jet engines", "C. Blaring car horns", "D. Factory sirens"], "correctAnswerIndex": 0, "explanation": "Trong bài nghe: 'rhythmic chiming of electric tramcars echoed through the streets.'"},
    {"id": "u6-l3", "question": "When had the city dismantled the old tram tracks?", "options": ["A. By 1990", "B. In 2024", "C. In 1950", "D. In 1880"], "correctAnswerIndex": 0, "explanation": "Trong bài nghe: 'By 1990, the city had dismantled the old tram tracks.'"},
    {"id": "u6-l4", "question": "What modern structures now cross the Red River in Ha Noi?", "options": ["A. Magnificent modern bridges", "B. Bamboo rafts", "C. Ropes", "D. Wooden canoes"], "correctAnswerIndex": 0, "explanation": "Trong bài nghe: 'magnificent bridges spanning the Red River.'"},
    {"id": "u6-l5", "question": "Which famous skyscraper is mentioned by Grandpa Binh?", "options": ["A. Landmark 72", "B. Eiffel Tower", "C. Big Ben", "D. Empire State Building"], "correctAnswerIndex": 0, "explanation": "Trong bài nghe: 'towering skyscrapers like Landmark 72.'"},
    {"id": "u6-l6", "question": "How does Grandpa Binh feel about the modernization of the capital?", "options": ["A. He is delighted that living conditions improved drastically", "B. He hates all modern buildings", "C. He refused to look at the city", "D. He wants to move abroad"], "correctAnswerIndex": 0, "explanation": "Trong bài nghe: 'I am delighted that living conditions have improved so drastically.'"},
    {"id": "u6-l7", "question": "Who is Lan talking with in the audio?", "options": ["A. Grandpa Binh", "B. A bus driver", "C. A foreign tourist", "D. A young child"], "correctAnswerIndex": 0, "explanation": "Trong bài nghe: 'Elderly Resident Mr. Binh & High School Student Lan.'"},
    {"id": "u6-l8", "question": "What aspect of the past does Grandpa Binh still cherish?", "options": ["A. The peaceful tranquility of the old days", "B. Muddy roads", "C. Lack of medicines", "D. Power outages"], "correctAnswerIndex": 0, "explanation": "Trong bài nghe: 'I still cherish the peaceful tranquility of the old days.'"}
]

u6_listening_fibs = [
    {"id": "u6-f1", "sentenceWithBlank": "The rhythmic _____ of electric tramcars echoed across streets.", "correctWord": "chiming", "hint": "Tiếng chuông leng keng"},
    {"id": "u6-f2", "sentenceWithBlank": "By 1990, the city had dismantled the old tram _____.", "correctWord": "tracks", "hint": "Các tuyến đường ray kim loại"},
    {"id": "u6-f3", "sentenceWithBlank": "Modern bridges now span across the Red _____.", "correctWord": "River", "hint": "Sông Hồng của thủ đô Hà Nội"},
    {"id": "u6-f4", "sentenceWithBlank": "Living standards have improved _____ over thirty years.", "correctWord": "drastically", "hint": "Một cách mạnh mẽ, rõ rệt"}
]

u6_speaking = [
    {"id": "u6-s1", "targetSentence": "Over the past three decades, Viet Nam has experienced tremendous economic and infrastructural transformation.", "ipa": "/ˈəʊvə ðə pɑːst θriː ˈdɛkeɪdz ˌvjɛt ˈnɑːm hæz ɪksˈpɪərɪənst trɪˈmɛndəs ˌiːkəˈnɒmɪk ænd ˌɪnfrəˈstrʌkʧərəl ˌtrænsfəˈmeɪʃən/", "vietnameseMeaning": "Trong suốt ba thập kỷ qua, Việt Nam đã trải qua sự chuyển mình to lớn về kinh tế và cơ sở hạ tầng.", "contextSituation": "Thuyết trình về thành tựu đổi mới của đất nước.", "keyPhonicsFocus": "Phát âm chuẩn từ 'transformation' /ˌtrænsfəˈmeɪʃən/ và 'infrastructural'.", "sampleAudioText": "Over the past three decades, Viet Nam has experienced tremendous economic and infrastructural transformation."},
    {"id": "u6-s2", "targetSentence": "By the time the new elevated railway was opened, commuters had endured heavy traffic for years.", "ipa": "/baɪ ðə taɪm ðə njuː ˈɛlɪveɪtɪd ˈreɪlweɪ wɒz ˈəʊpənd kəˈmjuːtəz hæd ɪnˈdjʊəd ˈhɛvi ˈtræfɪk fɔː jɪəz/", "vietnameseMeaning": "Vào thời điểm tuyến đường sắt trên cao mới được khánh thành, người đi làm đã phải chịu đựng cảnh kẹt xe trong nhiều năm.", "contextSituation": "Nói về lợi ích của công trình đường sắt đô thị.", "keyPhonicsFocus": "Phát âm chuẩn cấu trúc Quá khứ hoàn thành 'had endured'.", "sampleAudioText": "By the time the new elevated railway was opened, commuters had endured heavy traffic for years."},
    {"id": "u6-s3", "targetSentence": "We are proud that modern healthcare and educational facilities are accessible to everyone.", "ipa": "/wiː ɑː praʊd ðæt ˈmɒdən ˈhɛlθkeər ænd ˌɛʤʊˈkeɪʃənl fəˈsɪlɪtiz ɑːr əkˈsɛsəbl tuː ˈɛvrɪwʌn/", "vietnameseMeaning": "Chúng tôi tự hào rằng các cơ sở y tế và giáo dục hiện đại giờ đây ai cũng có thể tiếp cận được.", "contextSituation": "Nêu cao sự phát triển phúc lợi xã hội.", "keyPhonicsFocus": "Phát âm chuẩn cấu trúc 'We are proud that' và 'accessible'.", "sampleAudioText": "We are proud that modern healthcare and educational facilities are accessible to everyone."},
    {"id": "u6-s4", "targetSentence": "It was difficult for rural families to travel to neighboring provinces without paved concrete roads.", "ipa": "/ɪt wɒz ˈdɪfɪkəlt fɔː ˈrʊərəl ˈfæmɪliz tuː ˈtrævl tuː ˈneɪbərɪŋ ˈprɒvɪnsɪz wɪˈðaʊt peɪvd ˈkɒŋkriːt rəʊdz/", "vietnameseMeaning": "Thật khó khăn cho các gia đình nông thôn khi muốn di chuyển sang các tỉnh lân cận khi chưa có đường bê tông trải nhựa.", "contextSituation": "Kể về khó khăn giao thông ngày xưa.", "keyPhonicsFocus": "Phát âm chuẩn cấu trúc 'It was difficult for sb to travel'.", "sampleAudioText": "It was difficult for rural families to travel to neighboring provinces without paved concrete roads."},
    {"id": "u6-s5", "targetSentence": "Before smartphones became ubiquitous, people had written handwritten letters to stay in touch.", "ipa": "/bɪˈfɔː ˈsmɑːtfəʊnz bɪˈkeɪm juːˈbɪkwɪtəs ˈpiːpl hæd ˈrɪtn ˈhændˌrɪtn ˈlɛtəz tuː steɪ ɪn tʌʧ/", "vietnameseMeaning": "Trước khi điện thoại thông minh trở nên phổ biến, mọi người từng viết thư tay để giữ liên lạc.", "contextSituation": "So sánh cách thức liên lạc xưa và nay.", "keyPhonicsFocus": "Phát âm chuẩn cụm từ 'had written handwritten letters'.", "sampleAudioText": "Before smartphones became ubiquitous, people had written handwritten letters to stay in touch."},
    {"id": "u6-s6", "targetSentence": "The elders were delighted that their children had graduated from prestigious national universities.", "ipa": "/ði ˈɛldəz wɜː dɪˈlaɪtɪd ðæt ðeə ˈʧɪldrən hæd ˈɡræʤʊeɪtɪd frɒm prɛˈstɪʤəs ˈnæʃənl ˌjuːnɪˈvɜːsɪtiz/", "vietnameseMeaning": "Các bậc cha mẹ vui mừng khôn xiết khi con cái của họ đã tốt nghiệp từ các trường đại học danh tiếng.", "contextSituation": "Kể về niềm tự hào hiếu học gia đình.", "keyPhonicsFocus": "Phát âm chuẩn tính từ 'prestigious' /prɛˈstɪʤəs/ và 'delighted that'.", "sampleAudioText": "The elders were delighted that their children had graduated from prestigious national universities."},
    {"id": "u6-s7", "targetSentence": "It is essential for modern youth to honor the hard work and resilience of past generations.", "ipa": "/ɪt ɪz ɪˈsɛnʃəl fɔː ˈmɒdən juːθ tuː ˈɒnə ðə hɑːd wɜːk ænd rɪˈzɪlɪəns ɒv pɑːst ˌʤɛnəˈreɪʃənz/", "vietnameseMeaning": "Tuổi trẻ ngày nay cần phải ghi nhớ công ơn và sự kiên cường của các thế hệ đi trước.", "contextSituation": "Lời răn dạy về lòng tri ân lịch sử.", "keyPhonicsFocus": "Phát âm chuẩn âm câm /h/ trong 'honor' /ˈɒnə/ và 'resilience'.", "sampleAudioText": "It is essential for modern youth to honor the hard work and resilience of past generations."},
    {"id": "u6-s8", "targetSentence": "Many high-rise apartment complexes now incorporate lush green parks and solar energy systems.", "ipa": "/ˈmɛni haɪ raɪz əˈpɑːtmənt ˈkɒmplɛksɪz naʊ ɪnˈkɔːpəreɪt lʌʃ ɡriːn pɑːks ænd ˈsəʊlə ˈɛnəʤi ˈsɪstɪmz/", "vietnameseMeaning": "Nhiều khu chung cư cao tầng hiện nay tích hợp các công viên xanh mướt và hệ thống năng lượng mặt trời.", "contextSituation": "Miêu tả kiến trúc nhà ở đô thị hiện đại.", "keyPhonicsFocus": "Phát âm chuẩn động từ 'incorporate' /ɪnˈkɔːpəreɪt/.", "sampleAudioText": "Many high-rise apartment complexes now incorporate lush green parks and solar energy systems."},
    {"id": "u6-s9", "targetSentence": "Before the subsidy period ended, essential consumer goods had been distributed through coupons.", "ipa": "/bɪˈfɔː ðə ˈsʌbsɪdi ˈpɪərɪəd ˈɛndɪd ɪˈsɛnʃəl kənˈsjuːmə ɡʊdz hæd biːn ˌdɪstrɪˈbjuːtɪd θruː ˈkuːpɒnz/", "vietnameseMeaning": "Trước khi thời kỳ bao cấp khép lại, hàng tiêu dùng thiết yếu đã được phân phối qua tem phiếu.", "contextSituation": "Thuyết minh về lịch sử kinh tế.", "keyPhonicsFocus": "Phát âm chuẩn cụm từ 'had been distributed through coupons'.", "sampleAudioText": "Before the subsidy period ended, essential consumer goods had been distributed through coupons."},
    {"id": "u6-s10", "targetSentence": "We are amazed that telecommunication networks now reach even the most remote mountain hamlets.", "ipa": "/wiː ɑːr əˈmeɪzd ðæt ˌtɛlɪkəˌmjuːnɪˈkeɪʃən ˈnɛtwɜːks naʊ riːʧ ˈiːvən ðə məʊst rɪˈməʊt ˈmaʊntɪn ˈhæmlɪts/", "vietnameseMeaning": "Chúng tôi kinh ngạc khi mạng lưới viễn thông ngày nay đã vươn tới cả những bản làng vùng cao xa xôi nhất.", "contextSituation": "Nói về sự phát triển vượt bậc của internet và công nghệ.", "keyPhonicsFocus": "Phát âm chuẩn từ 'hamlets' /ˈhæmlɪts/ và 'telecommunication'.", "sampleAudioText": "We are amazed that telecommunication networks now reach even the most remote mountain hamlets."},
    {"id": "u6-s11", "targetSentence": "It was wonderful to see old mud houses gradually replaced by solid, multi-story brick homes.", "ipa": "/ɪt wɒz ˈwʌndəfʊl tuː siː əʊld mʌd ˈhaʊzɪz ˈɡræʤʊəli rɪˈpleɪst baɪ ˈsɒlɪd ˈmʌlti-ˈstɔːri brɪk həʊmz/", "vietnameseMeaning": "Thật tuyệt vời khi chứng kiến những ngôi nhà tranh vách đất xưa dần được thay thế bằng những ngôi nhà gạch cao tầng khang trang.", "contextSituation": "Miêu tả sự đổi thay diện mạo nông thôn mới.", "keyPhonicsFocus": "Phát âm chuẩn cấu trúc 'It was wonderful to see'.", "sampleAudioText": "It was wonderful to see old mud houses gradually replaced by solid, multi-story brick homes."},
    {"id": "u6-s12", "targetSentence": "By the year 2000, primary school literacy programs had reached every corner of the nation.", "ipa": "/baɪ ðə jɪə tuː ˈθaʊzənd ˈpraɪməri skuːl ˈlɪtərəsi ˈprəʊɡræmz hæd riːʧt ˈɛvri ˈkɔːnər ɒv ðə ˈneɪʃən/", "vietnameseMeaning": "Đến năm 2000, các chương trình phổ cập giáo dục tiểu học đã vươn tới mọi ngóc ngách của đất nước.", "contextSituation": "Khẳng định thành tựu xóa mù chữ.", "keyPhonicsFocus": "Phát âm chuẩn cụm từ 'had reached every corner'.", "sampleAudioText": "By the year 2000, primary school literacy programs had reached every corner of the nation."},
    {"id": "u6-s13", "targetSentence": "Parents are pleased that their children can now learn foreign languages with interactive AI software.", "ipa": "/ˈpeərənts ɑː pliːzd ðæt ðeə ˈʧɪldrən kæn naʊ lɜːn ˈfɒrɪn ˈlæŋɡwɪʤɪz wɪð ˌɪntərˈæktɪv eɪ-aɪ ˈsɒftweə/", "vietnameseMeaning": "Các bậc phụ huynh hài lòng khi con cái họ ngày nay có thể học ngoại ngữ với các phần mềm AI tương tác.", "contextSituation": "Khen ngợi ứng dụng công nghệ giáo dục.", "keyPhonicsFocus": "Phát âm chuẩn cấu trúc 'Parents are pleased that'.", "sampleAudioText": "Parents are pleased that their children can now learn foreign languages with interactive AI software."},
    {"id": "u6-s14", "targetSentence": "It is important for families to maintain regular dinner conversations to bridge the generation gap.", "ipa": "/ɪt ɪz ɪmˈpɔːtənt fɔː ˈfæmɪliz tuː meɪnˈteɪn ˈrɛɡjʊlə ˈdɪnə ˌkɒnvəˈseɪʃənz tuː brɪʤ ðə ˌʤɛnəˈreɪʃən ɡæp/", "vietnameseMeaning": "Việc các gia đình duy trì bữa cơm tối trò chuyện cùng nhau là rất quan trọng để xóa nhòa khoảng cách thế hệ.", "contextSituation": "Lời khuyên giữ gìn hạnh phúc gia đình.", "keyPhonicsFocus": "Phát âm chuẩn từ 'bridge' /brɪʤ/ và 'generation gap'.", "sampleAudioText": "It is important for families to maintain regular dinner conversations to bridge the generation gap."},
    {"id": "u6-s15", "targetSentence": "Before express delivery became popular, sending goods across regions had taken several weeks.", "ipa": "/bɪˈfɔːr ɪksˈprɛs dɪˈlɪvəri bɪˈkeɪm ˈpɒpjʊlə ˈsɛndɪŋ ɡʊdz əˈkrɒs ˈriːʤənz hæd ˈteɪkən ˈsɛvrəl wiːks/", "vietnameseMeaning": "Trước khi dịch vụ chuyển phát nhanh phổ biến, việc gửi hàng hóa giữa các vùng miền từng mất nhiều tuần lễ.", "contextSituation": "Nói về sự phát triển của ngành logistics.", "keyPhonicsFocus": "Phát âm chuẩn Quá khứ hoàn thành 'had taken several weeks'.", "sampleAudioText": "Before express delivery became popular, sending goods across regions had taken several weeks."},
    {"id": "u6-s16", "targetSentence": "We are confident that Viet Nam's economy will continue to thrive and integrate globally.", "ipa": "/wiː ɑː ˈkɒnfɪdənt ðæt ˌvjɛt ˈnɑːmz iːˈkɒnəmi wɪl kənˈtɪnjuː tuː θraɪv ænd ˈɪntɪɡreɪt ˈɡləʊbəli/", "vietnameseMeaning": "Chúng tôi tin tưởng chắc chắn rằng nền kinh tế Việt Nam sẽ tiếp tục phát triển phồn vinh và hội nhập toàn cầu.", "contextSituation": "Khẳng định niềm tin vào tương lai đất nước.", "keyPhonicsFocus": "Phát âm chuẩn cấu trúc 'We are confident that' và 'integrate'.", "sampleAudioText": "We are confident that Viet Nam's economy will continue to thrive and integrate globally."},
    {"id": "u6-s17", "targetSentence": "It was inspiring to watch our historic cities modernize while meticulously safeguarding ancient architecture.", "ipa": "/ɪt wɒz ɪnˈspaɪərɪŋ tuː wɒʧ ˈaʊə hɪsˈtɒrɪk ˈsɪtiz ˈmɒdənaɪz waɪl mɪˈtɪkjʊləsli ˈseɪfɡɑːdɪŋ ˈeɪnʃənt ˈɑːkɪtɛkʧə/", "vietnameseMeaning": "Thật truyền cảm hứng khi thấy các thành phố lịch sử của chúng ta hiện đại hóa mà vẫn bảo tồn tỉ mỉ kiến trúc cổ.", "contextSituation": "Ca ngợi sự kết hợp hài hòa giữa truyền thống và hiện đại.", "keyPhonicsFocus": "Phát âm chuẩn trạng từ 'meticulously' /mɪˈtɪkjʊləsli/.", "sampleAudioText": "It was inspiring to watch our historic cities modernize while meticulously safeguarding ancient architecture."},
    {"id": "u6-s18", "targetSentence": "By the time international flights resumed, the airports had upgraded their automated security terminals.", "ipa": "/baɪ ðə taɪm ˌɪntəˈnæʃənl flaɪts rɪˈzjuːmd ði ˈeəpɔːts hæd ʌpˈɡreɪdɪd ðeər ˈɔːtəmeɪtɪd sɪˈkjʊərɪti ˈtɜːmɪnlz/", "vietnameseMeaning": "Vào thời điểm các chuyến bay quốc tế được nối lại, các sân bay đã nâng cấp hệ thống nhà ga an ninh tự động.", "contextSituation": "Nói về hiện đại hóa cửa khẩu hàng không.", "keyPhonicsFocus": "Phát âm chuẩn 'had upgraded their automated terminals'.", "sampleAudioText": "By the time international flights resumed, the airports had upgraded their automated security terminals."},
    {"id": "u6-s19", "targetSentence": "Vietnamese youth are proud that domestic technological innovations are competing on the global stage.", "ipa": "/ˌvjɛtnəˈmiːz juːθ ɑː praʊd ðæt dəʊˈmɛstɪk ˌtɛknəˈlɒʤɪkəl ˌɪnəˈveɪʃənz ɑː kəmˈpiːtɪŋ ɒn ðə ˈɡləʊbəl steɪʤ/", "vietnameseMeaning": "Tuổi trẻ Việt Nam tự hào rằng những sáng tạo công nghệ trong nước đang tự tin cạnh tranh trên trường quốc tế.", "contextSituation": "Bày tỏ niềm tự hào về trí tuệ công nghệ Việt Nam.", "keyPhonicsFocus": "Phát âm chuẩn cụm từ 'domestic technological innovations'.", "sampleAudioText": "Vietnamese youth are proud that domestic technological innovations are competing on the global stage."},
    {"id": "u6-s20", "targetSentence": "Bridging past values and future modern aspirations creates a resilient and prosperous nation.", "ipa": "/ˈbrɪʤɪŋ pɑːst ˈvæljuːz ænd ˈfjuːʧə ˈmɒdən ˌæspəˈreɪʃənz kriːˈeɪts ə rɪˈzɪlɪənt ænd ˈprɒspərəs ˈneɪʃən/", "vietnameseMeaning": "Kết nối các giá trị quá khứ với khát vọng tương lai hiện đại tạo nên một dân tộc kiên cường và thịnh vượng.", "contextSituation": "Thông điệp đúc kết về hành trình phát triển của dân tộc.", "keyPhonicsFocus": "Phát âm chuẩn tính từ 'prosperous' /ˈprɒspərəs/ và 'aspirations'.", "sampleAudioText": "Bridging past values and future modern aspirations creates a resilient and prosperous nation."}
]

u6_reading_info = {
    "title": "Chuyển Mình Kỳ Diệu: Hành Trình Bứt Phá Đổi Mới Của Việt Nam",
    "topic": "Hiện đại hóa cơ sở hạ tầng & Đời sống xã hội Việt Nam thời kỳ đổi mới",
    "passageText": "Over the past four decades since the initiation of the Doi Moi economic reforms in 1986, Viet Nam has achieved one of the most remarkable development transformations in modern Asian history. From a nation recovering from prolonged war hardships and economic subsidies, the country has ascended to become a vibrant, middle-income powerhouse and a global manufacturing and digital hub.\n\nInfrastructural expansion exemplifies this historic transformation. Decades ago, interprovincial transport was hindered by single-lane unpaved roads and slow ferry crossings. By the time the millennium arrived, modern expressways, suspension bridges over the Red and Mekong Rivers, and deep-water international sea terminals had been established. In metropolitan hubs like Ha Noi and Ho Chi Minh City, modern elevated railways and subterranean metro lines now whisk millions of commuters daily.\n\nEqually profound is the evolution of societal living standards. Thatch-and-mud dwellings have been replaced by resilient brick homes and smart high-rises. High-speed 5G connectivity spans from urban centers to remote highlands, empowering students and entrepreneurs. While embracing digital modernity, Vietnamese communities remain deeply committed to preserving ancestral filial piety, communal solidarity, and cultural identity.",
    "keyVocabularyHighlights": [
        {"word": "economic powerhouse", "meaning": "đầu tàu kinh tế phát triển năng động"},
        {"word": "infrastructural expansion", "meaning": "sự mở rộng vượt bậc của cơ sở hạ tầng"},
        {"word": "deep-water terminals", "meaning": "cảng biển nước sâu quốc tế"},
        {"word": "ancestral filial piety", "meaning": "đạo hiếu thảo kính trọng ông bà cha mẹ"}
    ]
}

u6_reading_qs = [
    {"id": "u6-r1", "question": "What major historic milestone initiated Viet Nam's economic reforms in 1986?", "options": ["A. The Doi Moi reforms", "B. The industrial revolution in Europe", "C. The construction of the first airport", "D. The invention of the bicycle"], "correctAnswerIndex": 0, "explanation": "Trong đoạn 1: 'since the initiation of the Doi Moi economic reforms in 1986.'"},
    {"id": "u6-r2", "question": "How has Viet Nam's socioeconomic status changed over the past four decades?", "options": ["A. It has become a vibrant, middle-income powerhouse and global manufacturing/digital hub", "B. It has remained completely unchanged", "C. It lost all its factories", "D. It banned all international trade"], "correctAnswerIndex": 0, "explanation": "Trong đoạn 1: 'ascended to become a vibrant, middle-income powerhouse and a global manufacturing and digital hub.'"},
    {"id": "u6-r3", "question": "What hindered interprovincial transport in Viet Nam decades ago?", "options": ["A. Single-lane unpaved roads and slow ferry crossings", "B. High-speed airplanes", "C. Underground metro lines", "D. Bullet trains"], "correctAnswerIndex": 0, "explanation": "Trong đoạn 2: 'hindered by single-lane unpaved roads and slow ferry crossings.'"},
    {"id": "u6-r4", "question": "What modern transport projects have been constructed across the Red and Mekong Rivers?", "options": ["A. Modern suspension bridges and expressways", "B. Temporary wooden rafts", "C. Floating bamboo walkways", "D. Clay dikes only"], "correctAnswerIndex": 0, "explanation": "Trong đoạn 2: 'suspension bridges over the Red and Mekong Rivers.'"},
    {"id": "u6-r5", "question": "What has replaced traditional thatch-and-mud dwellings across the country?", "options": ["A. Resilient brick homes and smart high-rise apartments", "B. Plastic tents", "C. Underground holes", "D. Wooden tree houses"], "correctAnswerIndex": 0, "explanation": "Trong đoạn 3: 'Thatch-and-mud dwellings have been replaced by resilient brick homes and smart high-rises.'"},
    {"id": "u6-r6", "question": "How far does high-speed 5G telecommunication connectivity reach today?", "options": ["A. From urban centers to remote mountain highlands", "B. Only inside one library", "C. Only in foreign airports", "D. Nowhere in the country"], "correctAnswerIndex": 0, "explanation": "Trong đoạn 3: 'High-speed 5G connectivity spans from urban centers to remote highlands.'"},
    {"id": "u6-r7", "question": "Which word in paragraph 1 is closest in meaning to 'ascended'?", "options": ["A. Risen and climbed up successfully", "B. Fallen down", "C. Stopped working", "D. Decreased"], "correctAnswerIndex": 0, "explanation": "'Ascended' có nghĩa là vươn lên, nâng cao vị thế (ascended to become a powerhouse)."},
    {"id": "u6-r8", "question": "Which word in paragraph 2 is closest in meaning to 'whisk'?", "options": ["A. Transport rapidly and smoothly", "B. Walk slowly", "C. Wait for hours", "D. Break down"], "correctAnswerIndex": 0, "explanation": "'Whisk commuters' có nghĩa là vận chuyển nhanh chóng, êm ái."},
    {"id": "u6-r9", "question": "What cultural values do Vietnamese communities remain deeply committed to preserving?", "options": ["A. Ancestral filial piety, communal solidarity, and cultural identity", "B. Complete isolation from neighbors", "C. Forgetting old traditions", "D. Living without families"], "correctAnswerIndex": 0, "explanation": "Trong đoạn 3: 'preserving ancestral filial piety, communal solidarity, and cultural identity.'"},
    {"id": "u6-r10", "question": "What is the best overall title for this reading passage?", "options": ["A. The Dangers of Flying in Fog", "B. A Miraculous Transformation: Viet Nam's Journey of Innovation & Growth", "C. How to Construct a Suspension Bridge", "D. The History of Ancient Wooden Boats"], "correctAnswerIndex": 1, "explanation": "Bài đọc tổng kết hành trình chuyển mình kỳ diệu và bứt phá đổi mới của Việt Nam."}
]

u6_writing_prompts = [
    {
        "id": "u6-w1",
        "title": "Đề 1: Write a paragraph describing changes in your hometown over the past decade (60-80 words)",
        "description": "Viết một đoạn văn miêu tả những thay đổi tích cực ở quê hương em trong 10 năm qua (đường sá, trường học, nhà cửa, công nghệ...).",
        "suggestedOutline": [
            "Introduction: State that your hometown has undergone remarkable changes.",
            "Body: Contrast past conditions (dirt paths, small houses) with modern improvements (concrete roads, smart schools, streetlights).",
            "Conclusion: Express your joy and pride in these positive transformations."
        ],
        "usefulPhrases": [
            "Over the past decade, my hometown has experienced a dramatic transformation...",
            "In the past, villagers had traveled on bumpy dirt roads...",
            "Today, new concrete highways, modern schools, and streetlights have been built...",
            "I am extremely proud to see my hometown developing so rapidly."
        ],
        "wordLimit": "60 - 80 từ",
        "sampleGrade10Response": "Over the past decade, my hometown has experienced a dramatic and heartwarming transformation. Ten years ago, residents had travelled on dusty, unpaved dirt roads that flooded during monsoon rains. Today, wide asphalt highways, modern multi-story schools, and solar streetlights have been constructed. Furthermore, every household now enjoys high-speed internet and clean tap water. I am delighted and proud to see my hometown developing into a civilized and prosperous community."
    },
    {
        "id": "u6-w2",
        "title": "Đề 2: Write a paragraph comparing transportation in Viet Nam: then and now (60-80 words)",
        "description": "Viết một đoạn văn so sánh phương tiện giao thông ở Việt Nam ngày xưa và ngày nay.",
        "suggestedOutline": [
            "Introduction: Introduce the evolution of Vietnamese transportation.",
            "Body: Describe past travel (bicycles, tramcars, slow ferries) vs. modern travel (elevated trains, electric buses, expressways).",
            "Conclusion: Confirm that modern transit makes daily life faster and more convenient."
        ],
        "usefulPhrases": [
            "Transportation in Viet Nam has changed beyond recognition...",
            "Decades ago, most people had relied on simple bicycles or tramcars...",
            "Nowadays, commuters can travel quickly via elevated railways and electric buses...",
            "These modern transit systems have made daily commute effortless and comfortable."
        ],
        "wordLimit": "60 - 80 từ",
        "sampleGrade10Response": "Transportation in Viet Nam has changed beyond recognition over the past few decades. In the 1980s, citizens had relied mainly on rickety bicycles, walking barefoot, or electric tramcars. Today, our major cities are connected by modern elevated railways, zero-emission electric buses, and multi-lane expressways. Traveling between provinces that once took entire days now requires only a few hours. Modern transport infrastructure has truly made our lives faster, safer, and far more convenient."
    },
    {
        "id": "u6-w3",
        "title": "Đề 3: Write a paragraph about how technology has improved learning for students (60-80 words)",
        "description": "Viết một đoạn văn nêu các lợi ích của công nghệ số và internet đối với việc học tập của học sinh ngày nay.",
        "suggestedOutline": [
            "Introduction: State that technology has revolutionized modern education.",
            "Body: Highlight advantages (online encyclopedias, interactive smartboards, AI language practice).",
            "Conclusion: Conclude on how technology empowers self-study."
        ],
        "usefulPhrases": [
            "Modern technology has completely revolutionized how students learn today...",
            "Before the digital age, students had spent hours searching through paper dictionaries...",
            "Now, we can access global digital courses and interactive AI learning apps...",
            "Technology empowers students to expand their knowledge anytime, anywhere."
        ],
        "wordLimit": "60 - 80 từ",
        "sampleGrade10Response": "Modern technology has revolutionized the way Vietnamese students acquire knowledge. In the past, students had spent hours searching through scarce paper textbooks in libraries. Today, with high-speed internet and smartphones, learners can access vast online encyclopedias, watch scientific lectures, and practice English with interactive AI apps. Digital classrooms equipped with smartboards make lessons engaging and vivid. Technology has empowered teenagers to study flexibly and connect with global educational resources."
    },
    {
        "id": "u6-w4",
        "title": "Đề 4: Write a paragraph suggesting ways to bridge the generation gap in modern families (60-80 words)",
        "description": "Viết một đoạn văn đề xuất cách thu hẹp khoảng cách thế hệ giữa con cháu và ông bà cha mẹ.",
        "suggestedOutline": [
            "Introduction: State why the generation gap happens in modern society.",
            "Body: Give 2 practical solutions (eating meals together, teaching grandparents technology, listening patiently).",
            "Conclusion: Reiterate that mutual empathy keeps families united."
        ],
        "usefulPhrases": [
            "To bridge the generation gap in modern families, mutual empathy is essential...",
            "First, family members should maintain regular daily dinners without smartphone distractions...",
            "Second, teenagers can patiently teach grandparents how to use video calls...",
            "Open communication and respect foster warmth and lasting family harmony."
        ],
        "wordLimit": "60 - 80 từ",
        "sampleGrade10Response": "Bridging the generation gap is essential for maintaining strong family harmony in our fast-paced society. First, family members should sit down together for regular home-cooked dinners without smartphone distractions. Second, teenagers ought to listen patiently to their grandparents' life stories and teach them how to use video calls on tablets. Respecting differences in viewpoints while showing gratitude creates deep empathy and keeps multi-generational families closely united and loving."
    },
    {
        "id": "u6-w5",
        "title": "Đề 5: Write a paragraph expressing your pride in Viet Nam's development (60-80 words)",
        "description": "Viết một đoạn văn bày tỏ niềm tự hào trước những thành tựu đổi mới và phát triển của đất nước.",
        "suggestedOutline": [
            "Introduction: Express immense pride in Viet Nam's socioeconomic progress.",
            "Body: Mention achievements (modern skyscrapers, bridges, global integration, poverty reduction).",
            "Conclusion: Express your commitment as a young citizen to contribute to the nation."
        ],
        "usefulPhrases": [
            "I feel immense pride when witnessing the rapid progress of Viet Nam...",
            "From a war-torn country, our nation has transformed into an energetic economic hub...",
            "Modern infrastructure, high living standards, and technological advances show our resilience...",
            "As a student, I am motivated to study hard to contribute to our beloved fatherland."
        ],
        "wordLimit": "60 - 80 từ",
        "sampleGrade10Response": "I feel immense pride whenever I reflect upon Viet Nam's breathtaking developmental journey. Overcoming historical adversities, our fatherland has risen to become a dynamic, prosperous, and respected nation on the international stage. Modern skyscrapers, expanding metro networks, and technological innovations reflect our people's unyielding diligence and resilience. As young Vietnamese students, we are deeply inspired to study diligently and cultivate noble skills to contribute to our country's bright future."
    }
]

unit6 = make_unit(6, "Unit 6: Viet Nam: Then and Now", "Việt Nam: Xưa và Nay & Đời sống xã hội", "Tìm hiểu sự chuyển mình của Việt Nam qua các thời kỳ, thì Quá khứ hoàn thành (Past Perfect) và cấu trúc Tính từ + To-V / That clause.", "Ngữ âm: Nhấn trọng âm từ có hậu tố -ic, -ical và ngữ điệu biểu cảm tính từ", "GraduationCap", u6_vocab, u6_grammar_info, u6_grammar_exs, u6_listening_info, u6_listening_qs, u6_listening_fibs, u6_speaking, u6_reading_info, u6_reading_qs, u6_writing_prompts)
write_ts_unit(6, unit6)

print("Unit 6 generated successfully!")
