import json
from gen_unit_utils import make_unit, write_ts_unit

# ==============================================================================
# UNIT 9: WORLD ENGLISHES (20 Vocab, 20 Grammar, 8 Listening MC + 4 FIB, 20 Speaking, 10 Reading, 5 Writing)
# ==============================================================================
u9_vocab = [
    {"id": "u9-v1", "word": "lingua franca", "phonetic": "/ˌlɪŋɡwə ˈfræŋkə/", "partOfSpeech": "noun", "vietnameseMeaning": "ngôn ngữ chung toàn cầu để giao tiếp quốc tế", "englishExample": "English has established itself as the global lingua franca in international diplomacy, commerce, and aviation.", "vietnameseExample": "Tiếng Anh đã khẳng định vị thế là ngôn ngữ chung toàn cầu trong ngoại giao quốc tế, thương mại và hàng không."},
    {"id": "u9-v2", "word": "native speaker", "phonetic": "/ˈneɪtɪv ˈspiːkə/", "partOfSpeech": "noun", "vietnameseMeaning": "người bản ngữ", "englishExample": "Interacting with both native speakers and international learners enhances communicative agility.", "vietnameseExample": "Tương tác với cả người bản ngữ và người học quốc tế giúp nâng cao sự linh hoạt trong giao tiếp."},
    {"id": "u9-v3", "word": "bilingual", "phonetic": "/baɪˈlɪŋɡwəl/", "partOfSpeech": "adjective", "vietnameseMeaning": "sử dụng song ngữ thành thạo", "englishExample": "Raising bilingual children enhances their cognitive flexibility and cultural empathy.", "vietnameseExample": "Nuôi dạy trẻ em song ngữ giúp nâng cao sự linh hoạt trong nhận thức và lòng thấu cảm văn hóa."},
    {"id": "u9-v4", "word": "accent", "phonetic": "/ˈæksənt/", "partOfSpeech": "noun", "vietnameseMeaning": "chất giọng, ngữ điệu vùng miền", "englishExample": "Every regional English accent, from Scottish to Australian, carries unique phonetic charm.", "vietnameseExample": "Mỗi chất giọng tiếng Anh vùng miền, từ Scotland đến Úc, đều mang một nét quyến rũ ngữ âm độc đáo."},
    {"id": "u9-v5", "word": "dialect", "phonetic": "/ˈdaɪəlɛkt/", "partOfSpeech": "noun", "vietnameseMeaning": "tiếng địa phương, thổ ngữ", "englishExample": "Linguists study regional dialects to trace the historical migration of English-speaking communities.", "vietnameseExample": "Các nhà ngôn ngữ học nghiên cứu thổ ngữ địa phương để lần theo lịch sử di cư của các cộng đồng nói tiếng Anh."},
    {"id": "u9-v6", "word": "multilingual", "phonetic": "/ˌmʌltɪˈlɪŋɡwəl/", "partOfSpeech": "adjective", "vietnameseMeaning": "đa ngôn ngữ (nói từ 3 thứ tiếng trở lên)", "englishExample": "Singapore is a shining example of a prosperous multilingual society.", "vietnameseExample": "Singapore là một tấm gương sáng về một xã hội đa ngôn ngữ thịnh vượng."},
    {"id": "u9-v7", "word": "fluency", "phonetic": "/ˈfluːənsi/", "partOfSpeech": "noun", "vietnameseMeaning": "sự lưu loát, trôi chảy tự nhiên", "englishExample": "Daily speaking practice in real-life scenarios is the fastest pathway to communicative fluency.", "vietnameseExample": "Luyện nói hàng ngày trong các tình huống thực tế là con đường nhanh nhất để đạt được sự lưu loát trong giao tiếp."},
    {"id": "u9-v8", "word": "mother tongue", "phonetic": "/ˈmʌðə tʌŋ/", "partOfSpeech": "noun", "vietnameseMeaning": "tiếng mẹ đẻ", "englishExample": "Vietnamese is our cherished mother tongue that binds our cultural identity together.", "vietnameseExample": "Tiếng Việt là tiếng mẹ đẻ thiêng liêng gắn kết bản sắc văn hóa của chúng ta."},
    {"id": "u9-v9", "word": "intonation", "phonetic": "/ˌɪntəˈneɪʃən/", "partOfSpeech": "noun", "vietnameseMeaning": "ngữ điệu lên xuống của câu", "englishExample": "Mastering natural intonation helps convey emotional nuance and subtle irony.", "vietnameseExample": "Làm chủ ngữ điệu tự nhiên giúp truyền tải sắc thái cảm xúc và sự châm biếm tinh tế."},
    {"id": "u9-v10", "word": "official language", "phonetic": "/əˈfɪʃəl ˈlæŋɡwɪʤ/", "partOfSpeech": "noun", "vietnameseMeaning": "ngôn ngữ chính thức của quốc gia", "englishExample": "English functions as an official language in more than fifty sovereign nations across the globe.", "vietnameseExample": "Tiếng Anh đóng vai trò là ngôn ngữ chính thức tại hơn 50 quốc gia có chủ quyền trên toàn cầu."},
    {"id": "u9-v11", "word": "slang", "phonetic": "/slæŋ/", "partOfSpeech": "noun", "vietnameseMeaning": "từ lóng thông tục", "englishExample": "Teenagers frequently adopt vibrant internet slang when messaging peers on social media.", "vietnameseExample": "Thanh thiếu niên thường xuyên sử dụng từ lóng internet sôi nổi khi nhắn tin cho bạn bè trên mạng xã hội."},
    {"id": "u9-v12", "word": "idiomatic expression", "phonetic": "/ˌɪdɪəˈmætɪk ɪksˈprɛʃən/", "partOfSpeech": "noun", "vietnameseMeaning": "thành ngữ, cách diễn đạt đặc ngữ", "englishExample": "Learning idiomatic expressions makes your spoken English sound remarkably authentic and vivid.", "vietnameseExample": "Học các cách diễn đạt thành ngữ giúp tiếng Anh giao tiếp của bạn nghe cực kỳ tự nhiên và sinh động."},
    {"id": "u9-v13", "word": "loanword", "phonetic": "/ˈləʊnwɜːd/", "partOfSpeech": "noun", "vietnameseMeaning": "từ mượn từ ngôn ngữ khác", "englishExample": "English incorporates thousands of historical loanwords from French, Latin, and Greek.", "vietnameseExample": "Tiếng Anh kết nạp hàng ngàn từ mượn lịch sử từ tiếng Pháp, tiếng Latinh và tiếng Hy Lạp."},
    {"id": "u9-v14", "word": "proficiency", "phonetic": "/prəˈfɪʃənsi/", "partOfSpeech": "noun", "vietnameseMeaning": "năng lực thành thạo chuyên môn", "englishExample": "High English proficiency opens doors to prestigious international scholarships and global careers.", "vietnameseExample": "Năng lực tiếng Anh thành thạo mở ra cánh cửa dẫn đến các học bổng quốc tế danh giá và nghề nghiệp toàn cầu."},
    {"id": "u9-v15", "word": "lexicon", "phonetic": "/ˈlɛksɪkən/", "partOfSpeech": "noun", "vietnameseMeaning": "vốn từ vựng, từ điển ngữ nghĩa", "englishExample": "Technological advancements constantly inject innovative terms into the modern English lexicon.", "vietnameseExample": "Những tiến bộ công nghệ liên tục bổ sung các thuật ngữ sáng tạo vào vốn từ vựng tiếng Anh hiện đại."},
    {"id": "u9-v16", "word": "cross-cultural communication", "phonetic": "/krɒs-ˈkʌlʧərəl kəˌmjuːnɪˈkeɪʃən/", "partOfSpeech": "noun", "vietnameseMeaning": "giao tiếp đa văn hóa", "englishExample": "Effective cross-cultural communication requires mutual empathy, open-mindedness, and active listening.", "vietnameseExample": "Giao tiếp đa văn hóa hiệu quả đòi hỏi sự thấu cảm lẫn nhau, tư duy cởi mở và kỹ năng lắng nghe chủ động."},
    {"id": "u9-v17", "word": "phonetics", "phonetic": "/fəˈnɛtɪks/", "partOfSpeech": "noun", "vietnameseMeaning": "ngữ âm học", "englishExample": "Studying the International Phonetic Alphabet (IPA) allows students to pronounce unfamiliar vocabulary accurately.", "vietnameseExample": "Học Bảng Ký Hiệu Ngữ Âm Quốc Tế (IPA) giúp học sinh phát âm chuẩn xác các từ vựng mới lạ."},
    {"id": "u9-v18", "word": "standard English", "phonetic": "/ˈstændəd ˈɪŋɡlɪʃ/", "partOfSpeech": "noun", "vietnameseMeaning": "tiếng Anh chuẩn mực học thuật", "englishExample": "Academic dissertations and diplomatic publications adhere strictly to standard English conventions.", "vietnameseExample": "Các luận văn học thuật và ấn phẩm ngoại giao luôn tuân thủ nghiêm ngặt các quy chuẩn tiếng Anh chuẩn mực."},
    {"id": "u9-v19", "word": "linguistic diversity", "phonetic": "/lɪŋˈɡwɪstɪk daɪˈvɜːsɪti/", "partOfSpeech": "noun", "vietnameseMeaning": "sự đa dạng ngôn ngữ", "englishExample": "Preserving global linguistic diversity protects unique philosophical systems and indigenous knowledge.", "vietnameseExample": "Gìn giữ sự đa dạng ngôn ngữ toàn cầu bảo vệ những hệ thống triết học và tri thức bản địa độc đáo."},
    {"id": "u9-v20", "word": "mastery", "phonetic": "/ˈmɑːstəri/", "partOfSpeech": "noun", "vietnameseMeaning": "sự tinh thông, làm chủ thuần thục", "englishExample": "True language mastery transcends memorizing grammar; it embodies the ability to connect deeply with human souls.", "vietnameseExample": "Sự tinh thông ngôn ngữ thực sự vượt xa việc ghi nhớ ngữ pháp; nó thể hiện khả năng kết nối sâu sắc với tâm hồn con người."}
]

u9_grammar_info = {
    "title": "Câu Điều Kiện Loại 2 (Conditional Type 2: Unreal Condition in the Present/Future)",
    "summary": "Nắm vững cấu trúc câu điều kiện loại 2 dùng để diễn tả điều kiện trái ngược với thực tế ở hiện tại hoặc tương lai, đưa ra lời khuyên (If I were you) hoặc giả định viễn cảnh.",
    "formulaBox": [
        "Mệnh đề If: If + S + V-ed / V2 (To be dùng 'WERE' cho tất cả các ngôi)",
        "Mệnh đề chính: S + WOULD / COULD / MIGHT + V-inf",
        "Ví dụ: If I WERE fluent in English, I WOULD APPLY for an international scholarship in Oxford.",
        "Ví dụ: If she SPOKE multiple foreign languages, she COULD WORK as a United Nations interpreter.",
        "Ví dụ: If I WERE YOU, I WOULD PRACTICE English pronunciation every morning with Thầy David."
    ],
    "usagePoints": [
        {"title": "1. Giả định trái với hiện tại", "detail": "Diễn tả sự việc không có thật ở hiện tại: I don't live in London -> If I lived in London, I would visit Big Ben.", "example": "If I had more time, I would learn Spanish as a third language."},
        {"title": "2. Lời khuyên chân thành", "detail": "Cấu trúc 'If I were you, I would/wouldn't + V' là cách đưa ra lời khuyên lịch sự và tự nhiên nhất.", "example": "If I were you, I would listen to English podcasts every single day."}
    ]
}

u9_grammar_exs = [
    {"id": "u9-g1", "question": "If I _____ you, I would practice speaking English with native speakers regularly.", "options": ["A. were", "B. was", "C. am", "D. have been"], "correctAnswer": "A. were", "explanation": "Trong câu điều kiện loại 2, 'were' được ưu tiên sử dụng cho mọi chủ ngữ trong mệnh đề If: 'If I were you...'."},
    {"id": "u9-g2", "question": "If Linh spoke fluent English, she _____ apply for an overseas exchange scholarship in Canada.", "options": ["A. could", "B. can", "C. will", "D. shall"], "correctAnswer": "A. could", "explanation": "Mệnh đề chính trong câu điều kiện loại 2: S + would/could/might + V-inf -> 'she could apply'."},
    {"id": "u9-g3", "question": "If we _____ in an English-speaking country, our communicative pronunciation would improve rapidly.", "options": ["A. lived", "B. live", "C. have lived", "D. are living"], "correctAnswer": "A. lived", "explanation": "Mệnh đề If ở điều kiện loại 2 dùng Quá khứ đơn: 'If we lived...'."},
    {"id": "u9-g4", "question": "What _____ you do if you had the opportunity to study linguistics at Cambridge University?", "options": ["A. would", "B. will", "C. can", "D. do"], "correctAnswer": "A. would", "explanation": "Câu hỏi điều kiện loại 2: 'What would you do if you had...'."},
    {"id": "u9-g5", "question": "If Nam _____ more English vocabulary, he would write essays much more effortlessly.", "options": ["A. knew", "B. knows", "C. has known", "D. is knowing"], "correctAnswer": "A. knew", "explanation": "Mệnh đề If loại 2 dùng V2/V-ed: 'If Nam knew...'."},
    {"id": "u9-g6", "question": "If she had enough confidence, she _____ join the national English debating championship.", "options": ["A. would", "B. will", "C. can", "D. shall"], "correctAnswer": "A. would", "explanation": "Mệnh đề chính loại 2: 'she would join...'."},
    {"id": "u9-g7", "question": "If I _____ a bilingual dictionary right now, I could look up these challenging idioms immediately.", "options": ["A. possessed", "B. possess", "C. have possessed", "D. will possess"], "correctAnswer": "A. possessed", "explanation": "Mệnh đề If loại 2 dùng V-ed 'possessed'."},
    {"id": "u9-g8", "question": "If people around the world _____ only one universal language, cultural diversity might decline.", "options": ["A. spoke", "B. speak", "C. will speak", "D. have spoken"], "correctAnswer": "A. spoke", "explanation": "Mệnh đề If loại 2: 'If people around the world spoke...'."},
    {"id": "u9-g9", "question": "If my brother were taller, he _____ play professional basketball for the national team.", "options": ["A. could", "B. can", "C. will", "D. may"], "correctAnswer": "A. could", "explanation": "Mệnh đề chính loại 2: 'he could play...'."},
    {"id": "u9-g10", "question": "I would travel to New Zealand to practice English if I _____ enough holiday savings.", "options": ["A. had", "B. have", "C. will have", "D. am having"], "correctAnswer": "A. had", "explanation": "Mệnh đề If loại 2: 'if I had...'."},
    {"id": "u9-g11", "question": "If you _____ English podcasts every day, your listening comprehension would sharpen quickly.", "options": ["A. listened to", "B. listen to", "C. have listened to", "D. will listen to"], "correctAnswer": "A. listened to", "explanation": "Mệnh đề If loại 2: 'If you listened to...'."},
    {"id": "u9-g12", "question": "If she were the minister of education, she _____ introduce multilingual immersion programs in all schools.", "options": ["A. would", "B. will", "C. can", "D. shall"], "correctAnswer": "A. would", "explanation": "Mệnh đề chính loại 2: 'she would introduce...'."},
    {"id": "u9-g13", "question": "We _____ understand Australian accents more easily if we watched more Australian films.", "options": ["A. would", "B. will", "C. can", "D. may"], "correctAnswer": "A. would", "explanation": "Mệnh đề chính loại 2: 'We would understand...'."},
    {"id": "u9-g14", "question": "If the weather _____ not so stormy today, we would go on a walking tour around the British Museum.", "options": ["A. were", "B. is", "C. will be", "D. has been"], "correctAnswer": "A. were", "explanation": "Mệnh đề If loại 2: 'If the weather were not...'."},
    {"id": "u9-g15", "question": "If I _____ a magic wand, I would eliminate all communication barriers between nations.", "options": ["A. had", "B. have", "C. will have", "D. am having"], "correctAnswer": "A. had", "explanation": "Mệnh đề If loại 2: 'If I had...'."},
    {"id": "u9-g16", "question": "Mai would master the International Phonetic Alphabet much faster if she _____ Thầy David's audio guides.", "options": ["A. followed", "B. follows", "C. will follow", "D. has followed"], "correctAnswer": "A. followed", "explanation": "Mệnh đề If loại 2: 'if she followed...'."},
    {"id": "u9-g17", "question": "If there _____ no internet, global cross-cultural communication would be much more difficult.", "options": ["A. were", "B. is", "C. will be", "D. has been"], "correctAnswer": "A. were", "explanation": "Mệnh đề If loại 2: 'If there were no internet...'."},
    {"id": "u9-g18", "question": "He _____ buy English storybooks for all his students if he won the teaching excellence award.", "options": ["A. would", "B. will", "C. can", "D. shall"], "correctAnswer": "A. would", "explanation": "Mệnh đề chính loại 2: 'He would buy...'."},
    {"id": "u9-g19", "question": "If teenagers spent less time gaming and more time reading, their English lexicon _____ expand significantly.", "options": ["A. would", "B. will", "C. can", "D. must"], "correctAnswer": "A. would", "explanation": "Mệnh đề chính loại 2: 'their English lexicon would expand...'."},
    {"id": "u9-g20", "question": "If I were in your shoes, I _____ hesitate to enroll in the advanced bilingual debate seminar.", "options": ["A. would not", "B. will not", "C. cannot", "D. must not"], "correctAnswer": "A. would not", "explanation": "Lời khuyên loại 2: 'If I were in your shoes, I would not hesitate...'."}
]

u9_listening_info = {
    "audioTitle": "Sự Đa Dạng Của Tiếng Anh Toàn Cầu (World Englishes & Global Communication)",
    "audioDuration": "3:25",
    "audioScriptSpeaker": "Linguistics Professor Dr. Robert & Student Ha",
    "transcriptText": "Ha: Professor Robert, why is English referred to as 'World Englishes' in the plural form rather than just a single language?\nDr. Robert: Hello Ha! That is a fascinating question. Today, non-native English speakers vastly outnumber native speakers. As English spread across continents, diverse regional varieties emerged—such as British English, American English, Australian English, Indian English, and Singaporean Singlish. Each variety reflects its unique phonetic rhythm, idioms, and cultural identity!\nHa: Does one variety hold superiority over the others?\nDr. Robert: Not at all! Modern linguistics emphasizes mutual intelligibility and communicative efficacy rather than rigid native accents. If you speak clearly with natural intonation, your message will bridge cultures effectively worldwide.\nHa: What advice would you give Vietnamese learners striving for fluency?\nDr. Robert: If I were you, I would immerse myself in authentic listening materials daily, fearlessly embrace speaking opportunities, and cherish your own bilingual Vietnamese voice!",
    "vietnameseTranslation": "Hà: Thưa Giáo sư Robert, tại sao tiếng Anh lại được gọi là 'World Englishes' ở dạng số nhiều thay vì chỉ là một ngôn ngữ đơn lẻ ạ?\nGiáo sư Robert: Chào Hà! Đó là một câu hỏi rất thú vị. Ngày nay, số người nói tiếng Anh không phải tiếng mẹ đẻ đã vượt xa số người bản ngữ. Khi tiếng Anh lan tỏa khắp các châu lục, các biến thể vùng miền đa dạng đã xuất hiện—chẳng hạn như tiếng Anh-Anh, Anh-Mỹ, Anh-Úc, Anh-Ấn và tiếng Anh Singlish của Singapore. Mỗi biến thể phản ánh nhịp điệu ngữ âm, thành ngữ và bản sắc văn hóa độc đáo riêng!\nHà: Liệu có một biến thể nào vượt trội hay chuẩn mực hơn các biến thể khác không ạ?\nGiáo sư Robert: Hoàn toàn không! Ngôn ngữ học hiện đại nhấn mạnh vào sự thông hiểu lẫn nhau và hiệu quả giao tiếp hơn là những chất giọng bản ngữ cứng nhắc. Nếu em nói rõ ràng với ngữ điệu tự nhiên, thông điệp của em sẽ kết nối các nền văn hóa một cách hiệu quả trên toàn thế giới.\nHà: Giáo sư có lời khuyên nào cho học sinh Việt Nam đang nỗ lực đạt được sự lưu loát không ạ?\nGiáo sư Robert: Nếu thầy là em, thầy sẽ đắm mình vào các tài liệu nghe thực tế mỗi ngày, dũng cảm nắm bắt mọi cơ hội giao tiếp và tự hào về giọng nói song ngữ Việt Nam của chính mình!"
}

u9_listening_qs = [
    {"id": "u9-l1", "question": "Why is the plural term 'World Englishes' used according to Dr. Robert?", "options": ["A. Because non-native speakers outnumber natives and diverse regional varieties exist", "B. Because English was invented on Mars", "C. Because only five people speak English", "D. Because English is disappearing"], "correctAnswerIndex": 0, "explanation": "Trong bài nghe: 'non-native English speakers vastly outnumber native speakers... diverse regional varieties emerged.'"},
    {"id": "u9-l2", "question": "Which varieties of English did Dr. Robert mention?", "options": ["A. British, American, Australian, Indian, and Singaporean English", "B. Only Shakespearean 16th century English", "C. Secret code dialects only", "D. Silent sign language only"], "correctAnswerIndex": 0, "explanation": "Trong bài nghe: 'British English, American English, Australian English, Indian English, and Singaporean Singlish.'"},
    {"id": "u9-l3", "question": "What does each regional variety of English reflect?", "options": ["A. Its unique phonetic rhythm, idioms, and cultural identity", "B. The number of cars in the city", "C. The price of gold", "D. Weather temperatures"], "correctAnswerIndex": 0, "explanation": "Trong bài nghe: 'reflects its unique phonetic rhythm, idioms, and cultural identity!'"},
    {"id": "u9-l4", "question": "Does one variety of English hold superiority over others?", "options": ["A. Not at all; modern linguistics values mutual intelligibility", "B. Yes, only British English is allowed", "C. Yes, only American English is correct", "D. No one should speak English"], "correctAnswerIndex": 0, "explanation": "Trong bài nghe: 'Not at all! Modern linguistics emphasizes mutual intelligibility and communicative efficacy.'"},
    {"id": "u9-l5", "question": "What two elements are prioritized in modern global communication?", "options": ["A. Mutual intelligibility and communicative efficacy", "B. Fast running and high jumping", "C. Perfect mimicry of actors", "D. Speaking as fast as a machine"], "correctAnswerIndex": 0, "explanation": "Trong bài nghe: 'emphasizes mutual intelligibility and communicative efficacy rather than rigid native accents.'"},
    {"id": "u9-l6", "question": "What happens if you speak clearly with natural intonation?", "options": ["A. Your message will bridge cultures effectively worldwide", "B. No one will understand you", "C. All computers will shut down", "D. Nothing happens"], "correctAnswerIndex": 0, "explanation": "Trong bài nghe: 'If you speak clearly with natural intonation, your message will bridge cultures effectively worldwide.'"},
    {"id": "u9-l7", "question": "What is Dr. Robert's advice for learners aiming for fluency?", "options": ["A. Immerse in authentic listening daily, embrace speaking opportunities, and cherish bilingual identity", "B. Stop speaking English completely", "C. Memorize dictionary pages silently without speaking", "D. Never listen to audio"], "correctAnswerIndex": 0, "explanation": "Trong bài nghe: 'immerse myself in authentic listening materials daily, fearlessly embrace speaking opportunities, and cherish your own bilingual Vietnamese voice!'"},
    {"id": "u9-l8", "question": "What core attitude toward one's bilingual voice is encouraged?", "options": ["A. Cherishing and feeling proud of one's authentic bilingual voice", "B. Feeling ashamed and hiding it", "C. Erasing Vietnamese identity completely", "D. Refusing to communicate"], "correctAnswerIndex": 0, "explanation": "Thông điệp cốt lõi là tự hào và tự tin với tiếng nói song ngữ của chính mình."}
]

u9_listening_fibs = [
    {"id": "u9-f1", "sentenceWithBlank": "Diverse regional _____ of English emerged across continents.", "correctWord": "varieties", "hint": "Các biến thể (varieties)"},
    {"id": "u9-f2", "sentenceWithBlank": "Modern linguistics prioritizes mutual _____ over rigid accents.", "correctWord": "intelligibility", "hint": "Sự thông hiểu lẫn nhau (intelligibility)"},
    {"id": "u9-f3", "sentenceWithBlank": "Natural _____ helps convey your message effectively worldwide.", "correctWord": "intonation", "hint": "Ngữ điệu (intonation)"},
    {"id": "u9-f4", "sentenceWithBlank": "Students should fearlessly embrace speaking _____.", "correctWord": "opportunities", "hint": "Những cơ hội (opportunities)"}
]

u9_speaking = [
    {"id": f"u9-s{i+1}", "targetSentence": s, "ipa": ipa, "vietnameseMeaning": vm, "contextSituation": ctx, "keyPhonicsFocus": kpf, "sampleAudioText": s}
    for i, (s, ipa, vm, ctx, kpf) in enumerate([
        ("English functions as a global lingua franca connecting millions of multilingual citizens across diverse continents.", "/ˈɪŋɡlɪʃ ˈfʌŋkʃənz æz ə ˈɡləʊbəl ˈlɪŋɡwə ˈfræŋkə kəˈnɛktɪŋ ˈmɪljənz ɒv ˌmʌltɪˈlɪŋɡwəl ˈsɪtɪznz əˈkrɒs daɪˈvɜːs ˈkɒntɪnənts/", "Tiếng Anh đóng vai trò là một ngôn ngữ chung toàn cầu kết nối hàng triệu công dân đa ngôn ngữ khắp các châu lục.", "Thuyết trình về vị thế tiếng Anh toàn cầu.", "Phát âm chuẩn 'lingua franca' /ˈlɪŋɡwə ˈfræŋkə/ và 'multilingual' /ˌmʌltɪˈlɪŋɡwəl/."),
        ("If I were fluent in English, I would confidently apply for prestigious international academic scholarships in Oxford.", "/ɪf aɪ wɜː ˈfluːənt ɪn ˈɪŋɡlɪʃ aɪ wʊd ˈkɒnfɪdəntli əˈplaɪ fɔː prɛˈstɪʤəs ˌɪntəˈnæʃənl ˌækəˈdɛmɪk ˈskɒləʃɪps ɪn ˈɒksfəd/", "Nếu tôi thông thạo tiếng Anh, tôi sẽ tự tin nộp hồ sơ xin các học bổng học thuật quốc tế danh giá tại Oxford.", "Bày tỏ ước mơ du học bằng câu điều kiện loại 2.", "Phát âm chuẩn 'If I were fluent' và 'prestigious scholarships' /prɛˈstɪʤəs ˈskɒləʃɪps/."),
        ("Non-native English speakers vastly outnumber native speakers, creating rich and vibrant World Englishes varieties.", "/nɒn-ˈneɪtɪv ˈɪŋɡlɪʃ ˈspiːkəz ˈvɑːstli aʊtˈnʌmbə ˈneɪtɪv ˈspiːkəz kriˈeɪtɪŋ rɪʧ ænd ˈvaɪbrənt wɜːld ˈɪŋɡlɪʃɪz vəˈraɪətiz/", "Số người nói tiếng Anh phi bản ngữ vượt xa người bản ngữ, tạo nên các biến thể Tiếng Anh Toàn Cầu phong phú và sôi nổi.", "Nói về hiện tượng World Englishes.", "Phát âm chuẩn 'outnumber' /aʊtˈnʌmbə/ và 'varieties' /vəˈraɪətiz/."),
        ("If we practiced communicative speaking daily with Thầy David, our natural intonation would flourish remarkably.", "/ɪf wiː ˈpræktɪst kəˌmjuːnɪˈkeɪtɪv ˈspiːkɪŋ ˈdeɪli wɪð ðeɪ ˈdeɪvɪd ˈaʊə ˈnætʃrəl ˌɪntəˈneɪʃən wʊd ˈflʌrɪʃ rɪˈmɑːkəbli/", "Nếu chúng ta luyện nói giao tiếp hàng ngày với Thầy David, ngữ điệu tự nhiên của chúng ta sẽ tiến bộ vượt bậc.", "Khuyên bạn cùng luyện nói.", "Phát âm chuẩn 'flourish' /ˈflʌrɪʃ/ và 'intonation' /ˌɪntəˈneɪʃən/."),
        ("Mastering the International Phonetic Alphabet empowers learners to pronounce complex loanwords with flawless precision.", "/ˈmɑːstərɪŋ ði ˌɪntəˈnæʃənl fəˈnɛtɪk ˈælfəbɛt ɪmˈpaʊəz ˈlɜːnəz tuː prəˈnaʊns ˈkɒmplɛks ˈləʊnwɜːdz wɪð ˈflɔːlɪs prɪˈsɪʒən/", "Làm chủ Bảng Ký Hiệu Ngữ Âm Quốc Tế tiếp thêm sức mạnh cho người học phát âm các từ mượn phức tạp một cách chuẩn xác không tì vết.", "Nói về tầm quan trọng của IPA.", "Phát âm chuẩn 'flawless precision' /ˈflɔːlɪs prɪˈsɪʒən/."),
        ("If I were in your position, I would listen to English podcasts every morning to enrich my vocabulary lexicon.", "/ɪf aɪ wɜːr ɪn jɔː pəˈzɪʃən aɪ wʊd ˈlɪsn tuː ˈɪŋɡlɪʃ ˈpɒdkɑːsts ˈɛvri ˈmɔːnɪŋ tuː ɪnˈrɪʧ maɪ vəʊˈkæbjʊləri ˈlɛksɪkən/", "Nếu tôi ở vị trí của bạn, tôi sẽ nghe podcast tiếng Anh mỗi sáng để làm giàu vốn từ vựng của mình.", "Đưa ra lời khuyên bằng câu điều kiện loại 2.", "Phát âm chuẩn 'vocabulary lexicon' /vəʊˈkæbjʊləri ˈlɛksɪkən/."),
        ("Every regional English accent, from Australian to Canadian, carries distinctive phonetic melodies and cultural heritage.", "/ˈɛvri ˈriːʤənl ˈɪŋɡlɪʃ ˈæksənt frɒm ɒˈstreɪliən tuː kəˈneɪdiən ˈkæriz dɪsˈtɪŋktɪv fəˈnɛtɪk ˈmɛlədiz ænd ˈkʌlʧərəl ˈhɛrɪtɪʤ/", "Mỗi chất giọng tiếng Anh vùng miền, từ Úc đến Canada, đều mang những giai điệu ngữ âm và di sản văn hóa đặc trưng.", "Tôn vinh các chất giọng tiếng Anh.", "Phát âm chuẩn 'distinctive phonetic melodies'."),
        ("If people around the globe embraced cross-cultural empathy, linguistic diversity would be treasured as humanity's greatest asset.", "/ɪf ˈpiːpl əˈraʊnd ðə ɡləʊb ɪmˈbreɪst krɒs-ˈkʌlʧərəl ˈɛmpəθi lɪŋˈɡwɪstɪk daɪˈvɜːsɪti wʊd biː ˈtrɛʒəd æz hjuːˈmænɪtiz ˈɡreɪtɪst ˈæsɛt/", "Nếu mọi người trên toàn cầu đón nhận sự thấu cảm đa văn hóa, sự đa dạng ngôn ngữ sẽ được trân quý như tài sản lớn nhất của nhân loại.", "Bàn về giá trị đa dạng ngôn ngữ.", "Phát âm chuẩn 'linguistic diversity' và 'humanity's greatest asset'."),
        ("Singaporean Singlish ingeniously blends English grammatical structures with Malay, Hokkien, and Mandarin expressions.", "/ˌsɪŋəˈpɔːrɪən ˈsɪŋɡlɪʃ ɪnˈʤiːniəsli blɛndz ˈɪŋɡlɪʃ ɡrəˈmætɪkəl ˈstrʌkʧəz wɪð məˈleɪ ˈhɒkiɛn ænd ˈmændərɪn ɪksˈprɛʃənz/", "Tiếng Singlish của Singapore kết hợp một cách tài tình cấu trúc ngữ pháp tiếng Anh với các cách diễn đạt tiếng Mã Lai, Phúc Kiến và Quan Thoại.", "Giới thiệu hiện tượng Singlish.", "Phát âm chuẩn 'ingeniously blends' /ɪnˈʤiːniəsli blɛndz/."),
        ("If she spoke three international languages fluently, she could work as a diplomatic interpreter for the United Nations.", "/ɪf ʃiː spəʊk θriː ˌɪntəˈnæʃənl ˈlæŋɡwɪʤɪz ˈfluːəntli ʃiː kʊd wɜːk æz ə ˌdɪpləˈmætɪk ɪnˈtɜːprɪtə fɔː ðə juːˈnaɪtɪd ˈneɪʃənz/", "Nếu cô ấy nói trôi chảy ba thứ tiếng quốc tế, cô ấy có thể làm việc với tư cách là một thông dịch viên ngoại giao cho Liên Hợp Quốc.", "Nói về nghề thông dịch viên ngoại giao.", "Phát âm chuẩn 'diplomatic interpreter' /ˌdɪpləˈmætɪk ɪnˈtɜːprɪtə/."),
        ("Effective cross-cultural communication prioritizes mutual understanding and respectful listening over rigid perfection.", "/ɪˈfɛktɪv krɒs-ˈkʌlʧərəl kəˌmjuːnɪˈkeɪʃən praɪˈɒrɪˌtaɪzɪz ˈmjuːʧʊəl ˌʌndəˈstændɪŋ ænd rɪsˈpɛktfʊl ˈlɪsnɪŋ ˈəʊvə ˈrɪʤɪd pəˈfɛkʃən/", "Giao tiếp đa văn hóa hiệu quả ưu tiên sự hiểu biết lẫn nhau và sự lắng nghe tôn trọng hơn là sự hoàn hảo cứng nhắc.", "Nhấn mạnh bản chất giao tiếp.", "Phát âm chuẩn 'mutual understanding' và 'rigid perfection'."),
        ("Learning idiomatic expressions and colloquial metaphors adds vibrant color and wit to your daily speech.", "/ˈlɜːnɪŋ ˌɪdɪəˈmætɪk ɪksˈprɛʃənz ænd kəˈləʊkwiəl ˈmɛtəfəz ædz ˈvaɪbrənt ˈkʌlər ænd wɪt tuː jɔː ˈdeɪli spiːʧ/", "Học các thành ngữ và ẩn dụ thông tục sẽ thêm vào màu sắc sinh động và sự dí dỏm cho lời nói hàng ngày của bạn.", "Khuyên học thành ngữ.", "Phát âm chuẩn 'colloquial metaphors' /kəˈləʊkwiəl ˈmɛtəfəz/."),
        ("If I had the chance to travel around the world, I would document unique local dialects across every continent.", "/ɪf aɪ hæd ðə ʧɑːns tuː ˈtrævl əˈraʊnd ðə wɜːld aɪ wʊd ˈdɒkjʊmɛnt juːˈniːk ˈləʊkəl ˈdaɪəlɛkts əˈkrɒs ˈɛvri ˈkɒntɪnənt/", "Nếu tôi có cơ hội đi du lịch khắp thế giới, tôi sẽ ghi chép lại những thổ ngữ địa phương độc đáo trên mọi châu lục.", "Ước mơ nghiên cứu thổ ngữ.", "Phát âm chuẩn 'document local dialects' /ˈdɒkjʊmɛnt ˈləʊkəl ˈdaɪəlɛkts/."),
        ("Bilingual individuals often demonstrate superior problem-solving skills, memory retention, and mental adaptability.", "/baɪˈlɪŋɡwəl ˌɪndɪˈvɪdjʊəlz ˈɒfn ˈdɛmənstreɪt suːˈpɪərɪə ˈprɒbləm-ˈsɒlvɪŋ skɪlz ˈmɛməri rɪˈtɛnʃən ænd ˈmɛntl əˌdæptəˈbɪlɪti/", "Những người song ngữ thường thể hiện kỹ năng giải quyết vấn đề, khả năng ghi nhớ và khả năng thích ứng tinh thần vượt trội.", "Nói về lợi ích của song ngữ.", "Phát âm chuẩn 'memory retention' và 'adaptability' /əˌdæptəˈbɪlɪti/."),
        ("If you conquered your fear of making pronunciation mistakes, your conversational confidence would soar instantly.", "/ɪf juː ˈkɒŋkəd jɔː fɪər ɒv ˈmeɪkɪŋ prəˌnʌnsɪˈeɪʃən mɪsˈteɪks jɔː ˌkɒnvəˈseɪʃənl ˈkɒnfɪdəns wʊd sɔːr ˈɪnstəntli/", "Nếu bạn chiến thắng nỗi sợ mắc lỗi phát âm, sự tự tin trong giao tiếp của bạn sẽ vụt sáng ngay lập tức.", "Động viên vượt qua nỗi sợ nói tiếng Anh.", "Phát âm chuẩn 'confidence would soar' /sɔː/."),
        ("Preserving our native Vietnamese mother tongue while acquiring global English creates a balanced cultural identity.", "/prɪˈzɜːvɪŋ ˈaʊə ˈneɪtɪv ˌvjɛtnəˈmiːz ˈmʌðə tʌŋ waɪl əˈkwaɪərɪŋ ˈɡləʊbəl ˈɪŋɡlɪʃ kriˈeɪts ə ˈbælənst ˈkʌlʧərəl aɪˈdɛntɪti/", "Gìn giữ tiếng mẹ đẻ Việt Nam trong khi tiếp thu tiếng Anh toàn cầu tạo nên một bản sắc văn hóa cân bằng.", "Thông điệp về gìn giữ tiếng mẹ đẻ.", "Phát âm chuẩn 'mother tongue' và 'balanced identity'."),
        ("The dynamic evolution of internet slang continuously introduces playful vocabulary into contemporary youth speech.", "/ðə daɪˈnæmɪk ˌiːvəˈluːʃən ɒv ˈɪntəˌnɛt slæŋ kənˈtɪnjuːəsli ˌɪntrəˈdjuːsɪz ˈpleɪfʊl vəʊˈkæbjʊləri ˈɪntuː kənˈtɛmpərəri juːθ spiːʧ/", "Sự tiến hóa năng động của tiếng lóng internet liên tục giới thiệu từ vựng vui nhộn vào ngôn ngữ giới trẻ đương đại.", "Nói về tiếng lóng trên mạng.", "Phát âm chuẩn 'dynamic evolution' và 'playful vocabulary'."),
        ("True language fluency is not about imitating foreign accents, but expressing your authentic thoughts with clarity and heart.", "/truː ˈlæŋɡwɪʤ ˈfluːənsi ɪz nɒt əˈbaʊt ˈɪmɪteɪtɪŋ ˈfɒrɪn ˈæksənts bʌt ɪksˈprɛsɪŋ jɔːr ɔːˈθɛntɪk θɔːts wɪð ˈklærɪti ænd hɑːt/", "Sự lưu loát ngôn ngữ thực sự không phải là bắt chước giọng nước ngoài, mà là bày tỏ những suy nghĩ chân thực với sự sáng rõ và trái tim.", "Triết lý về học ngôn ngữ.", "Phát âm chuẩn 'authenticity' và 'clarity and heart'."),
        ("May your linguistic journey empower you to build bridges of peace, understanding, and friendship across our world.", "/meɪ jɔː lɪŋˈɡwɪstɪk ˈʤɜːni ɪmˈpaʊə juː tuː bɪld ˈbrɪʤɪz ɒv piːs ˌʌndəˈstændɪŋ ænd ˈfrɛndʃɪps əˈkrɒs ˈaʊə wɜːld/", "Chúc cho hành trình ngôn ngữ của bạn tiếp thêm sức mạnh để bạn xây nên những nhịp cầu hòa bình, thấu hiểu và tình bạn khắp thế giới.", "Lời chúc hành trình học tiếng Anh.", "Phát âm chuẩn 'linguistic journey' và 'build bridges of peace'."),
        ("Let us celebrate every unique variety of World Englishes as a radiant testament to human diversity and unity.", "/lɛt ʌs ˈsɛlɪbreɪt ˈɛvri juːˈniːk vəˈraɪəti ɒv wɜːld ˈɪŋɡlɪʃɪz æz ə ˈreɪdiənt ˈtɛstəmənt tuː ˈhjuːmən daɪˈvɜːsɪti ænd ˈjuːnɪti/", "Chúng ta hãy cùng tôn vinh mỗi biến thể độc đáo của Tiếng Anh Toàn Cầu như một minh chứng rực rỡ cho sự đa dạng và đoàn kết của nhân loại.", "Thông điệp đoàn kết toàn cầu.", "Phát âm chuẩn 'radiant testament' /ˈreɪdiənt ˈtɛstəmənt/ và 'diversity and unity'.")
    ])
]

u9_reading_info = {
    "title": "Hiện Tượng Tiếng Anh Toàn Cầu & Sự Tiến Hóa Của Giao Tiếp Quốc Tế",
    "topic": "Khám phá hiện tượng World Englishes, sự chuyển dịch từ tiếng Anh bản ngữ sang ngôn ngữ chung toàn cầu và giao tiếp đa văn hóa",
    "passageText": "The linguistic landscape of the contemporary era has witnessed an unprecedented phenomenon: the rise of English not merely as the native tongue of traditional Anglo-Saxon nations, but as a dynamic global lingua franca known as World Englishes. Today, the demographic ratio of non-native English speakers to native speakers stands at an astonishing three to one. Consequently, English is no longer owned exclusively by any single geographic nation or cultural elite; it belongs to the global community that actively uses it for cross-border commerce, scientific innovation, international diplomacy, and digital connectivity.\n\nAs English took root across disparate continents, distinctive localized varieties flourished, such as Indian English, Nigerian English, Australian English, and Singaporean Singlish. Far from being substandard deviations, sociolinguists recognize these varieties as legitimate, culturally nuanced linguistic systems. Each variety integrates indigenous syntax, idiomatic loanwords, and distinctive phonetic rhythms, reflecting the lived experiences and identity of its speakers.\n\nIn this globalized paradigm, the benchmark of linguistic excellence has fundamentally evolved. International communication experts emphasize that achieving mutual intelligibility, pragmatic clarity, and cross-cultural empathy is far more vital than rigidly mimicking native British or American accents. When learners approach English with communicative confidence rather than pronunciation anxiety, language fulfills its highest philosophical purpose: acting as an empathetic bridge that unites diverse human souls across continents.",
    "keyVocabularyHighlights": [
        {"word": "unprecedented phenomenon", "meaning": "hiện tượng chưa từng có tiền lệ trong lịch sử"},
        {"word": "demographic ratio", "meaning": "tỷ lệ nhân khẩu học giữa các nhóm dân số"},
        {"word": "mutual intelligibility", "meaning": "khả năng thông hiểu lẫn nhau giữa các bên giao tiếp"},
        {"word": "pragmatic clarity", "meaning": "sự rõ ràng và hiệu quả thực tế trong giao tiếp"}
    ]
}

u9_reading_qs = [
    {"id": "u9-r1", "question": "What is the demographic ratio of non-native to native English speakers today according to paragraph 1?", "options": ["A. An astonishing three to one", "B. One to ten", "C. Equal one to one", "D. Zero non-native speakers"], "correctAnswerIndex": 0, "explanation": "Trong đoạn 1: 'the demographic ratio of non-native English speakers to native speakers stands at an astonishing three to one.'"},
    {"id": "u9-r2", "question": "Who does the English language belong to today according to paragraph 1?", "options": ["A. To the global community that actively uses it for commerce, science, and diplomacy", "B. Only to the royal family of Britain", "C. To Hollywood movie directors only", "D. To no one"], "correctAnswerIndex": 0, "explanation": "Trong đoạn 1: 'it belongs to the global community that actively uses it for cross-border commerce, scientific innovation, international diplomacy, and digital connectivity.'"},
    {"id": "u9-r3", "question": "How do sociolinguists view regional varieties of English like Singlish or Indian English?", "options": ["A. As legitimate, culturally nuanced linguistic systems", "B. As terrible mistakes that must be banned", "C. As illegal codes", "D. As foreign languages unrelated to English"], "correctAnswerIndex": 0, "explanation": "Trong đoạn 2: 'sociolinguists recognize these varieties as legitimate, culturally nuanced linguistic systems.'"},
    {"id": "u9-r4", "question": "What do regional English varieties integrate from local cultures?", "options": ["A. Indigenous syntax, idiomatic loanwords, and distinctive phonetic rhythms", "B. Only mathematical formulas", "C. Nothing at all", "D. Modern computer algorithms"], "correctAnswerIndex": 0, "explanation": "Trong đoạn 2: 'integrates indigenous syntax, idiomatic loanwords, and distinctive phonetic rhythms.'"},
    {"id": "u9-r5", "question": "How has the benchmark of linguistic excellence evolved in paragraph 3?", "options": ["A. Emphasizing mutual intelligibility, pragmatic clarity, and cross-cultural empathy", "B. Demanding everyone copy a 16th-century London accent", "C. Forbidding all non-native speakers from talking", "D. Testing only silent grammar memory"], "correctAnswerIndex": 0, "explanation": "Trong đoạn 3: 'achieving mutual intelligibility, pragmatic clarity, and cross-cultural empathy is far more vital than rigidly mimicking native... accents.'"},
    {"id": "u9-r6", "question": "What is the highest philosophical purpose of language described at the end?", "options": ["A. Acting as an empathetic bridge that unites diverse human souls across continents", "B. Dividing nations into hostile groups", "C. Earning high test scores only", "D. Replacing all national flags"], "correctAnswerIndex": 0, "explanation": "Trong đoạn 3: 'acting as an empathetic bridge that unites diverse human souls across continents.'"},
    {"id": "u9-r7", "question": "Which word in paragraph 2 is closest in meaning to 'deviations'?", "options": ["A. Departures, variations, or divergences from a standard norm", "B. Perfect copies", "C. Solid rocks", "D. Fast vehicles"], "correctAnswerIndex": 0, "explanation": "'Deviations' có nghĩa là những sự chệch hướng, những biến thể khác với chuẩn mực thông thường."},
    {"id": "u9-r8", "question": "Which word in paragraph 3 is closest in meaning to 'benchmark'?", "options": ["A. Standard, criterion, or measure of excellence", "B. Wooden bench in a park", "C. Bank money", "D. Type of pencil"], "correctAnswerIndex": 0, "explanation": "'Benchmark' có nghĩa là tiêu chuẩn, chuẩn mực đánh giá."},
    {"id": "u9-r9", "question": "What is the tone of the author regarding World Englishes?", "options": ["A. Progressive, inclusive, and culturally appreciative", "B. Scornful and discriminatory", "C. Angry and defensive", "D. Bored and dismissive"], "correctAnswerIndex": 0, "explanation": "Tác giả thể hiện thái độ tiến bộ, bao dung, hòa nhập và trân trọng sự đa dạng văn hóa."},
    {"id": "u9-r10", "question": "What is the most suitable title for this comprehensive reading passage?", "options": ["A. World Englishes: The Evolution of Global Communication and Linguistic Diversity", "B. A Guide to American Pronunciation Only", "C. How to Build Commercial Bridges Across Rivers", "D. History of Medieval Latin Manuscripts"], "correctAnswerIndex": 0, "explanation": "Tiêu đề chuẩn xác nhất tóm lược hiện tượng Tiếng Anh Toàn Cầu, sự tiến hóa của giao tiếp và tính đa dạng ngôn ngữ."}
]

u9_writing_prompts = [
    {
        "id": "u9-w1",
        "title": "Đề 1: Write a paragraph on the benefits of learning English as a global language (60-80 words)",
        "description": "Viết một đoạn văn trình bày những lợi ích thiết thực của việc học tiếng Anh như một ngôn ngữ toàn cầu.",
        "suggestedOutline": [
            "Introduction: State that English is an indispensable global language for contemporary students.",
            "Body: Give benefits (accessing global knowledge/internet, winning international scholarships, connecting with global friends).",
            "Conclusion: Affirm that English proficiency empowers youth to become global citizens."
        ],
        "usefulPhrases": [
            "Mastering English as a global lingua franca unlocks boundless opportunities for contemporary students...",
            "First, it grants direct access to vast international scientific research, digital libraries, and academic literature...",
            "Second, high English proficiency paves the way for prestigious overseas scholarships and global career trajectories...",
            "Ultimately, English serves as an empowering bridge connecting young Vietnamese to the world."
        ],
        "wordLimit": "60 - 80 từ",
        "sampleGrade10Response": "Mastering English as a global lingua franca unlocks boundless opportunities for contemporary students. First, it grants direct access to vast international scientific research, digital educational platforms, and global literature. Second, high English proficiency paves the way for winning prestigious overseas scholarships and securing dynamic multinational careers. Most importantly, English allows us to proudly share Vietnamese culture and forge lifelong friendships across continents, transforming us into confident global citizens."
    },
    {
        "id": "u9-w2",
        "title": "Đề 2: Write a paragraph on what you would do if you could speak English fluently (60-80 words)",
        "description": "Viết một đoạn văn sử dụng câu điều kiện loại 2 kể về những điều em sẽ làm nếu em nói tiếng Anh trôi chảy như người bản xứ.",
        "suggestedOutline": [
            "Introduction: Introduce your hypothesis (If I spoke English fluently...).",
            "Body: Detail actions (travel around the world, volunteer as an international guide in Hoi An, study at a renowned university).",
            "Conclusion: Express your determination to practice hard to achieve this goal."
        ],
        "usefulPhrases": [
            "If I spoke English fluently with natural confidence, my life would be filled with exciting adventures...",
            "First, I would volunteer as a bilingual tour guide in Hanoi to introduce our rich historical heritage to foreign travelers...",
            "Furthermore, I could apply for an international journalism scholarship in the United Kingdom...",
            "I am determined to practice speaking daily with Thầy David to turn this dream into reality."
        ],
        "wordLimit": "60 - 80 từ",
        "sampleGrade10Response": "If I spoke English fluently with natural confidence, my life would be filled with exciting adventures. First, I would volunteer as a bilingual cultural guide in Hanoi to share Vietnam's thousand-year heritage with international travelers. Furthermore, I could confidently apply for an environmental science scholarship at an overseas university in Canada. Conquering English would empower me to advocate for global environmental protection. I will practice diligently every day to achieve this goal."
    },
    {
        "id": "u9-w3",
        "title": "Đề 3: Write a paragraph on why mutual understanding is more important than native accents (60-80 words)",
        "description": "Viết một đoạn văn giải thích tại sao sự thông hiểu lẫn nhau trong giao tiếp quan trọng hơn việc bắt chước giọng bản ngữ chuẩn.",
        "suggestedOutline": [
            "Introduction: State that effective communication values mutual intelligibility over native-like accents.",
            "Body: Explain reasons (World Englishes has many varieties, clear pronunciation and empathy matter most, excessive accent anxiety hinders confidence).",
            "Conclusion: Encourage learners to speak with clarity and confidence."
        ],
        "usefulPhrases": [
            "In modern World Englishes, achieving mutual intelligibility is far more significant than mimicking native accents...",
            "Since non-native speakers vastly outnumber native speakers globally, clarity, logical coherence, and empathy matter most...",
            "Obsessing over sounding like a native British or American speaker often breeds unnecessary anxiety and stifles self-expression...",
            "Speaking clearly with natural intonation empowers us to communicate effectively across cultures."
        ],
        "wordLimit": "60 - 80 từ",
        "sampleGrade10Response": "In modern global communication, achieving mutual intelligibility is far more significant than rigidly mimicking native accents. Since non-native English speakers vastly outnumber native speakers worldwide, clarity, logical coherence, and empathetic listening matter most. Obsessing over sounding like a native speaker often creates unnecessary hesitation and undermines speaking confidence. As long as we pronounce words clearly with natural intonation, our authentic Vietnamese bilingual voice can bridge cultures beautifully."
    },
    {
        "id": "u9-w4",
        "title": "Đề 4: Write a paragraph giving advice to a friend who is afraid of making speaking mistakes (60-80 words)",
        "description": "Viết một đoạn văn đưa ra lời khuyên chân thành (dùng If I were you) cho một người bạn đang sợ nói tiếng Anh vì sợ sai.",
        "suggestedOutline": [
            "Introduction: Empathize with your friend's anxiety about making speaking mistakes.",
            "Body: Give advice (If I were you, I would remember that mistakes are natural stepping stones, practice speaking daily in front of a mirror or with friends).",
            "Conclusion: Encourage your friend to be bold and confident."
        ],
        "usefulPhrases": [
            "If I were you, I would never let the fear of making grammatical or pronunciation mistakes hold me back...",
            "Mistakes are completely natural stepping stones that every successful language learner must experience...",
            "I would advise you to practice speaking short daily sentences with peers or shadowing audio guides regularly...",
            "With consistent courage and daily practice, your speaking fluency will flourish remarkably."
        ],
        "wordLimit": "60 - 80 từ",
        "sampleGrade10Response": "If I were you, I would never let the fear of making pronunciation or grammar mistakes hold me back. Making errors is a completely natural and essential stepping stone in language learning. I would advise you to practice speaking English aloud every day by shadowing audio recordings or joining bilingual club discussions. Remember that confidence and clear message delivery are what truly matter. Believe in yourself and speak boldly without hesitation!"
    },
    {
        "id": "u9-w5",
        "title": "Đề 5: Write a paragraph on the importance of preserving the mother tongue while learning English (60-80 words)",
        "description": "Viết một đoạn văn khẳng định tầm quan trọng của việc gìn giữ tiếng mẹ đẻ (tiếng Việt) trong khi tiếp thu tiếng Anh toàn cầu.",
        "suggestedOutline": [
            "Introduction: State that bilingualism requires cherishing our mother tongue alongside learning English.",
            "Body: Explain why (mother tongue carries our national soul and cultural heritage; English provides a global communication tool).",
            "Conclusion: Emphasize maintaining a harmonious balance between national identity and global integration."
        ],
        "usefulPhrases": [
            "While acquiring English proficiency is vital for global integration, cherishing our native Vietnamese mother tongue is sacred...",
            "Our mother tongue carries thousands of years of ancestral wisdom, literature, and cultural soul...",
            "Mastering English provides a powerful global tool, but our mother tongue anchors who we truly are...",
            "Embracing both languages harmoniously nurtures enlightened, culturally rooted global citizens."
        ],
        "wordLimit": "60 - 80 từ",
        "sampleGrade10Response": "While acquiring English proficiency is vital for global integration, cherishing our native Vietnamese mother tongue is sacred. Our mother tongue carries thousands of years of rich ancestral wisdom, heartfelt poetry, and national identity. While English equips us with a powerful tool to engage with international science and commerce, Vietnamese anchors our cultural soul. Embracing both languages harmoniously allows Vietnamese youth to step confidently into the world without ever losing their roots."
    }
]

unit9 = make_unit(9, "Unit 9: World Englishes", "Tiếng Anh toàn cầu & Đa dạng ngôn ngữ", "Khám phá hiện tượng World Englishes, các biến thể tiếng Anh trên thế giới, Câu điều kiện loại 2 (Conditional Type 2: Unreal Condition).", "Ngữ âm: Trọng âm câu, ngữ điệu biểu cảm và cách phát âm các từ mượn quốc tế", "Globe", u9_vocab, u9_grammar_info, u9_grammar_exs, u9_listening_info, u9_listening_qs, u9_listening_fibs, u9_speaking, u9_reading_info, u9_reading_qs, u9_writing_prompts)
write_ts_unit(9, unit9)
print("Unit 9 generated successfully!")

# ==============================================================================
# UNIT 10: PLANET EARTH (20 Vocab, 20 Grammar, 8 Listening MC + 4 FIB, 20 Speaking, 10 Reading, 5 Writing)
# ==============================================================================
u10_vocab = [
    {"id": "u10-v1", "word": "greenhouse effect", "phonetic": "/ˈɡriːnhaʊs ɪˈfɛkt/", "partOfSpeech": "noun", "vietnameseMeaning": "hiệu ứng nhà kính", "englishExample": "Excessive atmospheric greenhouse gases trap thermal heat, intensifying the greenhouse effect.", "vietnameseExample": "Khí nhà kính tích tụ quá mức trong khí quyển giữ nhiệt lại, làm gia tăng hiệu ứng nhà kính."},
    {"id": "u10-v2", "word": "global warming", "phonetic": "/ˈɡləʊbəl ˈwɔːmɪŋ/", "partOfSpeech": "noun", "vietnameseMeaning": "hiện tượng nóng lên toàn cầu", "englishExample": "Global warming causes catastrophic polar ice caps melting and extreme weather abnormalities.", "vietnameseExample": "Sự nóng lên toàn cầu gây ra hiện tượng băng hai cực tan chảy thảm khốc và các dị thường thời tiết cực đoan."},
    {"id": "u10-v3", "word": "renewable energy", "phonetic": "/rɪˈnjuːəbl ˈɛnəʤi/", "partOfSpeech": "noun", "vietnameseMeaning": "năng lượng tái tạo (mặt trời, gió, thủy triều)", "englishExample": "Transitioning rapidly to renewable energy sources is paramount to achieving net-zero emissions.", "vietnameseExample": "Chuyển dịch nhanh chóng sang các nguồn năng lượng tái tạo là điều tối quan trọng để đạt mức phát thải ròng bằng không."},
    {"id": "u10-v4", "word": "deforestation", "phonetic": "/diːˌfɒrɪˈsteɪʃən/", "partOfSpeech": "noun", "vietnameseMeaning": "nạn phá rừng, chặt phá rừng bừa bãi", "englishExample": "Rampant deforestation strips wild species of natural habitats and accelerates soil erosion.", "vietnameseExample": "Nạn phá rừng tràn lan tước đoạt sinh cảnh tự nhiên của các loài hoang dã và đẩy nhanh xói mòn đất."},
    {"id": "u10-v5", "word": "carbon emission", "phonetic": "/ˈkɑːbən ɪˈmɪʃən/", "partOfSpeech": "noun", "vietnameseMeaning": "lượng khí thải carbon", "englishExample": "Industrial factories must install modern filtration technologies to curtail carbon emissions.", "vietnameseExample": "Các nhà máy công nghiệp phải lắp đặt công nghệ lọc hiện đại để cắt giảm lượng khí thải carbon."},
    {"id": "u10-v6", "word": "fossil fuels", "phonetic": "/ˈfɒsl fjʊəlz/", "partOfSpeech": "noun", "vietnameseMeaning": "nhiên liệu hóa thạch (than đá, dầu mỏ, khí đốt)", "englishExample": "Burning fossil fuels releases massive volumes of toxic carbon dioxide into the atmosphere.", "vietnameseExample": "Đốt nhiên liệu hóa thạch thải ra lượng lớn khí carbon dioxide độc hại vào bầu khí quyển."},
    {"id": "u10-v7", "word": "biodegradable", "phonetic": "/ˌbaɪəʊdɪˈɡreɪdəbl/", "partOfSpeech": "adjective", "vietnameseMeaning": "có khả năng tự phân hủy sinh học", "englishExample": "Using biodegradable food packaging prevents toxic microplastic contamination in oceans.", "vietnameseExample": "Sử dụng bao bì thực phẩm tự phân hủy sinh học ngăn chặn ô nhiễm vi nhựa độc hại trong đại dương."},
    {"id": "u10-v8", "word": "afforestation", "phonetic": "/əˌfɒrɪˈsteɪʃən/", "partOfSpeech": "noun", "vietnameseMeaning": "sự trồng rừng gây rừng mới", "englishExample": "National afforestation campaigns aim to cover barren mountain slopes with lush trees.", "vietnameseExample": "Các chiến dịch trồng rừng quốc gia nhằm phủ xanh các sườn núi trọc bằng những hàng cây tươi tốt."},
    {"id": "u10-v9", "word": "sea level rise", "phonetic": "/siː ˈlɛvl raɪz/", "partOfSpeech": "noun", "vietnameseMeaning": "mực nước biển dâng cao", "englishExample": "Sea level rise threatens low-lying delta agriculture and coastal freshwater aquifers.", "vietnameseExample": "Mực nước biển dâng cao đe dọa nông nghiệp vùng đồng bằng trũng thấp và các tầng nước ngọt ven biển."},
    {"id": "u10-v10", "word": "ecological footprint", "phonetic": "/ˌiːkəˈlɒʤɪkəl ˈfʊtprɪnt/", "partOfSpeech": "noun", "vietnameseMeaning": "dấu chân sinh thái (mức tiêu thụ tài nguyên)", "englishExample": "Adopting minimalist green habits substantially minimizes our individual ecological footprint.", "vietnameseExample": "Thực hành lối sống xanh tối giản giúp giảm thiểu đáng kể dấu chân sinh thái của mỗi cá nhân chúng ta."},
    {"id": "u10-v11", "word": "ozone layer", "phonetic": "/ˈəʊzəʊn ˈleɪə/", "partOfSpeech": "noun", "vietnameseMeaning": "tầng ô-dôn bảo vệ Trái Đất", "englishExample": "The upper ozone layer shields all terrestrial life against lethal ultraviolet radiation.", "vietnameseExample": "Tầng ô-dôn trên cao che chắn mọi sự sống trên cạn khỏi bức xạ tia cực tím gây chết người."},
    {"id": "u10-v12", "word": "extreme weather", "phonetic": "/ɪksˈtriːm ˈwɛðə/", "partOfSpeech": "noun", "vietnameseMeaning": "thời tiết cực đoan (bão dữ, hạn hán, lũ lụt)", "englishExample": "Climate volatility is triggering frequent extreme weather phenomena globally.", "vietnameseExample": "Sự biến động khí hậu đang gây ra các hiện tượng thời tiết cực đoan thường xuyên trên toàn cầu."},
    {"id": "u10-v13", "word": "habitat destruction", "phonetic": "/ˈhæbɪtæt dɪsˈtrʌkʃən/", "partOfSpeech": "noun", "vietnameseMeaning": "sự tàn phá sinh cảnh sống tự nhiên", "englishExample": "Habitat destruction remains the foremost driving force behind the sixth mass wildlife extinction.", "vietnameseExample": "Sự tàn phá sinh cảnh vẫn là động lực hàng đầu dẫn đến cuộc đại tuyệt chủng động vật hoang dã lần thứ sáu."},
    {"id": "u10-v14", "word": "solar panel", "phonetic": "/ˈsəʊlə ˈpænl/", "partOfSpeech": "noun", "vietnameseMeaning": "tấm pin năng lượng mặt trời", "englishExample": "Installing rooftop solar panels converts clean sunlight into usable green electricity.", "vietnameseExample": "Lắp đặt các tấm pin mặt trời trên mái nhà chuyển hóa ánh nắng sạch thành điện xanh hữu ích."},
    {"id": "u10-v15", "word": "wind turbine", "phonetic": "/wɪnd ˈtɜːbaɪn/", "partOfSpeech": "noun", "vietnameseMeaning": "tua-bin gió phát điện", "englishExample": "Offshore wind turbines generate colossal megawatts of carbon-free renewable power.", "vietnameseExample": "Các tua-bin gió ngoài khơi tạo ra hàng ngàn megawatt điện năng tái tạo không phát thải carbon."},
    {"id": "u10-v16", "word": "endangered species", "phonetic": "/ɪnˈdeɪnʤəd ˈspiːʃiːz/", "partOfSpeech": "noun", "vietnameseMeaning": "các loài có nguy cơ tuyệt chủng", "englishExample": "The saola is one of the most critically endangered species surviving in Vietnam's Annamite Range.", "vietnameseExample": "Sao la là một trong những loài có nguy cơ tuyệt chủng nguy cấp nhất còn sót lại ở Dãy Trường Sơn Việt Nam."},
    {"id": "u10-v17", "word": "conservationist", "phonetic": "/ˌkɒnsəˈveɪʃənɪst/", "partOfSpeech": "noun", "vietnameseMeaning": "nhà hoạt động bảo tồn môi trường & sinh thái", "englishExample": "Dedicated conservationists work tirelessly to rescue sea turtles and rehabilitate damaged mangroves.", "vietnameseExample": "Những nhà bảo tồn tận tụy làm việc không mệt mỏi để cứu rùa biển và phục hồi rừng ngập mặn bị tàn phá."},
    {"id": "u10-v18", "word": "sustainable lifestyle", "phonetic": "/səˈsteɪnəbl ˈlaɪfstaɪl/", "partOfSpeech": "noun", "vietnameseMeaning": "lối sống bền vững thân thiện môi trường", "englishExample": "Leading a sustainable lifestyle entails conserving tap water, sorting recyclables, and biking.", "vietnameseExample": "Sống một lối sống bền vững bao gồm việc tiết kiệm nước sinh hoạt, phân loại rác tái chế và đi xe đạp."},
    {"id": "u10-v19", "word": "carbon neutral", "phonetic": "/ˈkɑːbən ˈnjuːtrəl/", "partOfSpeech": "adjective", "vietnameseMeaning": "trung hòa carbon (cân bằng lượng phát thải)", "englishExample": "Vietnam has committed to achieving carbon neutral status by the milestone year of 2050.", "vietnameseExample": "Việt Nam đã cam kết đạt trạng thái trung hòa carbon vào năm cột mốc 2050."},
    {"id": "u10-v20", "word": "ecosystem restoration", "phonetic": "/ˈiːkəʊˌsɪstəm ˌrɛstəˈreɪʃən/", "partOfSpeech": "noun", "vietnameseMeaning": "sự phục hồi và tái tạo hệ sinh thái", "englishExample": "Global ecosystem restoration initiatives plant billions of native trees to revive degraded biomes.", "vietnameseExample": "Các sáng kiến phục hồi hệ sinh thái toàn cầu trồng hàng tỷ cây bản địa để hồi sinh các quần xã sinh vật bị suy thoái."}
]

u10_grammar_info = {
    "title": "Mệnh Đề Quan Hệ Với Giới Từ & Trạng Từ Quan Hệ (Relative Clauses with Prepositions & Where, When, Why)",
    "summary": "Nắm vững cách đặt giới từ trước đại từ quan hệ (in which, on which, to whom, with whom) trong văn phong trang trọng, và cách thay thế bằng các trạng từ quan hệ Where (= in/at which), When (= at/on which), Why (= for which).",
    "formulaBox": [
        "Giới từ + Whom (chỉ người) / Giới từ + Which (chỉ vật)",
        "Ví dụ: The environmental organization IN WHICH she works promotes solar energy.",
        "Ví dụ: The conservationist WITH WHOM we collaborated received a global award.",
        "Trạng từ quan hệ: WHERE (nơi chốn = in/at which), WHEN (thời gian = in/at/on which), WHY (lý do = for which)",
        "Ví dụ: This is the national park WHERE (= in which) rare primates are protected.",
        "Ví dụ: 2050 is the milestone year WHEN (= in which) Vietnam aims for carbon neutrality."
    ],
    "usagePoints": [
        {"title": "1. Giới từ đứng trước đại từ quan hệ", "detail": "Tuyệt đối không dùng 'That' hoặc 'Who' ngay sau giới từ. Chỉ được dùng 'Whom' (người) hoặc 'Which' (vật).", "example": "The conference AT WHICH (không dùng at that) climate policies were discussed was held in Paris."},
        {"title": "2. Chuyển đổi trạng từ quan hệ", "detail": "Where/When/Why không đi kèm giới từ ở phía sau.", "example": "The forest WHERE endangered tigers live is strictly guarded."}
    ]
}

u10_grammar_exs = [
    {"id": "u10-g1", "question": "The primary rainforest in _____ endangered langurs reside is strictly protected.", "options": ["A. which", "B. that", "C. whom", "D. where"], "correctAnswer": "A. which", "explanation": "Sau giới từ 'in' chỉ vật/địa điểm dùng 'in which' (hoặc where không có giới từ)."},
    {"id": "u10-g2", "question": "The marine biologist with _____ we conducted coral reef research received a prestigious conservation award.", "options": ["A. whom", "B. who", "C. that", "D. which"], "correctAnswer": "A. whom", "explanation": "Sau giới từ 'with' chỉ người bắt buộc phải dùng 'whom'."},
    {"id": "u10-g3", "question": "This is the solar power station _____ generates clean electricity for forty thousand homes.", "options": ["A. which", "B. where", "C. whom", "D. when"], "correctAnswer": "A. which", "explanation": "Làm chủ ngữ cho động từ 'generates' chỉ vật -> dùng 'which' / 'that'."},
    {"id": "u10-g4", "question": "Can Gio Mangrove Biosphere Reserve is the sanctuary _____ thousands of migratory birds feed each winter.", "options": ["A. where", "B. which", "C. whom", "D. when"], "correctAnswer": "A. where", "explanation": "Trạng từ quan hệ chỉ nơi chốn 'where' (= in which) trong đó chim kiếm ăn."},
    {"id": "u10-g5", "question": "2050 is the target year _____ Vietnam pledges to achieve net-zero carbon emissions.", "options": ["A. when", "B. where", "C. which", "D. why"], "correctAnswer": "A. when", "explanation": "Trạng từ quan hệ chỉ thời gian 'when' (= in which)."},
    {"id": "u10-g6", "question": "The environmental crisis about _____ scientists are most deeply alarmed is global climate heating.", "options": ["A. which", "B. that", "C. whom", "D. where"], "correctAnswer": "A. which", "explanation": "Sau giới từ 'about' chỉ vật -> 'about which'."},
    {"id": "u10-g7", "question": "The reason _____ we must immediately stop single-use plastics is to safeguard ocean life.", "options": ["A. why", "B. where", "C. when", "D. which"], "correctAnswer": "A. why", "explanation": "Trạng từ quan hệ chỉ lý do sau 'The reason why...'."},
    {"id": "u10-g8", "question": "The youth eco-club to _____ Minh belongs has planted three thousand mangrove saplings.", "options": ["A. which", "B. whom", "C. that", "D. where"], "correctAnswer": "A. which", "explanation": "Sau giới từ 'to' chỉ tổ chức/vật 'The youth eco-club' -> 'to which'."},
    {"id": "u10-g9", "question": "The rooftop _____ the new solar panels were installed absorbs ample sunshine all day.", "options": ["A. on which", "B. in which", "C. to whom", "D. at that"], "correctAnswer": "A. on which", "explanation": "Lắp đặt trên mái nhà: 'on which the new solar panels were installed'."},
    {"id": "u10-g10", "question": "The forest rangers _____ devoted their lives to guarding wildlife were honored at the ceremony.", "options": ["A. who", "B. which", "C. whom", "D. whose"], "correctAnswer": "A. who", "explanation": "Chỉ người làm chủ ngữ cho 'devoted' -> dùng 'who'."},
    {"id": "u10-g11", "question": "The ecological documentary for _____ our class provided research data was broadcast nationally.", "options": ["A. which", "B. that", "C. whom", "D. where"], "correctAnswer": "A. which", "explanation": "Sau giới từ 'for' chỉ vật 'The ecological documentary' -> 'for which'."},
    {"id": "u10-g12", "question": "The island habitat _____ rare sea turtles lay their eggs is monitored around the clock.", "options": ["A. where", "B. which", "C. whom", "D. when"], "correctAnswer": "A. where", "explanation": "Chỉ nơi chốn 'where rare sea turtles lay their eggs'."},
    {"id": "u10-g13", "question": "Earth Day, _____ is celebrated globally on April 22nd, mobilizes environmental action.", "options": ["A. which", "B. that", "C. where", "D. who"], "correctAnswer": "A. which", "explanation": "Mệnh đề không xác định có dấu phẩy chỉ sự kiện -> dùng 'which'."},
    {"id": "u10-g14", "question": "The environmental activists with _____ we marched through the city carried banners against deforestation.", "options": ["A. whom", "B. who", "C. that", "D. which"], "correctAnswer": "A. whom", "explanation": "Sau giới từ 'with' chỉ người -> 'with whom'."},
    {"id": "u10-g15", "question": "The clean wind farm _____ turbines spin off the coast of Ninh Thuan produces abundant green power.", "options": ["A. whose", "B. which", "C. that", "D. where"], "correctAnswer": "A. whose", "explanation": "Sở hữu 'whose turbines' (những tua-bin của trang trại gió)."},
    {"id": "u10-g16", "question": "The global climate summit at _____ historic emissions treaties were signed took place in Glasgow.", "options": ["A. which", "B. where", "C. that", "D. whom"], "correctAnswer": "A. which", "explanation": "Sau giới từ 'at' chỉ sự kiện 'The global climate summit' -> 'at which'."},
    {"id": "u10-g17", "question": "That was the exact moment _____ the young volunteers finished cleaning up the coastal beach.", "options": ["A. when", "B. where", "C. why", "D. which"], "correctAnswer": "A. when", "explanation": "Sau danh từ chỉ thời điểm 'the exact moment when...'."},
    {"id": "u10-g18", "question": "The innovative filtering device _____ removes microplastics from wastewater was invented by high school students.", "options": ["A. that", "B. who", "C. whom", "D. where"], "correctAnswer": "A. that", "explanation": "Thay thế cho 'The innovative filtering device' (vật) -> 'that' / 'which'."},
    {"id": "u10-g19", "question": "Professor Phong, _____ research focuses on delta soil salinity, will deliver a keynote lecture.", "options": ["A. whose", "B. who", "C. whom", "D. which"], "correctAnswer": "A. whose", "explanation": "Sở hữu 'whose research' (nghiên cứu của Giáo sư Phong)."},
    {"id": "u10-g20", "question": "The degraded mountain slopes on _____ millions of pine trees were planted are now flourishing green.", "options": ["A. which", "B. where", "C. that", "D. whom"], "correctAnswer": "A. which", "explanation": "Sau giới từ 'on' chỉ địa điểm 'on which millions of pine trees were planted'."}
]

u10_listening_info = {
    "audioTitle": "Cứu Lấy Trái Đất & Năng Lượng Tái Tạo (Safeguarding Planet Earth)",
    "audioDuration": "3:20",
    "audioScriptSpeaker": "Environmental Scientist Dr. Lam & Student An",
    "transcriptText": "An: Dr. Lam, what is the most critical environmental crisis currently threatening Planet Earth?\nDr. Lam: Hello An! The accelerating pace of global warming driven by greenhouse gas emissions from fossil fuels is our planet's greatest threat. This phenomenon triggers catastrophic polar ice melting, severe sea level rise, and frequent extreme weather catastrophes such as historic droughts and flash floods.\nAn: What sustainable solutions must humanity adopt immediately?\nDr. Lam: We must accelerate our transition to clean renewable energy—such as massive offshore wind farms and rooftop solar panels. Additionally, restoring degraded mangrove forests and practicing reforestation act as natural carbon sponges that absorb tons of carbon dioxide from the air.\nAn: How can teenagers contribute to saving our planet every day?\nDr. Lam: Students can lead by adopting sustainable daily lifestyles: sorting plastic waste for recycling, turning off unused electrical appliances, choosing bicycles for short trips, and planting green trees in school gardens. Every small conscious action creates a giant wave of positive planetary change!",
    "vietnameseTranslation": "An: Tiến sĩ Lâm ơi, cuộc khủng hoảng môi trường nghiêm trọng nhất hiện đang đe dọa Hành tinh Trái Đất là gì ạ?\nTiến sĩ Lâm: Chào An! Tốc độ nóng lên toàn cầu ngày càng gia tăng do phát thải khí nhà kính từ nhiên liệu hóa thạch là mối đe dọa lớn nhất đối với hành tinh chúng ta. Hiện tượng này gây ra tình trạng băng hai cực tan chảy thảm khốc, mực nước biển dâng cao nghiêm trọng và các thảm họa thời tiết cực đoan thường xuyên như hạn hán lịch sử và lũ quét.\nAn: Nhân loại phải thực hiện những giải pháp bền vững nào ngay lập tức ạ?\nTiến sĩ Lâm: Chúng ta phải đẩy nhanh quá trình chuyển dịch sang năng lượng tái tạo sạch—chẳng hạn như các trang trại điện gió ngoài khơi khổng lồ và các tấm pin mặt trời trên mái nhà. Ngoài ra, việc phục hồi rừng ngập mặn bị suy thoái và tích cực trồng rừng đóng vai trò như những miếng bọt biển carbon tự nhiên hấp thụ hàng tấn khí CO2 từ không khí.\nAn: Các bạn học sinh có thể đóng góp như thế nào để cứu hành tinh mỗi ngày ạ?\nTiến sĩ Lâm: Các em có thể đi đầu bằng cách thực hành lối sống bền vững hàng ngày: phân loại rác nhựa để tái chế, tắt các thiết bị điện không dùng, chọn đi xe đạp cho những quãng đường ngắn và trồng cây xanh trong vườn trường. Mỗi hành động nhỏ có ý thức đều tạo nên một làn sóng thay đổi tích cực khổng lồ cho hành tinh!"
}

u10_listening_qs = [
    {"id": "u10-l1", "question": "What is identified as Planet Earth's greatest environmental threat according to Dr. Lam?", "options": ["A. Global warming driven by greenhouse gas emissions from fossil fuels", "B. Building too many libraries", "C. Painting houses white", "D. Flying kites on weekends"], "correctAnswerIndex": 0, "explanation": "Trong bài nghe: 'global warming driven by greenhouse gas emissions from fossil fuels is our planet's greatest threat.'"},
    {"id": "u10-l2", "question": "What catastrophes are triggered by global warming?", "options": ["A. Polar ice melting, severe sea level rise, and extreme weather droughts and floods", "B. Free gold raining from clouds", "C. Falling stars every night", "D. Oceans turning into lemonade"], "correctAnswerIndex": 0, "explanation": "Trong bài nghe: 'triggers catastrophic polar ice melting, severe sea level rise, and frequent extreme weather catastrophes.'"},
    {"id": "u10-l3", "question": "What clean energy sources must humanity accelerate transition to?", "options": ["A. Offshore wind farms and rooftop solar panels", "B. Burning more coal and heavy oil", "C. Cutting down all national forests", "D. Using plastic candles"], "correctAnswerIndex": 0, "explanation": "Trong bài nghe: 'transition to clean renewable energy—such as massive offshore wind farms and rooftop solar panels.'"},
    {"id": "u10-l4", "question": "How do restored mangrove forests and afforestation help the planet?", "options": ["A. They act as natural carbon sponges that absorb tons of carbon dioxide", "B. They produce toxic plastic", "C. They heat up the atmosphere", "D. They dry up rivers"], "correctAnswerIndex": 0, "explanation": "Trong bài nghe: 'act as natural carbon sponges that absorb tons of carbon dioxide from the air.'"},
    {"id": "u10-l5", "question": "What daily habit can students adopt regarding waste?", "options": ["A. Sorting plastic waste for recycling", "B. Throwing all trash into rivers", "C. Burning plastic bags at home", "D. Leaving trash in schoolyards"], "correctAnswerIndex": 0, "explanation": "Trong bài nghe: 'sorting plastic waste for recycling.'"},
    {"id": "u10-l6", "question": "What eco-friendly transportation does Dr. Lam recommend for short trips?", "options": ["A. Choosing bicycles", "B. Driving giant diesel trucks", "C. Flying in private helicopters", "D. Riding high-emission motorbikes"], "correctAnswerIndex": 0, "explanation": "Trong bài nghe: 'choosing bicycles for short trips.'"},
    {"id": "u10-l7", "question": "What action in school gardens helps fight climate change?", "options": ["A. Planting green trees", "B. Pouring cement over soil", "C. Pulling out all grass", "D. Cutting all tree branches"], "correctAnswerIndex": 0, "explanation": "Trong bài nghe: 'and planting green trees in school gardens.'"},
    {"id": "u10-l8", "question": "What is the concluding empowering message of Dr. Lam?", "options": ["A. Every small conscious action creates a giant wave of positive planetary change", "B. One person cannot do anything", "C. Global warming is impossible to stop", "D. Pollution does not matter"], "correctAnswerIndex": 0, "explanation": "Tiến sĩ Lâm khẳng định: 'Every small conscious action creates a giant wave of positive planetary change!'"}
]

u10_listening_fibs = [
    {"id": "u10-f1", "sentenceWithBlank": "Global warming is driven by greenhouse gas _____.", "correctWord": "emissions", "hint": "Lượng khí phát thải (emissions)"},
    {"id": "u10-f2", "sentenceWithBlank": "Humanity must transition to clean _____ energy.", "correctWord": "renewable", "hint": "Tái tạo (renewable)"},
    {"id": "u10-f3", "sentenceWithBlank": "Forests act as natural carbon _____ absorbing CO2.", "correctWord": "sponges", "hint": "Miếng bọt biển (sponges)"},
    {"id": "u10-f4", "sentenceWithBlank": "Every conscious action creates positive _____ change.", "correctWord": "planetary", "hint": "Thuộc về hành tinh (planetary)"}
]

u10_speaking = [
    {"id": f"u10-s{i+1}", "targetSentence": s, "ipa": ipa, "vietnameseMeaning": vm, "contextSituation": ctx, "keyPhonicsFocus": kpf, "sampleAudioText": s}
    for i, (s, ipa, vm, ctx, kpf) in enumerate([
        ("Planet Earth is our sole shared sanctuary, and protecting its delicate biosphere is humanity's highest moral imperative.", "/ˈplænɪt ɜːθ ɪz ˈaʊə səʊl ʃeəd ˈsæŋktjʊəri ænd prəˈtɛktɪŋ ɪts ˈdɛlɪkɪt ˈbaɪəʊsfɪər ɪz hjuːˈmænɪtiz ˈhaɪɪst ˈmɒrəl ɪmˈpɛrətɪv/", "Hành tinh Trái Đất là thánh địa chung duy nhất của chúng ta, và bảo vệ sinh quyển mỏng manh của nó là mệnh lệnh đạo đức cao cả nhất của nhân loại.", "Thuyết trình về trách nhiệm bảo vệ Trái Đất.", "Phát âm chuẩn 'sanctuary' /ˈsæŋktjʊəri/ và 'moral imperative' /ˈmɒrəl ɪmˈpɛrətɪv/."),
        ("The primary rainforest in which thousands of critically endangered species reside must be shielded from illegal deforestation.", "/ðə ˈpraɪməri ˈreɪnˌfɒrɪst ɪn wɪʧ ˈθaʊzəndz ɒv ˈkrɪtɪkəli ɪnˈdeɪnʤəd ˈspiːʃiːz rɪˈzaɪd mʌst biː ˈʃiːldɪd frɒm ɪˈliːɡəl diːˌfɒrɪˈsteɪʃən/", "Khu rừng nhiệt đới nguyên sinh nơi hàng ngàn loài có nguy cơ tuyệt chủng nguy cấp đang cư trú phải được bảo vệ khỏi nạn phá rừng trái phép.", "Kêu gọi bảo vệ rừng nguyên sinh.", "Phát âm chuẩn mệnh đề 'in which thousands of endangered species reside'."),
        ("Transitioning rapidly from fossil fuels to renewable solar and offshore wind energy is crucial to halting global warming.", "/trænˈzɪʃənɪŋ ˈræpɪdli frɒm ˈfɒsl fjʊəlz tuː rɪˈnjuːəbl ˈsəʊlər ænd ɒfˈʃɔː wɪnd ˈɛnəʤi ɪz ˈkruːʃəl tuː ˈhɔːltɪŋ ˈɡləʊbəl ˈwɔːmɪŋ/", "Chuyển dịch nhanh chóng từ nhiên liệu hóa thạch sang năng lượng mặt trời tái tạo và điện gió ngoài khơi là điều tối quan trọng để ngăn chặn sự nóng lên toàn cầu.", "Thuyết trình về chuyển đổi năng lượng xanh.", "Phát âm chuẩn 'transitioning' /trænˈzɪʃənɪŋ/ và 'renewable' /rɪˈnjuːəbl/."),
        ("The dedicated marine conservationists with whom we volunteered restored five hectares of degraded coastal mangrove forests.", "/ðə ˈdɛdɪkeɪtɪd məˈriːn ˌkɒnsəˈveɪʃənɪsts wɪð huːm wiː ˌvɒlənˈtɪəd rɪˈstɔːd faɪv ˈhɛkteəz ɒv dɪˈɡreɪdɪd ˈkəʊstl ˈmæŋɡrəʊv ˈfɒrɪsts/", "Những nhà bảo tồn biển tận tụy mà chúng tôi cùng tham gia tình nguyện đã phục hồi 5 héc-ta rừng ngập mặn ven biển bị suy thoái.", "Kể về hoạt động trồng rừng ngập mặn.", "Phát âm chuẩn mệnh đề 'with whom we volunteered'."),
        ("Adopting biodegradable packaging and eliminating single-use plastic prevents lethal microplastic poisoning in our marine ecosystems.", "/əˈdɒptɪŋ ˌbaɪəʊdɪˈɡreɪdəbl ˈpækɪʤɪŋ ænd ɪˈlɪmɪneɪtɪŋ ˈsɪŋɡl-juːs ˈplæstɪk prɪˈvɛnts ˈliːθəl ˈmaɪkrəʊˌplæstɪk ˈpɔɪznɪŋ ɪn ˈaʊə məˈriːn ˈiːkəʊˌsɪstəmz/", "Sử dụng bao bì tự phân hủy sinh học và loại bỏ nhựa dùng một lần sẽ ngăn chặn ngộ độc vi nhựa gây chết người trong các hệ sinh thái biển của chúng ta.", "Tuyên truyền giảm rác thải nhựa.", "Phát âm chuẩn 'biodegradable' /ˌbaɪəʊdɪˈɡreɪdəbl/ và 'lethal' /ˈliːθəl/."),
        ("Can Gio Biosphere Reserve is the vast sanctuary where rare migratory birds seek winter refuge and thrive peacefully.", "/kæn ɡiəʊ ˈbaɪəʊsfɪə rɪˈzɜːv ɪz ðə vɑːst ˈsæŋktjʊəri weə reə ˈmaɪɡrətəri bɜːdz siːk ˈwɪntə ˈrɛfjuːʤ ænd θraɪv ˈpiːsfʊli/", "Khu dự trữ sinh quyển Cần Giờ là thánh địa bao la nơi các loài chim di cư quý hiếm tìm nơi trú đông và phát triển thanh bình.", "Giới thiệu Rừng ngập mặn Cần Giờ.", "Phát âm chuẩn 'migratory birds' /ˈmaɪɡrətəri bɜːdz/ và 'refuge' /ˈrɛfjuːʤ/."),
        ("The dramatic sea level rise caused by polar ice melting threatens agricultural productivity in low-lying river deltas.", "/ðə drəˈmætɪk siː ˈlɛvl raɪz kɔːzd baɪ ˈpəʊlər aɪs ˈmɛltɪŋ ˈθrɛtnz ˌæɡrɪˈkʌlʧərəl ˌprɒdʌkˈtɪvɪti ɪn ləʊ-ˈlaɪɪŋ ˈrɪvə ˈdɛltəz/", "Mực nước biển dâng cao đột ngột do băng hai cực tan chảy đe dọa năng suất nông nghiệp ở các vùng đồng bằng châu thổ trũng thấp.", "Cảnh báo nước biển dâng.", "Phát âm chuẩn 'sea level rise' và 'agricultural productivity'."),
        ("2050 is the historic milestone year when Vietnam aims to reach net-zero greenhouse gas emissions.", "/ˈtwɛnti ˈfɪfti ɪz ðə hɪsˈtɒrɪk ˈmaɪlstəʊn jɪə wɛn ˌvjɛtnæm eɪmz tuː riːʧ nɛt-ˈzɪərəʊ ˈɡriːnhaʊs ɡæs ɪˈmɪʃənz/", "Năm 2050 là năm cột mốc lịch sử khi Việt Nam đặt mục tiêu đạt mức phát thải ròng khí nhà kính bằng 0.", "Nói về mục tiêu Net-Zero 2050 của Việt Nam.", "Phát âm chuẩn 'net-zero emissions' /nɛt-ˈzɪərəʊ ɪˈmɪʃənz/."),
        ("The rooftop solar panels which were installed on our high school generate clean green electricity daily.", "/ðə ˈruːftɒp ˈsəʊlə ˈpænlz wɪʧ wɜːr ɪnˈstɔːld ɒn ˈaʊə haɪ skuːl ˈʤɛnəreɪt kliːn ɡriːn ɪlɛkˈtrɪsɪti ˈdeɪli/", "Những tấm pin năng lượng mặt trời trên mái trường học của chúng tôi tạo ra nguồn điện xanh sạch mỗi ngày.", "Kể về dự án điện mặt trời học đường.", "Phát âm chuẩn 'solar panels' /ˈsəʊlə ˈpænlz/."),
        ("The international environmental conference at which global climate policies were formulated concluded with inspiring commitments.", "/ði ˌɪntəˈnæʃənl ɪnˌvaɪrənˈmɛntl ˈkɒnfərəns æt wɪʧ ˈɡləʊbəl ˈklaɪmɪt ˈpɒlɪsiz wɜː ˈfɔːmjʊleɪtɪd kənˈkluːdɪd wɪð ɪnˈspaɪərɪŋ kəˈmɪtmənts/", "Hội nghị môi trường quốc tế nơi các chính sách khí hậu toàn cầu được hoạch định đã khép lại với những cam kết đầy cảm hứng.", "Thuyết trình về hiệp ước khí hậu.", "Phát âm chuẩn mệnh đề 'at which global climate policies were formulated'."),
        ("Preserving the upper ozone layer is vital because it shields all living organisms from dangerous cosmic radiation.", "/prɪˈzɜːvɪŋ ði ˈʌpər ˈəʊzəʊn ˈleɪər ɪz ˈvaɪtl bɪˈkɒz ɪt ʃiːldz ɔːl ˈlɪvɪŋ ˈɔːɡənɪzmz frɒm ˈdeɪnʤərəs ˈkɒzmɪk ˌreɪdɪˈeɪʃən/", "Gìn giữ tầng ô-dôn trên cao là điều sống còn vì nó che chắn mọi sinh vật sống khỏi bức xạ vũ trụ nguy hiểm.", "Giải thích vai trò tầng ô-dôn.", "Phát âm chuẩn 'ozone layer' và 'cosmic radiation' /ˈkɒzmɪk ˌreɪdɪˈeɪʃən/."),
        ("Every student who chooses to commute by bicycle actively reduces carbon emissions in our neighborhood.", "/ˈɛvri ˈstjuːdənt huː ˈʧuːzɪz tuː kəˈmjuːt baɪ ˈbaɪsɪkl ˈæktɪvli rɪˈdjuːsɪz ˈkɑːbən ɪˈmɪʃənz ɪn ˈaʊə ˈneɪbəhʊd/", "Mỗi học sinh chọn đi lại bằng xe đạp đều tích cực giảm thiểu lượng khí thải carbon trong khu phố của chúng ta.", "Khen ngợi việc đi xe đạp đến trường.", "Phát âm chuẩn 'commute by bicycle' và 'carbon emissions'."),
        ("The massive offshore wind turbines whose blades rotate above the ocean produce megawatt hours of clean energy.", "/ðə ˈmæsɪv ɒfˈʃɔː wɪnd ˈtɜːbaɪnz huːz bleɪdz rəʊˈteɪt əˈbʌv ði ˈəʊʃən prəˈdjuːs ˈmɛɡəwɒt ˈaʊəz ɒv kliːn ˈɛnəʤi/", "Những tua-bin gió ngoài khơi khổng lồ có cánh quạt quay trên mặt biển sản xuất hàng ngàn megawatt-giờ năng lượng sạch.", "Miêu tả điện gió ngoài khơi.", "Phát âm chuẩn 'offshore wind turbines' /ɒfˈʃɔː wɪnd ˈtɜːbaɪnz/."),
        ("Reforestation on barren hillsides stabilizes soil structures, replenishes underground aquifers, and prevents catastrophic landslides.", "/riːˌfɒrɪˈsteɪʃən ɒn ˈbærən ˈhɪlsaɪdz ˈsteɪbɪlaɪzɪz sɔɪl ˈstrʌkʧəz rɪˈplɛnɪʃɪz ˌʌndəˈɡraʊnd ˈækwɪfəz ænd prɪˈvɛnts ˌkætəˈstrɒfɪk ˈlændslaɪdz/", "Việc trồng lại rừng trên các sườn đồi trọc giúp ổn định cấu trúc đất, bổ sung các tầng nước ngầm và ngăn ngừa sạt lở đất thảm khốc.", "Phân tích tác dụng của trồng rừng.", "Phát âm chuẩn 'replenishes aquifers' /rɪˈplɛnɪʃɪz ˈækwɪfəz/ và 'landslides' /ˈlændslaɪdz/."),
        ("If we do not take decisive ecological action today, future generations will inherit a severely degraded biosphere.", "/ɪf wiː duː nɒt teɪk dɪˈsaɪsɪv ˌiːkəˈlɒʤɪkəl ˈækʃən təˈdeɪ ˈfjuːʧə ˌʤɛnəˈreɪʃənz wɪl ɪnˈhɛrɪt ə sɪˈvɪəli dɪˈɡreɪdɪd ˈbaɪəʊsfɪə/", "Nếu chúng ta không hành động sinh thái quyết liệt ngay hôm nay, các thế hệ tương lai sẽ phải thừa hưởng một sinh quyển bị suy thoái nghiêm trọng.", "Cảnh báo khẩn cấp về môi trường.", "Phát âm chuẩn 'decisive action' /dɪˈsaɪsɪv ˈækʃən/ và 'degraded biosphere' /dɪˈɡreɪdɪd ˈbaɪəʊsfɪə/."),
        ("The young conservationist whose speech on wildlife protection went viral inspired thousands of teenagers nationwide.", "/ðə jʌŋ ˌkɒnsəˈveɪʃənɪst huːz spiːʧ ɒn ˈwaɪldlaɪf prəˈtɛkʃən wɛnt ˈvaɪərəl ɪnˈspaɪəd ˈθaʊzəndz ɒv ˈtiːneɪʤəz ˈneɪʃənwaɪd/", "Nhà bảo tồn trẻ có bài phát biểu về bảo vệ động vật hoang dã lan truyền mạnh mẽ đã truyền cảm hứng cho hàng ngàn bạn trẻ trên toàn quốc.", "Khen ngợi nhà hoạt động trẻ.", "Phát âm chuẩn 'conservationist' /ˌkɒnsəˈveɪʃənɪst/."),
        ("Mindful resource consumption and zero-waste composting turn household organic scraps into rich soil fertilizer.", "/ˈmaɪndfʊl rɪˈsɔːs kənˈsʌmpʃən ænd ˈzɪərəʊ-weɪst ˈkɒmpɒstɪŋ tɜːn ˈhaʊshəʊld ɔːˈɡænɪk skræps ˈɪntuː rɪʧ sɔɪl ˈfɜːtɪlaɪzə/", "Tiêu dùng tài nguyên có chánh niệm và ủ phân hữu cơ không rác thải biến thức ăn thừa gia đình thành phân bón đất màu mỡ.", "Nói về ủ phân hữu cơ.", "Phát âm chuẩn 'composting' /ˈkɒmpɒstɪŋ/ và 'fertilizer' /ˈfɜːtɪlaɪzə/."),
        ("Let us unite our hearts, minds, and actions to heal our magnificent blue planet together.", "/lɛt ʌs juːˈnaɪt ˈaʊə hɑːts maɪndz ænd ˈækʃənz tuː hiːl ˈaʊə mæɡˈnɪfɪsnt bluː ˈplænɪt təˈɡɛðə/", "Chúng ta hãy cùng đồng lòng kết nối trái tim, trí tuệ và hành động để cùng nhau chữa lành hành tinh xanh tráng lệ của chúng ta.", "Kêu gọi hành động vì Trái Đất.", "Phát âm chuẩn 'heal our magnificent blue planet'."),
        ("May every green tree planted blossom into a living monument of hope, peace, and biodiversity.", "/meɪ ˈɛvri ɡriːn triː ˈplɑːntɪd ˈblɒsəm ˈɪntuː ə ˈlɪvɪŋ ˈmɒnjʊmənt ɒv həʊp piːs ænd ˌbaɪəʊdaɪˈvɜːsɪti/", "Chúc cho mỗi cây xanh được gieo trồng sẽ nở rộ thành một tượng đài sống động của niềm hy vọng, hòa bình và sự đa dạng sinh học.", "Lời chúc môi trường xanh tươi.", "Phát âm chuẩn 'living monument' /ˈlɪvɪŋ ˈmɒnjʊmənt/."),
        ("Every single breath we draw connects us inextricably to the vibrant breathing biosphere of Planet Earth.", "/ˈɛvri ˈsɪŋɡl brɛθ wiː drɔː kəˈnɛkts ʌs ˌɪnɪksˈtrɪkəbli tuː ðə ˈvaɪbrənt ˈbriːðɪŋ ˈbaɪəʊsfɪər ɒv ˈplænɪt ɜːθ/", "Mỗi một hơi thở chúng ta hít vào đều kết nối chúng ta một cách không thể tách rời với sinh quyển thở đầy sức sống của Hành tinh Trái Đất.", "Thông điệp thiêng liêng về sự sống.", "Phát âm chuẩn 'inextricably' /ˌɪnɪksˈtrɪkəbli/ và 'breathing biosphere'.")
    ])
]

u10_reading_info = {
    "title": "Hành Tinh Trái Đất Trước Khủng Hoảng Khí Hậu: Thách Thức Toàn Cầu & Lộ Trình Xanh",
    "topic": "Khủng hoảng biến đổi khí hậu, hiệu ứng nhà kính, chuyển dịch năng lượng tái tạo và phục hồi sinh quyển",
    "passageText": "Planet Earth, the sole known oasis of life in the cosmic void, faces an unprecedented anthropogenic crisis. Decades of unbridled industrialization and excessive reliance on fossil fuels have pumped gigatons of carbon dioxide and methane into the upper atmosphere. Consequently, the intensified greenhouse effect traps excess solar radiation, driving global surface temperatures upward at rates never recorded in geological history.\n\nThe repercussions of this planetary thermal surge are manifested across all continents. Polar glaciers and ice sheets are melting rapidly, precipitating accelerated sea level rise that threatens to submerge fertile low-lying agricultural deltas, including the Mekong Delta. Concurrently, climate instability fuels catastrophic extreme weather events: scorching multi-year droughts, ferocious super typhoons, and uncontainable wildfires that devastate ancient biodiversity hotspots.\n\nOvercoming this existential crisis requires a revolutionary transformation in human energy systems and ecological ethics. Nations worldwide are rapidly replacing coal-fired thermal plants with sprawling offshore wind farms, solar fields, and advanced battery storage technologies. Parallel to this green technological shift, global initiatives emphasize massive ecosystem restoration: rehabilitating coastal mangroves, restoring deforested watersheds, and enforcing circular economy zero-waste frameworks. Ultimately, safeguarding Planet Earth is not merely an environmental policy; it is the fundamental moral duty of every conscious citizen to protect the web of life for generations unborn.",
    "keyVocabularyHighlights": [
        {"word": "anthropogenic crisis", "meaning": "cuộc khủng hoảng môi trường do chính con người gây ra"},
        {"word": "planetary thermal surge", "meaning": "sự tăng vọt nhiệt độ trên phạm vi toàn hành tinh"},
        {"word": "existential crisis", "meaning": "cuộc khủng hoảng đe dọa sự tồn vong của nhân loại"},
        {"word": "circular economy", "meaning": "mô hình kinh tế tuần hoàn tái sử dụng tài nguyên"}
    ]
}

u10_reading_qs = [
    {"id": "u10-r1", "question": "What is the primary cause of the climate crisis according to paragraph 1?", "options": ["A. Industrialization and excessive reliance on fossil fuels releasing gigatons of greenhouse gases", "B. Volcanic eruptions on the moon", "C. Deep sea fishing only", "D. Planting too many trees"], "correctAnswerIndex": 0, "explanation": "Trong đoạn 1: 'Decades of unbridled industrialization and excessive reliance on fossil fuels have pumped gigatons of carbon dioxide and methane into the upper atmosphere.'"},
    {"id": "u10-r2", "question": "How does the intensified greenhouse effect alter global temperatures?", "options": ["A. Traps excess solar radiation, driving temperatures upward at unprecedented rates", "B. Freezes all oceans into solid ice", "C. Causes the sun to disappear", "D. Lowers global temperatures drastically"], "correctAnswerIndex": 0, "explanation": "Trong đoạn 1: 'the intensified greenhouse effect traps excess solar radiation, driving global surface temperatures upward...'"},
    {"id": "u10-r3", "question": "What region is specifically highlighted as threatened by sea level rise in paragraph 2?", "options": ["A. Fertile low-lying deltas, including the Mekong Delta", "B. The top of Mount Everest", "C. The Sahara Desert", "D. The Moon craters"], "correctAnswerIndex": 0, "explanation": "Trong đoạn 2: 'submerge fertile low-lying agricultural deltas, including the Mekong Delta.'"},
    {"id": "u10-r4", "question": "What extreme weather events are fueled by climate instability?", "options": ["A. Scorching droughts, ferocious super typhoons, and uncontainable wildfires", "B. Gentle mild showers only", "C. Cool breezes everywhere", "D. Perfect sunny days"], "correctAnswerIndex": 0, "explanation": "Trong đoạn 2: 'scorching multi-year droughts, ferocious super typhoons, and uncontainable wildfires...'"},
    {"id": "u10-r5", "question": "What clean energy technologies are replacing coal-fired thermal plants?", "options": ["A. Sprawling offshore wind farms, solar fields, and advanced battery storage", "B. Wood-burning stoves", "C. Heavy diesel generators", "D. Kerosene lamps"], "correctAnswerIndex": 0, "explanation": "Trong đoạn 3: 'replacing coal-fired thermal plants with sprawling offshore wind farms, solar fields, and advanced battery storage technologies.'"},
    {"id": "u10-r6", "question": "What ecological restoration initiatives are emphasized alongside clean energy?", "options": ["A. Rehabilitating coastal mangroves, restoring watersheds, and zero-waste frameworks", "B. Paving all forests with concrete", "C. Cutting down all mangrove trees", "D. Dumping waste into the ocean"], "correctAnswerIndex": 0, "explanation": "Trong đoạn 3: 'rehabilitating coastal mangroves, restoring deforested watersheds, and enforcing circular economy zero-waste frameworks.'"},
    {"id": "u10-r7", "question": "What is the ultimate definition of safeguarding Planet Earth at the end?", "options": ["A. The fundamental moral duty of every conscious citizen to protect the web of life", "B. A hobby for weekends only", "C. An optional game", "D. A commercial business trick"], "correctAnswerIndex": 0, "explanation": "Trong đoạn 3: 'it is the fundamental moral duty of every conscious citizen to protect the web of life for generations unborn.'"},
    {"id": "u10-r8", "question": "Which word in paragraph 1 is closest in meaning to 'anthropogenic'?", "options": ["A. Caused or originated by human activity and influence", "B. Formed by space meteorites", "C. Created by ancient dinosaurs", "D. Occurring naturally without cause"], "correctAnswerIndex": 0, "explanation": "'Anthropogenic' có nghĩa là bắt nguồn từ hoặc do hoạt động của con người gây ra."},
    {"id": "u10-r9", "question": "Which word in paragraph 2 is closest in meaning to 'submerge'?", "options": ["A. Inundate, flood, or completely cover with water", "B. Dry out into desert dust", "C. Freeze into solid crystal", "D. Elevate into high mountains"], "correctAnswerIndex": 0, "explanation": "'Submerge' có nghĩa là nhấn chìm, làm ngập hoàn toàn trong nước."},
    {"id": "u10-r10", "question": "What is the best title for this passage?", "options": ["A. Planet Earth in Climate Crisis: Global Challenges and the Green Roadmap", "B. The Architecture of Ancient Roman Bridges", "C. A Beginner's Guide to Deep-Sea Scuba Gear", "D. History of Medieval Steam Trains"], "correctAnswerIndex": 0, "explanation": "Tiêu đề chuẩn xác nhất phản ánh cuộc khủng hoảng khí hậu của Trái Đất và lộ trình chuyển đổi xanh toàn cầu."}
]

u10_writing_prompts = [
    {
        "id": "u10-w1",
        "title": "Đề 1: Write a paragraph about what students can do to reduce their carbon footprint (60-80 words)",
        "description": "Viết một đoạn văn nêu những hành động cụ thể học sinh có thể thực hiện để giảm thiểu dấu chân carbon hàng ngày.",
        "suggestedOutline": [
            "Introduction: State that students can take practical actions to shrink their carbon footprint.",
            "Body: Give actions (cycling/walking to school, turning off unused lights/fans, using reusable bottles, eating more plant-based meals).",
            "Conclusion: Affirm that small daily changes collectively protect Planet Earth."
        ],
        "usefulPhrases": [
            "Students can take meaningful daily actions to significantly shrink their individual carbon footprint...",
            "First, we should commute to school by bicycle or walk instead of relying on motorbikes...",
            "Second, turning off electrical appliances when not in use and carrying reusable stainless-steel water bottles eliminates waste...",
            "These conscious green habits collectively preserve our planet's fragile biosphere."
        ],
        "wordLimit": "60 - 80 từ",
        "sampleGrade10Response": "Students can take meaningful daily actions to significantly shrink their carbon footprint. First, commuting to school by bicycle or walking instead of riding motorbikes directly reduces harmful carbon emissions. Second, diligently turning off lights and computers when leaving classrooms conserves precious electricity. Furthermore, carrying refillable water bottles and reusable lunch containers eliminates single-use plastic waste. These conscious daily habits collectively help protect our planet's fragile biosphere from climate change."
    },
    {
        "id": "u10-w2",
        "title": "Đề 2: Write a paragraph on the benefits of switching to renewable energy (60-80 words)",
        "description": "Viết một đoạn văn trình bày những lợi ích sống còn khi chuyển đổi sang các nguồn năng lượng tái tạo.",
        "suggestedOutline": [
            "Introduction: State that transitioning to renewable energy is vital to combating global climate change.",
            "Body: Detail benefits (infinite clean power from sun/wind, zero greenhouse gas emissions, reducing air pollution, protecting human health).",
            "Conclusion: Urge widespread investment in clean green technologies."
        ],
        "usefulPhrases": [
            "Transitioning from polluting fossil fuels to renewable energy sources is essential for Earth's future...",
            "Harnessing clean solar radiation and offshore wind power produces limitless electricity without generating greenhouse emissions...",
            "Moreover, phasing out coal-fired thermal plants drastically reduces urban smog and respiratory illnesses...",
            "Investing aggressively in green energy technologies guarantees sustainable prosperity for future generations."
        ],
        "wordLimit": "60 - 80 từ",
        "sampleGrade10Response": "Transitioning from polluting fossil fuels to clean renewable energy is essential for our planet's future. Harnessing boundless solar power and offshore wind energy produces clean electricity with zero harmful greenhouse gas emissions. Moreover, replacing coal-fired thermal plants drastically cleans urban air and prevents chronic respiratory diseases. By aggressively developing green energy technologies, humanity can combat catastrophic global warming while securing sustainable economic development for generations to come."
    },
    {
        "id": "u10-w3",
        "title": "Đề 3: Write a paragraph on the devastating consequences of deforestation (60-80 words)",
        "description": "Viết một đoạn văn cảnh báo những hậu quả tàn khốc của nạn phá rừng đối với khí hậu và đa dạng sinh học.",
        "suggestedOutline": [
            "Introduction: State that rampant deforestation is a catastrophic threat to Planet Earth.",
            "Body: Explain severe consequences (loss of wildlife habitats leading to extinction, loss of natural carbon sinks, causing landslides/floods).",
            "Conclusion: Call for strict forest protection and global afforestation."
        ],
        "usefulPhrases": [
            "Rampant deforestation inflicts catastrophic damage upon global climate stability and biodiversity...",
            "When primary rainforests are cleared, thousands of rare species lose their natural habitats and face extinction...",
            "Furthermore, destroying forests removes Earth's vital carbon sinks, accelerating global warming and triggering severe flash floods...",
            "Strict anti-logging laws and urgent reforestation campaigns are essential to revive our planet's green lungs."
        ],
        "wordLimit": "60 - 80 từ",
        "sampleGrade10Response": "Rampant deforestation inflicts catastrophic damage upon global climate stability and biodiversity. When primary rainforests are destroyed, millions of unique wild animals lose their natural habitats, accelerating the extinction crisis. Furthermore, felling ancient trees eliminates Earth's vital carbon sinks, releasing trapped carbon and intensifying global warming. Deforested mountain slopes also trigger severe flash floods and destructive landslides. Protecting existing forests and planting new trees are urgent global imperatives."
    },
    {
        "id": "u10-w4",
        "title": "Đề 4: Write a paragraph on why protecting mangrove forests is crucial for coastal Vietnam (60-80 words)",
        "description": "Viết một đoạn văn phân tích tại sao việc bảo vệ rừng ngập mặn là điều sống còn đối với các vùng ven biển Việt Nam.",
        "suggestedOutline": [
            "Introduction: State that mangrove forests are indispensable green shields for coastal Vietnam.",
            "Body: Explain functions (shielding against typhoons/sea surges, trapping massive blue carbon, serving as nurseries for marine life).",
            "Conclusion: Emphasize the necessity of restoring coastal mangrove ecosystems."
        ],
        "usefulPhrases": [
            "Mangrove forests act as indispensable natural green shields protecting Vietnam's extensive coastline...",
            "Their dense intertwined roots buffer coastal villages against violent typhoon waves, storm surges, and coastal erosion...",
            "Additionally, mangroves serve as highly efficient carbon sinks and fertile nurseries for countless marine fish and crabs...",
            "Restoring and expanding mangrove ecosystems is critical for coastal climate resilience."
        ],
        "wordLimit": "60 - 80 từ",
        "sampleGrade10Response": "Mangrove forests act as indispensable natural green shields protecting Vietnam's extensive coastline. Their dense, intertwined root systems buffer coastal settlements against ferocious typhoon waves, storm surges, and severe soil erosion. Additionally, mangroves sequester massive amounts of blue carbon and provide safe breeding nurseries for hundreds of fish and crustacean species. Restoring and protecting mangrove ecosystems in places like Can Gio is critical to enhancing our national climate resilience."
    },
    {
        "id": "u10-w5",
        "title": "Đề 5: Write a paragraph proposing a green school project to protect the environment (60-80 words)",
        "description": "Viết một đoạn văn đề xuất một dự án trường học xanh để bảo vệ môi trường và lan tỏa lối sống bền vững.",
        "suggestedOutline": [
            "Introduction: Propose a 'Green Campus Initiative' for your secondary school.",
            "Body: Outline key activities (installing classroom recycling bins, planting organic vegetable gardens, running a monthly plastic-free day).",
            "Conclusion: State how this project empowers students to become eco-champions."
        ],
        "usefulPhrases": [
            "I propose launching a comprehensive 'Green Campus Initiative' in our secondary school...",
            "The project will establish colored recycling stations for paper and plastics, and create an organic school garden...",
            "Furthermore, hosting monthly plastic-free days will encourage students to bring reusable food containers...",
            "This hands-on initiative will empower students to become proactive champions of environmental sustainability."
        ],
        "wordLimit": "60 - 80 từ",
        "sampleGrade10Response": "I propose launching a comprehensive 'Green Campus Initiative' in our school to inspire environmental action. This project will install designated waste-sorting stations in every hallway for recycling plastics, cans, and paper. Furthermore, students will plant an organic rooftop vegetable garden fertilized with composted food scraps from the canteen. By organizing monthly plastic-free days, this initiative will empower every student to practice real sustainability and protect our cherished Earth."
    }
]

unit10 = make_unit(10, "Unit 10: Planet Earth", "Hành tinh Trái Đất & Khủng hoảng khí hậu", "Khám phá biến đổi khí hậu, năng lượng tái tạo, bảo vệ rừng ngập mặn, Mệnh đề quan hệ với giới từ (in which, with whom) và Trạng từ quan hệ (where, when, why).", "Ngữ âm: Nhấn trọng âm các thuật ngữ môi trường đa âm tiết và ngữ điệu câu cảnh báo sinh thái", "Sun", u10_vocab, u10_grammar_info, u10_grammar_exs, u10_listening_info, u10_listening_qs, u10_listening_fibs, u10_speaking, u10_reading_info, u10_reading_qs, u10_writing_prompts)
write_ts_unit(10, unit10)
print("Unit 10 generated successfully!")

