import json
from gen_unit_utils import make_unit, write_ts_unit

# ==============================================================================
# UNIT 11: ELECTRONIC DEVICES (20 Vocab, 20 Grammar, 8 Listening MC + 4 FIB, 20 Speaking, 10 Reading, 5 Writing)
# ==============================================================================
u11_vocab = [
    {"id": "u11-v1", "word": "artificial intelligence", "phonetic": "/ˌɑːtɪˈfɪʃəl ɪnˈtɛlɪʤəns/", "partOfSpeech": "noun", "vietnameseMeaning": "trí tuệ nhân tạo (AI)", "englishExample": "Artificial intelligence algorithms customize personalized learning paths for secondary students.", "vietnameseExample": "Các thuật toán trí tuệ nhân tạo tùy biến các lộ trình học tập cá nhân hóa cho học sinh cấp hai."},
    {"id": "u11-v2", "word": "digital device", "phonetic": "/ˈdɪʤɪtl dɪˈvaɪs/", "partOfSpeech": "noun", "vietnameseMeaning": "thiết bị kỹ thuật số (máy tính bảng, laptop, điện thoại)", "englishExample": "Modern classrooms integrate digital devices to make STEM lessons interactive and engaging.", "vietnameseExample": "Các lớp học hiện đại tích hợp thiết bị kỹ thuật số để làm cho các bài học STEM trở nên tương tác và lôi cuốn."},
    {"id": "u11-v3", "word": "cybersecurity", "phonetic": "/ˌsaɪbəsɪˈkjʊərɪti/", "partOfSpeech": "noun", "vietnameseMeaning": "an ninh mạng, an toàn thông tin số", "englishExample": "Teaching teenagers strong cybersecurity habits prevents personal data theft and online fraud.", "vietnameseExample": "Dạy thanh thiếu niên các thói quen an ninh mạng vững chắc giúp ngăn ngừa đánh cắp dữ liệu cá nhân và lừa đảo trực tuyến."},
    {"id": "u11-v4", "word": "virtual reality", "phonetic": "/ˈvɜːʧʊəl riˈælɪti/", "partOfSpeech": "noun", "vietnameseMeaning": "thực tế ảo (VR)", "englishExample": "Virtual reality headsets transport students on simulated field trips inside the human bloodstream.", "vietnameseExample": "Kính thực tế ảo đưa học sinh vào các chuyến dã ngoại mô phỏng bên trong dòng máu của con người."},
    {"id": "u11-v5", "word": "e-learning platform", "phonetic": "/ˈiː-ˌlɜːnɪŋ ˈplætfɔːm/", "partOfSpeech": "noun", "vietnameseMeaning": "nền tảng học tập điện tử trực tuyến", "englishExample": "Our school's e-learning platform hosts thousands of recorded lectures and interactive quizzes.", "vietnameseExample": "Nền tảng học trực tuyến của trường chúng tôi lưu trữ hàng ngàn bài giảng ghi hình và câu đố tương tác."},
    {"id": "u11-v6", "word": "touchscreen", "phonetic": "/ˈtʌʧskriːn/", "partOfSpeech": "noun", "vietnameseMeaning": "màn hình cảm ứng", "englishExample": "Interactive touchscreen smartboards allow teachers to annotate complex diagrams effortlessly.", "vietnameseExample": "Bảng thông minh màn hình cảm ứng tương tác cho phép giáo viên chú thích các sơ đồ phức tạp một cách dễ dàng."},
    {"id": "u11-v7", "word": "digital footprint", "phonetic": "/ˈdɪʤɪtl ˈfʊtprɪnt/", "partOfSpeech": "noun", "vietnameseMeaning": "dấu chân kỹ thuật số (vết tích dữ liệu cá nhân trên Internet)", "englishExample": "Being mindful of your digital footprint protects your online privacy and future career reputation.", "vietnameseExample": "Có ý thức về dấu chân kỹ thuật số giúp bảo vệ quyền riêng tư trực tuyến và uy tín nghề nghiệp tương lai."},
    {"id": "u11-v8", "word": "cloud computing", "phonetic": "/klaʊd kəmˈpjuːtɪŋ/", "partOfSpeech": "noun", "vietnameseMeaning": "điện toán đám mây (lưu trữ & xử lý trực tuyến)", "englishExample": "Cloud computing enables collaborative group editing of documents in real time across continents.", "vietnameseExample": "Điện toán đám mây cho phép nhóm cùng chỉnh sửa tài liệu theo thời gian thực trên khắp các châu lục."},
    {"id": "u11-v9", "word": "wearable gadget", "phonetic": "/ˈweərəbl ˈɡæʤɪt/", "partOfSpeech": "noun", "vietnameseMeaning": "thiết bị đeo thông minh (đồng hồ thông minh, vòng đeo sức khỏe)", "englishExample": "Smartwatches and other wearable gadgets track heart rates, daily steps, and sleep cycles.", "vietnameseExample": "Đồng hồ thông minh và các thiết bị đeo thông minh khác theo dõi nhịp tim, số bước chân hàng ngày và chu kỳ giấc ngủ."},
    {"id": "u11-v10", "word": "broadband connection", "phonetic": "/ˈbrɔːdbænd kəˈnɛkʃən/", "partOfSpeech": "noun", "vietnameseMeaning": "kết nối internet băng thông rộng tốc độ cao", "englishExample": "High-speed broadband connections are essential for seamless virtual video conferences.", "vietnameseExample": "Kết nối băng thông rộng tốc độ cao là điều thiết yếu cho các hội nghị truyền hình trực tuyến mượt mà."},
    {"id": "u11-v11", "word": "software application", "phonetic": "/ˈsɒftweər ˌæplɪˈkeɪʃən/", "partOfSpeech": "noun", "vietnameseMeaning": "ứng dụng phần mềm", "englishExample": "Educational software applications utilize gamification to make grammar revision fun.", "vietnameseExample": "Các ứng dụng phần mềm giáo dục sử dụng cơ chế trò chơi hóa để làm cho việc ôn tập ngữ pháp trở nên thú vị."},
    {"id": "u11-v12", "word": "digital literacy", "phonetic": "/ˈdɪʤɪtl ˈlɪtərəsi/", "partOfSpeech": "noun", "vietnameseMeaning": "năng lực số, kỹ năng làm chủ công nghệ số", "englishExample": "Digital literacy empowers students to critically evaluate online information and detect fake news.", "vietnameseExample": "Năng lực số giúp học sinh đánh giá phản biện thông tin trực tuyến và phát hiện tin giả."},
    {"id": "u11-v13", "word": "voice recognition", "phonetic": "/vɔɪs ˌrɛkəɡˈnɪʃən/", "partOfSpeech": "noun", "vietnameseMeaning": "công nghệ nhận diện giọng nói", "englishExample": "Voice recognition technology powers AI speech tutors to evaluate English phonetics accurately.", "vietnameseExample": "Công nghệ nhận diện giọng nói vận hành các gia sư AI để đánh giá ngữ âm tiếng Anh chuẩn xác."},
    {"id": "u11-v14", "word": "storage capacity", "phonetic": "/ˈstɔːrɪʤ kəˈpæsɪti/", "partOfSpeech": "noun", "vietnameseMeaning": "dung lượng bộ nhớ lưu trữ", "englishExample": "Solid-state drives offer massive storage capacity and lightning-fast file transfer speeds.", "vietnameseExample": "Ổ cứng thể rắn mang lại dung lượng lưu trữ khổng lồ và tốc độ truyền tệp nhanh như chớp."},
    {"id": "u11-v15", "word": "rechargeable battery", "phonetic": "/riːˈʧɑːʤəbl ˈbætəri/", "partOfSpeech": "noun", "vietnameseMeaning": "pin có thể sạc lại", "englishExample": "Modern smartphones feature long-lasting rechargeable batteries with rapid wireless charging.", "vietnameseExample": "Điện thoại thông minh hiện đại sở hữu pin sạc dùng lâu với tính năng sạc không dây siêu nhanh."},
    {"id": "u11-v16", "word": "automation", "phonetic": "/ˌɔːtəˈmeɪʃən/", "partOfSpeech": "noun", "vietnameseMeaning": "sự tự động hóa", "englishExample": "Smart home automation allows users to control lighting and air conditioners remotely via phones.", "vietnameseExample": "Tự động hóa nhà thông minh cho phép người dùng điều khiển đèn và điều hòa từ xa qua điện thoại."},
    {"id": "u11-v17", "word": "data encryption", "phonetic": "/ˈdeɪtə ɪnˈkrɪpʃən/", "partOfSpeech": "noun", "vietnameseMeaning": "mã hóa dữ liệu bảo mật", "englishExample": "End-to-end data encryption protects sensitive banking transactions from unauthorized hacking.", "vietnameseExample": "Mã hóa dữ liệu đầu cuối bảo vệ các giao dịch ngân hàng nhạy cảm khỏi sự xâm nhập trái phép."},
    {"id": "u11-v18", "word": "augmented reality", "phonetic": "/ɔːɡˈmɛntɪd riˈælɪti/", "partOfSpeech": "noun", "vietnameseMeaning": "thực tế tăng cường (AR)", "englishExample": "Augmented reality overlays 3D anatomical models onto biology textbooks in real time.", "vietnameseExample": "Thực tế tăng cường phủ các mô hình giải phẫu 3D lên sách giáo khoa sinh học theo thời gian thực."},
    {"id": "u11-v19", "word": "microchip", "phonetic": "/ˈmaɪkrəʊˌʧɪp/", "partOfSpeech": "noun", "vietnameseMeaning": "vi mạch bán dẫn, chip vi xử lý", "englishExample": "Advanced semiconductor microchips drive the computing power of supercomputers and space probes.", "vietnameseExample": "Các vi mạch bán dẫn tiên tiến thúc đẩy sức mạnh tính toán của siêu máy tính và tàu thám hiểm không gian."},
    {"id": "u11-v20", "word": "technological breakthrough", "phonetic": "/ˌtɛknəˈlɒʤɪkəl ˈbreɪkθruː/", "partOfSpeech": "noun", "vietnameseMeaning": "bước đột phá công nghệ mang tính cách mạng", "englishExample": "Quantum computing represents a monumental technological breakthrough in global science.", "vietnameseExample": "Điện toán lượng tử đại diện cho một bước đột phá công nghệ hoành tráng trong khoa học toàn cầu."}
]

u11_grammar_info = {
    "title": "Câu Tường Thuật (Reported Speech: Statements, Questions, Requests & Commands)",
    "summary": "Nắm vững quy tắc chuyển từ câu trực tiếp sang câu gián tiếp/tường thuật: lùi thì (Tense backshift), đổi đại từ (Pronouns), đổi trạng từ chỉ thời gian & nơi chốn (Time & place adverbs), và cấu trúc câu hỏi tường thuật (S + asked + O + if/whether hoặc Wh-word + S + V).",
    "formulaBox": [
        "1. Câu trần thuật: S + said (that) + S + V(lùi thì) / S + told + O (that) + S + V(lùi thì)",
        "2. Câu hỏi Yes/No: S + asked + (O) + IF / WHETHER + S + V(lùi thì)",
        "3. Câu hỏi Wh-: S + asked + (O) + WH-WORD + S + V(lùi thì)",
        "4. Mệnh lệnh/yêu cầu: S + told / asked / advised + O + (NOT) TO + V-inf",
        "Quy tắc lùi thì: Hiện tại đơn -> Quá khứ đơn; Hiện tại tiếp diễn -> Quá khứ tiếp diễn; Hiện tại hoàn thành -> Quá khứ hoàn thành; will -> would; can -> could; must -> had to.",
        "Quy tắc đổi trạng từ: now -> then, today -> that day, yesterday -> the day before, tomorrow -> the next/following day, here -> there, this -> that, these -> those."
    ],
    "usagePoints": [
        {"title": "1. Câu hỏi trong câu tường thuật", "detail": "Trong câu hỏi tường thuật, trật tự từ trở về dạng khẳng định (S + V), KHÔNG đảo trợ động từ (do/does/did) ra trước chủ ngữ.", "example": "He asked me: 'Where do you buy this tablet?' -> He asked me where I bought that tablet."},
        {"title": "2. Câu mệnh lệnh / yêu cầu", "detail": "Dùng cấu trúc 'tell / ask + O + to V'.", "example": "The teacher told us to turn off our electronic devices during the exam."}
    ]
}

u11_grammar_exs = [
    {"id": "u11-g1", "question": "Minh said that he _____ a new touchscreen tablet the previous day.", "options": ["A. had bought", "B. bought", "C. buys", "D. has bought"], "correctAnswer": "A. had bought", "explanation": "Câu trực tiếp ở thì Quá khứ đơn ('yesterday' -> 'the previous day') khi lùi thì chuyển thành Quá khứ hoàn thành 'had bought'."},
    {"id": "u11-g2", "question": "The teacher told us _____ our smartphones during the national examination.", "options": ["A. not to use", "B. to not use", "C. not use", "D. do not use"], "correctAnswer": "A. not to use", "explanation": "Cấu trúc mệnh lệnh tường thuật phủ định: 'tell + O + not to V' -> 'told us not to use'."},
    {"id": "u11-g3", "question": "Lan asked me if I _____ how to install that English learning app.", "options": ["A. knew", "B. know", "C. have known", "D. am knowing"], "correctAnswer": "A. knew", "explanation": "Câu hỏi Yes/No tường thuật: S + asked + if + S + V(lùi thì) -> 'knew'."},
    {"id": "u11-g4", "question": "The IT technician asked Nam where he _____ his encrypted password.", "options": ["A. stored", "B. does store", "C. did store", "D. stores"], "correctAnswer": "A. stored", "explanation": "Câu hỏi Wh- tường thuật theo trật tự khẳng định S + V(lùi thì) -> 'where he stored'."},
    {"id": "u11-g5", "question": "My father told me that excessive screen time _____ bad for my eyesight.", "options": ["A. was", "B. is", "C. has been", "D. will be"], "correctAnswer": "A. was", "explanation": "Lùi thì từ 'is' sang 'was' trong câu gián tiếp."},
    {"id": "u11-g6", "question": "She asked her classmate _____ he could lend her his wireless mouse.", "options": ["A. whether", "B. what", "C. where", "D. which"], "correctAnswer": "A. whether", "explanation": "Câu hỏi Yes/No gián tiếp dùng 'if' hoặc 'whether'."},
    {"id": "u11-g7", "question": "The instructor asked us _____ we had backed up our digital files onto the cloud.", "options": ["A. if", "B. what", "C. who", "D. whose"], "correctAnswer": "A. if", "explanation": "Câu hỏi Yes/No tường thuật: 'asked us if we had backed up...'."},
    {"id": "u11-g8", "question": "Phong said, 'I will purchase a new smartwatch tomorrow.' -> Phong said that he _____ a new smartwatch the following day.", "options": ["A. would purchase", "B. will purchase", "C. purchased", "D. had purchased"], "correctAnswer": "A. would purchase", "explanation": "'will' lùi thì thành 'would', 'tomorrow' đổi thành 'the following day'."},
    {"id": "u11-g9", "question": "The teacher asked the students what electronic devices they _____ for online research.", "options": ["A. used", "B. do use", "C. did use", "D. are using"], "correctAnswer": "A. used", "explanation": "Câu hỏi Wh- tường thuật: 'what electronic devices they used' (trật tự khẳng định S + V)."},
    {"id": "u11-g10", "question": "He told his sister _____ the rechargeable battery overnight to prevent degradation.", "options": ["A. not to overcharge", "B. not overcharge", "C. don't overcharge", "D. not overcharging"], "correctAnswer": "A. not to overcharge", "explanation": "Cấu trúc: 'told + O + not to V' -> 'not to overcharge'."},
    {"id": "u11-g11", "question": "Mai said that she _____ virtual reality simulations in biology class since Monday.", "options": ["A. had been using", "B. has been using", "C. is using", "D. was using"], "correctAnswer": "A. had been using", "explanation": "Hiện tại hoàn thành tiếp diễn lùi thì thành Quá khứ hoàn thành tiếp diễn: 'had been using'."},
    {"id": "u11-g12", "question": "David asked me _____ I had ever tried an AI-powered voice recognition tool.", "options": ["A. whether", "B. that", "C. what", "D. whom"], "correctAnswer": "A. whether", "explanation": "Câu hỏi Yes/No tường thuật dùng 'whether' / 'if'."},
    {"id": "u11-g13", "question": "The principal announced that the school _____ free high-speed broadband Wi-Fi that semester.", "options": ["A. would provide", "B. will provide", "C. provides", "D. is providing"], "correctAnswer": "A. would provide", "explanation": "'will provide' lùi thì thành 'would provide', 'this semester' -> 'that semester'."},
    {"id": "u11-g14", "question": "Huy asked his friend why he _____ to join the digital literacy workshop.", "options": ["A. had refused", "B. has refused", "C. does refuse", "D. did refuse"], "correctAnswer": "A. had refused", "explanation": "Wh- question gián tiếp lùi thì: 'why he had refused'."},
    {"id": "u11-g15", "question": "She advised me _____ two-factor authentication to secure my social media accounts.", "options": ["A. to enable", "B. enabling", "C. enable", "D. enabled"], "correctAnswer": "A. to enable", "explanation": "Cấu trúc: 'advise + O + to V' -> 'advised me to enable'."},
    {"id": "u11-g16", "question": "They said that they _____ a computer programming competition at that moment.", "options": ["A. were participating in", "B. are participating in", "C. participate in", "D. had participated in"], "correctAnswer": "A. were participating in", "explanation": "'now / at the moment' -> 'then / at that moment', 'are participating' -> 'were participating in'."},
    {"id": "u11-g17", "question": "The cybersecurity officer warned us _____ suspicious email attachments from unknown senders.", "options": ["A. not to open", "B. to not open", "C. not opening", "D. don't open"], "correctAnswer": "A. not to open", "explanation": "Cấu trúc: 'warn + O + not to V' -> 'warned us not to open'."},
    {"id": "u11-g18", "question": "An asked Dr. Lam how artificial intelligence _____ medical diagnoses.", "options": ["A. improved", "B. does improve", "C. did improve", "D. improves"], "correctAnswer": "A. improved", "explanation": "Câu hỏi Wh- tường thuật: 'how artificial intelligence improved' (trật tự khẳng định lùi thì)."},
    {"id": "u11-g19", "question": "The teacher told the class that the earth _____ around the sun.", "options": ["A. revolves", "B. revolved", "C. had revolved", "D. was revolving"], "correctAnswer": "A. revolves", "explanation": "Sự thật hiển nhiên/chân lý khoa học không lùi thì, giữ nguyên Hiện tại đơn: 'revolves'."},
    {"id": "u11-g20", "question": "Bao asked me when the latest software update _____ available.", "options": ["A. would be", "B. will be", "C. is", "D. has been"], "correctAnswer": "A. would be", "explanation": "Lùi thì: 'when the latest software update would be available'."}
]

u11_listening_info = {
    "audioTitle": "Thiết Bị Điện Tử & Trí Tuệ Nhân Tạo Trong Giáo Dục Hiện Đại",
    "audioDuration": "3:25",
    "audioScriptSpeaker": "EdTech Specialist Ms. Emily & Student Duc",
    "transcriptText": "Duc: Ms. Emily, how are modern digital devices transforming secondary education today?\nMs. Emily: Hello Duc! Electronic devices—ranging from lightweight tablets to AI-powered learning platforms—are revolutionizing the way students acquire knowledge. Rather than memorizing static textbooks passively, learners can explore interactive 3D simulations, receive instant grammar feedback, and collaborate on shared cloud documents in real time.\nDuc: Does excessive reliance on electronic gadgets pose any serious drawbacks?\nMs. Emily: That is an essential consideration! Excessive screen time can strain eyesight, disrupt restorative sleep cycles, and cause social detachment. Furthermore, students must cultivate rigorous cybersecurity literacy and avoid digital distractions during dedicated study hours.\nDuc: What golden principle should students remember when utilizing technology for study?\nMs. Emily: Treat technology as a powerful intellectual amplifier, not as a replacement for critical thinking! Use smart devices purposefully to create, discover, and expand your mental horizons!",
    "vietnameseTranslation": "Đức: Thưa cô Emily, các thiết bị kỹ thuật số hiện đại đang làm thay đổi giáo dục cấp hai ngày nay như thế nào ạ?\nCô Emily: Chào Đức! Các thiết bị điện tử—từ máy tính bảng gọn nhẹ đến các nền tảng học tập ứng dụng AI—đang cách mạng hóa cách học sinh tiếp thu kiến thức. Thay vì học vẹt sách giáo khoa tĩnh một cách thụ động, các em có thể khám phá các mô phỏng 3D tương tác, nhận phản hồi ngữ pháp tức thì và cùng chỉnh sửa tài liệu đám mây theo thời gian thực.\nĐức: Liệu việc phụ thuộc quá mức vào các thiết bị điện tử có gây ra tác hại nghiêm trọng nào không ạ?\nCô Emily: Đó là một cân nhắc rất quan trọng! Thời gian sử dụng màn hình quá nhiều có thể làm mỏi mắt, rối loạn chu kỳ giấc ngủ phục hồi và gây ra sự xa cách xã hội. Hơn nữa, học sinh phải rèn luyện năng lực an ninh mạng chặt chẽ và tránh những xao nhãng kỹ thuật số trong giờ học tập trung.\nĐức: Nguyên tắc vàng nào học sinh nên ghi nhớ khi sử dụng công nghệ để học tập ạ?\nCô Emily: Hãy coi công nghệ như một bộ khuếch đại trí tuệ mạnh mẽ, chứ không phải là sự thay thế cho tư duy phản biện! Hãy sử dụng các thiết bị thông minh một cách có mục đích để sáng tạo, khám phá và mở rộng chân trời tri thức của em!"
}

u11_listening_qs = [
    {"id": "u11-l1", "question": "How are digital devices transforming education according to Ms. Emily?", "options": ["A. Enabling interactive 3D simulations, instant feedback, and real-time cloud collaboration", "B. Forcing all schools to close down", "C. Replacing all human teachers completely", "D. Banning all books forever"], "correctAnswerIndex": 0, "explanation": "Trong bài nghe: 'explore interactive 3D simulations, receive instant grammar feedback, and collaborate on shared cloud documents in real time.'"},
    {"id": "u11-l2", "question": "What potential drawbacks of excessive screen time are mentioned?", "options": ["A. Straining eyesight, disrupting sleep cycles, and causing social detachment", "B. Making ears grow larger", "C. Causing sudden tooth loss", "D. Turning hair green"], "correctAnswerIndex": 0, "explanation": "Trong bài nghe: 'strain eyesight, disrupt restorative sleep cycles, and cause social detachment.'"},
    {"id": "u11-l3", "question": "What kind of literacy must students cultivate when using technology?", "options": ["A. Rigorous cybersecurity literacy", "B. Antique painting literacy", "C. Medieval Latin translation", "D. Car racing literacy"], "correctAnswerIndex": 0, "explanation": "Trong bài nghe: 'students must cultivate rigorous cybersecurity literacy.'"},
    {"id": "u11-l4", "question": "What should students avoid during dedicated study hours?", "options": ["A. Digital distractions", "B. Drinking fresh water", "C. Breathing fresh air", "D. Reading good books"], "correctAnswerIndex": 0, "explanation": "Trong bài nghe: 'and avoid digital distractions during dedicated study hours.'"},
    {"id": "u11-l5", "question": "How does Ms. Emily describe technology's ideal role?", "options": ["A. A powerful intellectual amplifier, not a replacement for critical thinking", "B. A lazy shortcut to avoid thinking", "C. A complete replacement for human brains", "D. A useless toy"], "correctAnswerIndex": 0, "explanation": "Trong bài nghe: 'Treat technology as a powerful intellectual amplifier, not as a replacement for critical thinking!'"},
    {"id": "u11-l6", "question": "What purpose should guide students when using smart devices?", "options": ["A. Using them purposefully to create, discover, and expand mental horizons", "B. Playing endless video games all night", "C. Staring blankly at screens", "D. Copying other people's homework blindly"], "correctAnswerIndex": 0, "explanation": "Trong bài nghe: 'Use smart devices purposefully to create, discover, and expand your mental horizons!'"},
    {"id": "u11-l7", "question": "What benefit does cloud computing bring to students?", "options": ["A. Collaborating on shared documents in real time", "B. Making rain fall from the ceiling", "C. Printing money at home", "D. Deleting all school records"], "correctAnswerIndex": 0, "explanation": "Trong bài nghe: 'collaborate on shared cloud documents in real time.'"},
    {"id": "u11-l8", "question": "What is the overall tone of Ms. Emily regarding technology in learning?", "options": ["A. Balanced, constructive, and forward-looking", "B. Angry and hostile toward computers", "C. Unrealistic and completely careless", "D. Bored and unhelpful"], "correctAnswerIndex": 0, "explanation": "Cô Emily thể hiện góc nhìn cân bằng, mang tính xây dựng và hướng tới tương lai."}
]

u11_listening_fibs = [
    {"id": "u11-f1", "sentenceWithBlank": "Smart devices provide instant _____ on grammar and exercises.", "correctWord": "feedback", "hint": "Phản hồi (feedback)"},
    {"id": "u11-f2", "sentenceWithBlank": "Excessive screen time disrupts restorative _____ cycles.", "correctWord": "sleep", "hint": "Giấc ngủ (sleep cycles)"},
    {"id": "u11-f3", "sentenceWithBlank": "Students must cultivate rigorous _____ literacy.", "correctWord": "cybersecurity", "hint": "An ninh mạng (cybersecurity)"},
    {"id": "u11-f4", "sentenceWithBlank": "Technology is a powerful _____ amplifier.", "correctWord": "intellectual", "hint": "Thuộc về trí tuệ (intellectual)"}
]

u11_speaking = [
    {"id": f"u11-s{i+1}", "targetSentence": s, "ipa": ipa, "vietnameseMeaning": vm, "contextSituation": ctx, "keyPhonicsFocus": kpf, "sampleAudioText": s}
    for i, (s, ipa, vm, ctx, kpf) in enumerate([
        ("Modern electronic devices have transformed conventional classrooms into dynamic, interactive digital learning hubs.", "/ˈmɒdən ɪlɛkˈtrɒnɪk dɪˈvaɪsɪz hæv trænsˈfɔːmd kənˈvɛnʃənl ˈklɑːsrʊmz ˈɪntuː daɪˈnæmɪk ˌɪntərˈæktɪv ˈdɪʤɪtl ˈlɜːnɪŋ hʌbz/", "Các thiết bị điện tử hiện đại đã biến các lớp học truyền thống thành các trung tâm học tập kỹ thuật số tương tác, năng động.", "Thuyết trình về ứng dụng công nghệ trong lớp học.", "Phát âm chuẩn 'interactive digital learning hubs'."),
        ("The teacher told us that artificial intelligence algorithms could customize individualized learning exercises.", "/ðə ˈtiːʧə təʊld ʌs ðæt ˌɑːtɪˈfɪʃəl ɪnˈtɛlɪʤəns ˈælɡərɪðmz kʊd ˈkʌstəmaɪz ˌɪndɪˈvɪdjʊəlaɪzd ˈlɜːnɪŋ ˈɛksəsaɪzɪz/", "Cô giáo nói với chúng tôi rằng các thuật toán trí tuệ nhân tạo có thể tùy chỉnh các bài tập học tập cá nhân hóa.", "Tường thuật lời giáo viên về AI trong giáo dục.", "Phát âm chuẩn 'artificial intelligence algorithms' /ˈælɡərɪðmz/."),
        ("Minh asked his classmate whether she had backed up her term assignment on the secure cloud storage drive.", "/mɪn ɑːskt hɪz ˈklɑːsmeɪt ˈwɛðə ʃiː hæd bækt ʌp hɜː tɜːm əˈsaɪnmənt ɒn ðə sɪˈkjʊə klaʊd ˈstɔːrɪʤ draɪv/", "Minh hỏi bạn cùng lớp xem bạn ấy đã sao lưu bài tập học kỳ lên ổ lưu trữ đám mây an toàn chưa.", "Tường thuật câu hỏi Yes/No về sao lưu dữ liệu.", "Phát âm chuẩn 'cloud storage drive' và 'backed up'."),
        ("Practicing robust cybersecurity habits protects our personal privacy and confidential accounts from malicious hackers.", "/ˈpræktɪsɪŋ rəʊˈbʌst ˌsaɪbəsɪˈkjʊərɪti ˈhæbɪts prəˈtɛkts ˈaʊə ˈpɜːsnl ˈprɪvəsi ænd ˌkɒnfɪˈdɛnʃəl əˈkaʊnts frɒm məˈlɪʃəs ˈhækəz/", "Thực hành thói quen an ninh mạng vững chắc bảo vệ quyền riêng tư cá nhân và các tài khoản bảo mật của chúng ta khỏi tin tặc độc hại.", "Tuyên truyền về an ninh mạng.", "Phát âm chuẩn 'robust cybersecurity' và 'malicious hackers' /məˈlɪʃəs ˈhækəz/."),
        ("Augmented reality software applications allow biology students to examine detailed 3D anatomical structures.", "/ɔːɡˈmɛntɪd riˈælɪti ˈsɒftweər ˌæplɪˈkeɪʃənz əˈlaʊ baɪˈɒləʤi ˈstjuːdənts tuː ɪɡˈzæmɪn ˈdiːteɪld θriː-diː ˌænəˈtɒmɪkəl ˈstrʌkʧəz/", "Các ứng dụng phần mềm thực tế tăng cường cho phép học sinh sinh học kiểm tra chi tiết các cấu trúc giải phẫu 3D.", "Nói về ứng dụng AR trong môn Sinh học.", "Phát âm chuẩn 'augmented reality' và 'anatomical structures' /ˌænəˈtɒmɪkəl ˈstrʌkʧəz/."),
        ("The instructor advised us not to spend excessive recreational screen time before going to sleep.", "/ði ɪnˈstrʌktər ədˈvaɪzd ʌs nɒt tuː spɛnd ɪkˈsɛsɪv ˌrɛkrɪˈeɪʃənl skriːn taɪm bɪˈfɔː ˈɡəʊɪŋ tuː sliːp/", "Người hướng dẫn đã khuyên chúng tôi không nên dành quá nhiều thời gian dùng màn hình giải trí trước khi đi ngủ.", "Tường thuật lời khuyên về screen time.", "Phát âm chuẩn 'excessive recreational screen time'."),
        ("Voice recognition technology integrated into English learning apps evaluates pronunciation accuracy in real time.", "/vɔɪs ˌrɛkəɡˈnɪʃən tɛkˈnɒləʤi ˈɪntɪɡreɪtɪd ˈɪntuː ˈɪŋɡlɪʃ ˈlɜːnɪŋ æps ɪˈvæljʊeɪts prəˌnʌnsɪˈeɪʃən ˈækjʊrəsi ɪn rɪəl taɪm/", "Công nghệ nhận dạng giọng nói tích hợp trong các ứng dụng học tiếng Anh đánh giá độ chính xác phát âm theo thời gian thực.", "Nói về app luyện phát âm AI.", "Phát âm chuẩn 'voice recognition' và 'pronunciation accuracy'."),
        ("Our group utilized interactive touchscreen smartboards to deliver a captivating presentation on solar energy.", "/ˈaʊə ɡruːp ˈjuːtɪlaɪzd ˌɪntərˈæktɪv ˈtʌʧskriːn ˈsmɑːtbɔːdz tuː dɪˈlɪvər ə ˈkæptɪveɪtɪŋ ˌprɛznˈteɪʃən ɒn ˈsəʊlə ˈɛnəʤi/", "Nhóm chúng tôi đã sử dụng bảng thông minh màn hình cảm ứng tương tác để thực hiện một bài thuyết trình lôi cuốn về năng lượng mặt trời.", "Kể về buổi thuyết trình nhóm.", "Phát âm chuẩn 'touchscreen smartboards' và 'captivating presentation'."),
        ("She asked me how long the rechargeable battery of my new high-performance laptop lasted.", "/ʃiː ɑːskt miː haʊ lɒŋ ðə riːˈʧɑːʤəbl ˈbætəri ɒv maɪ njuː haɪ-pəˈfɔːməns ˈlæpˌtɒp ˈlɑːstɪd/", "Cô ấy hỏi tôi pin sạc của chiếc máy tính xách tay hiệu năng cao mới của tôi dùng được trong bao lâu.", "Tường thuật câu hỏi Wh- về thời lượng pin.", "Phát âm chuẩn 'rechargeable battery' /riːˈʧɑːʤəbl ˈbætəri/."),
        ("Digital literacy empowers young learners to distinguish between factual scientific data and misleading rumors.", "/ˈdɪʤɪtl ˈlɪtərəsi ɪmˈpaʊəz jʌŋ ˈlɜːnəz tuː dɪsˈtɪŋɡwɪʃ bɪˈtwiːn ˈfæktʃʊəl ˌsaɪənˈtɪfɪk ˈdeɪtə ænd mɪsˈliːdɪŋ ˈruːməz/", "Năng lực số giúp người học trẻ phân biệt giữa dữ liệu khoa học thực tế và các tin đồn sai lệch.", "Nói về tầm quan trọng của tư duy số.", "Phát âm chuẩn 'digital literacy' /ˈdɪʤɪtl ˈlɪtərəsi/ và 'factual data'."),
        ("Smart wearable gadgets seamlessly monitor physical fitness metrics, daily footsteps, and cardiovascular health.", "/smɑːt ˈweərəbl ˈɡæʤɪts ˈsiːmlɪsli ˈmɒnɪtə ˈfɪzɪkəl ˈfɪtnɪs ˈmɛtrɪks ˈdeɪli ˈfʊtstɛps ænd ˌkɑːdɪəʊˈvæskjʊlə hɛlθ/", "Các thiết bị đeo thông minh theo dõi liền mạch các chỉ số thể chất, số bước chân hàng ngày và sức khỏe tim mạch.", "Giới thiệu thiết bị đeo thông minh.", "Phát âm chuẩn 'wearable gadgets' và 'cardiovascular health' /ˌkɑːdɪəʊˈvæskjʊlə hɛlθ/."),
        ("The IT specialist warned us that unencrypted public Wi-Fi networks were vulnerable to data interception.", "/ði aɪ-tiː ˈspɛʃəlɪst wɔːnd ʌs ðæt ʌnɪnˈkrɪptɪd ˈpʌblɪk waɪ-faɪ ˈnɛtwɜːks wɜː ˈvʌlnərəbl tuː ˈdeɪtə ˌɪntəˈsɛpʃən/", "Chuyên gia CNTT cảnh báo chúng tôi rằng các mạng Wi-Fi công cộng không mã hóa rất dễ bị đánh cắp dữ liệu.", "Tường thuật cảnh báo an ninh mạng.", "Phát âm chuẩn 'unencrypted' /ʌnɪnˈkrɪptɪd/ và 'vulnerable' /ˈvʌlnərəbl/."),
        ("Cloud computing allows international research teams to collaborate effortlessly without geographic boundaries.", "/klaʊd kəmˈpjuːtɪŋ əˈlaʊz ˌɪntəˈnæʃənl rɪˈsɜːʧ tiːmz tuː kəˈlæbəreɪt ˈɛfətlɪsli wɪˈðaʊt ˌʤiːəˈɡræfɪk ˈbaʊndəriz/", "Điện toán đám mây cho phép các nhóm nghiên cứu quốc tế cộng tác dễ dàng mà không bị giới hạn bởi ranh giới địa lý.", "Nói về lợi ích của Cloud.", "Phát âm chuẩn 'collaborate effortlessly' và 'geographic boundaries'."),
        ("He explained that semiconductor microchips were the fundamental building blocks of modern technological innovation.", "/hiː ɪksˈpleɪnd ðæt ˌsɛmɪkənˈdʌktə ˈmaɪkrəʊˌʧɪps wɜː ðə ˌfʌndəˈmɛntl ˈbɪldɪŋ blɒks ɒv ˈmɒdən ˌtɛknəˈlɒʤɪkəl ˌɪnəʊˈveɪʃən/", "Anh ấy giải thích rằng các vi mạch bán dẫn là nền tảng cơ bản của sự đổi mới công nghệ hiện đại.", "Tường thuật bài học về chất bán dẫn.", "Phát âm chuẩn 'semiconductor microchips' /ˌsɛmɪkənˈdʌktə ˈmaɪkrəʊˌʧɪps/."),
        ("Students must learn to manage digital screen time effectively to maintain academic excellence and physical vitality.", "/ˈstjuːdənts mʌst lɜːn tuː ˈmænɪʤ ˈdɪʤɪtl skriːn taɪm ɪˈfɛktɪvli tuː meɪnˈteɪn ˌækəˈdɛmɪk ˈɛksələns ænd ˈfɪzɪkəl vaɪˈtælɪti/", "Học sinh phải học cách quản lý thời gian sử dụng màn hình kỹ thuật số hiệu quả để duy trì thành tích học tập và thể lực sung mãn.", "Khuyên cân bằng screen time.", "Phát âm chuẩn 'physical vitality' /vaɪˈtælɪti/."),
        ("The principal reminded everyone to charge their learning tablets fully before the interactive digital exam.", "/ðə ˈprɪnsəpl rɪˈmaɪndɪd ˈɛvrɪwʌn tuː ʧɑːʤ ðeə ˈlɜːnɪŋ ˈtæblɪts ˈfʊli bɪˈfɔː ði ˌɪntərˈæktɪv ˈdɪʤɪtl ɪɡˈzæm/", "Thầy hiệu trưởng nhắc nhở mọi người sạc đầy pin máy tính bảng học tập trước kỳ thi kỹ thuật số tương tác.", "Tường thuật lời nhắc nhở của hiệu trưởng.", "Phát âm chuẩn 'reminded everyone to charge'."),
        ("Quantum computing breakthroughs will revolutionize complex data analysis, weather forecasting, and cryptographic security.", "/ˈkwɒntəm kəmˈpjuːtɪŋ ˈbreɪkθruːz wɪl ˌrɛvəˈluːʃnaɪz ˈkɒmplɛks ˈdeɪtə əˈnæləsɪs ˈwɛðə ˈfɔːkɑːstɪŋ ænd ˌkrɪptəˈɡræfɪk sɪˈkjʊərɪti/", "Những bước đột phá về điện toán lượng tử sẽ cách mạng hóa việc phân tích dữ liệu phức tạp, dự báo thời tiết và bảo mật mật mã.", "Nói về tương lai điện toán lượng tử.", "Phát âm chuẩn 'quantum computing breakthroughs' /ˈkwɒntəm kəmˈpjuːtɪŋ ˈbreɪkθruːz/."),
        ("Technology is an extraordinary servant when guided by human wisdom, ethics, and compassion.", "/tɛkˈnɒləʤi ɪz ən ɪksˈtrɔːdnri ˈsɜːvənt wɛn ˈɡaɪdɪd baɪ ˈhjuːmən ˈwɪzdəm ˈɛθɪks ænd kəmˈpæʃən/", "Công nghệ là một người đầy tớ phi thường khi được dẫn dắt bởi trí tuệ, đạo đức và lòng trắc ẩn của con người.", "Triết lý về công nghệ và con người.", "Phát âm chuẩn 'human wisdom, ethics, and compassion'."),
        ("May digital innovation open sparkling portals of discovery and lifelong enlightenment for every young scholar.", "/meɪ ˈdɪʤɪtl ˌɪnəʊˈveɪʃən ˈəʊpən ˈspɑːklɪŋ ˈpɔːtlz ɒv dɪsˈkʌvəri ænd ˈlaɪflɒŋ ɪnˈlaɪtnmənt fɔːr ˈɛvri jʌŋ ˈskɒlə/", "Chúc cho đổi mới kỹ thuật số sẽ mở ra những cánh cổng khám phá lấp lánh và sự khai sáng trọn đời cho mỗi học giả trẻ.", "Lời chúc về học tập thời đại số.", "Phát âm chuẩn 'sparkling portals of discovery'."),
        ("Let us harness electronic devices with purpose, mindfulness, and integrity to enrich the human experience.", "/lɛt ʌs ˈhɑːnɪs ɪlɛkˈtrɒnɪk dɪˈvaɪsɪz wɪð ˈpɜːpəs ˈmaɪndfʊlnɪs ænd ɪnˈtɛɡrɪti tuː ɪnˈrɪʧ ðə ˈhjuːmən ɪksˈpɪərɪəns/", "Chúng ta hãy cùng làm chủ các thiết bị điện tử với mục đích, sự tỉnh thức và sự chính trực để làm phong phú trải nghiệm của nhân loại.", "Thông điệp kết thúc về công nghệ số.", "Phát âm chuẩn 'purpose, mindfulness, and integrity'.")
    ])
]

u11_reading_info = {
    "title": "Cuộc Cách Mạng Kỹ Thuật Số Trong Giáo Dục: Tiềm Năng & Trách Nhiệm",
    "topic": "Ứng dụng thiết bị điện tử, trí tuệ nhân tạo, nền tảng đám mây và kỹ năng công dân số trong thời đại mới",
    "passageText": "The rapid advancement of microchip computing, artificial intelligence, and broadband connectivity has profoundly restructured the educational paradigm. Digital devices—including high-resolution tablets, smart interactive whiteboards, and immersive virtual reality headsets—have converted traditional classrooms into vibrant ecosystems of active discovery. Instead of remaining passive recipients of static textbook lectures, students can now dissect 3D biological organisms, tour remote cultural heritage sites virtually, and conduct simulated scientific experiments with unprecedented realism.\n\nFurthermore, artificial intelligence algorithms embedded within modern e-learning platforms deliver tailored adaptive learning pathways. By diagnosing individual learning paces, strengths, and conceptual gaps in real time, intelligent software generates customized remediation exercises and instant phonetic feedback. Meanwhile, cloud computing enables seamless peer collaboration on group projects across vast geographical boundaries, cultivating indispensable 21st-century teamwork skills.\n\nNonetheless, educational technologists emphasize that this technological revolution demands disciplined digital citizenship. Excessive, unregulated screen time has been empirically linked to visual strain, sleep architecture disruption, and reduced attention spans. Moreover, the pervasive nature of online networks necessitates robust cybersecurity literacy to prevent identity exploitation and algorithmic distraction. Ultimately, electronic devices must never be regarded as autonomous replacements for human mentorship or critical thinking, but rather as powerful cognitive catalysts that elevate human intellectual potential.",
    "keyVocabularyHighlights": [
        {"word": "educational paradigm", "meaning": "mô hình / khuôn khổ phương pháp luận giáo dục"},
        {"word": "adaptive learning pathways", "meaning": "lộ trình học tập thích ứng cá nhân hóa theo trình độ"},
        {"word": "digital citizenship", "meaning": "tinh thần và trách nhiệm của công dân số"},
        {"word": "cognitive catalysts", "meaning": "chất xúc tác thúc đẩy năng lực tư duy nhận thức"}
    ]
}

u11_reading_qs = [
    {"id": "u11-r1", "question": "What technological elements have restructured the educational paradigm according to paragraph 1?", "options": ["A. Microchip computing, artificial intelligence, and broadband connectivity", "B. Steam engines and coal railways", "C. Printing presses from the 15th century", "D. Chalk and blackboards only"], "correctAnswerIndex": 0, "explanation": "Trong đoạn 1: 'The rapid advancement of microchip computing, artificial intelligence, and broadband connectivity has profoundly restructured the educational paradigm.'"},
    {"id": "u11-r2", "question": "What can students now do with modern digital devices in classrooms?", "options": ["A. Dissect 3D biological organisms, tour heritage sites virtually, and run simulated experiments", "B. Sleep through all classes", "C. Play video games without thinking", "D. Throw away all books"], "correctAnswerIndex": 0, "explanation": "Trong đoạn 1: 'dissect 3D biological organisms, tour remote cultural heritage sites virtually, and conduct simulated scientific experiments...'"},
    {"id": "u11-r3", "question": "How do AI algorithms embedded in e-learning platforms assist learners in paragraph 2?", "options": ["A. Deliver tailored adaptive pathways, diagnose learning gaps, and generate customized feedback", "B. Do all homework for students automatically so they do not learn", "C. Erase all student grades", "D. Lock computer screens permanently"], "correctAnswerIndex": 0, "explanation": "Trong đoạn 2: 'deliver tailored adaptive learning pathways. By diagnosing individual learning paces, strengths, and conceptual gaps in real time...'"},
    {"id": "u11-r4", "question": "What 21st-century skill is cultivated through cloud computing collaboration?", "options": ["A. Indispensable teamwork and peer collaboration skills", "B. Solo gaming skills", "C. Memorizing silent phone numbers", "D. Fast typing of slang only"], "correctAnswerIndex": 0, "explanation": "Trong đoạn 2: 'enables seamless peer collaboration... cultivating indispensable 21st-century teamwork skills.'"},
    {"id": "u11-r5", "question": "What negative consequences are empirically linked to excessive screen time?", "options": ["A. Visual strain, sleep architecture disruption, and reduced attention spans", "B. Gaining superhuman strength", "C. Glowing in the dark", "D. Growing wings"], "correctAnswerIndex": 0, "explanation": "Trong đoạn 3: 'linked to visual strain, sleep architecture disruption, and reduced attention spans.'"},
    {"id": "u11-r6", "question": "Why is robust cybersecurity literacy necessary according to paragraph 3?", "options": ["A. To prevent identity exploitation and algorithmic distraction", "B. To learn how to hack government systems", "C. To sell stolen passwords", "D. To build hardware chips"], "correctAnswerIndex": 0, "explanation": "Trong đoạn 3: 'necessitates robust cybersecurity literacy to prevent identity exploitation and algorithmic distraction.'"},
    {"id": "u11-r7", "question": "How should electronic devices ultimately be regarded at the end of the text?", "options": ["A. As powerful cognitive catalysts that elevate human intellectual potential", "B. As autonomous replacements for teachers", "C. As evil machines that must be destroyed", "D. As simple expensive toys"], "correctAnswerIndex": 0, "explanation": "Trong đoạn 3: 'not rather as autonomous replacements... but rather as powerful cognitive catalysts that elevate human intellectual potential.'"},
    {"id": "u11-r8", "question": "Which word in paragraph 2 is closest in meaning to 'remediation'?", "options": ["A. Correction, improvement, or rectifying academic weaknesses", "B. Entertainment and dance", "C. Heavy punishment", "D. Total destruction"], "correctAnswerIndex": 0, "explanation": "'Remediation' có nghĩa là sự khắc phục, bổ trợ cải thiện các lỗ hổng kiến thức."},
    {"id": "u11-r9", "question": "Which word in paragraph 3 is closest in meaning to 'pervasive'?", "options": ["A. Widespread, prevalent, and present everywhere", "B. Rare and hidden", "C. Broken and useless", "D. Dangerously sharp"], "correctAnswerIndex": 0, "explanation": "'Pervasive' có nghĩa là lan tỏa khắp nơi, hiện diện ở mọi ngóc ngách."},
    {"id": "u11-r10", "question": "What is the primary message of the author in this passage?", "options": ["A. Technology offers immense educational power when guided by disciplined digital citizenship", "B. All digital devices should be banned from schools", "C. Computers should replace all teachers by tomorrow", "D. Students should spend 18 hours daily on social media"], "correctAnswerIndex": 0, "explanation": "Thông điệp chính là công nghệ mang lại tiềm năng giáo dục khổng lồ khi đi đôi với tinh thần công dân số có kỷ luật."}
]

u11_writing_prompts = [
    {
        "id": "u11-w1",
        "title": "Đề 1: Write a paragraph on the advantages of using tablets for learning (60-80 words)",
        "description": "Viết một đoạn văn trình bày những lợi ích vượt trội của việc sử dụng máy tính bảng trong học tập.",
        "suggestedOutline": [
            "Introduction: State that tablets have become indispensable digital tools for modern students.",
            "Body: Explain advantages (portability of thousands of e-books, accessing interactive learning apps, facilitating note-taking).",
            "Conclusion: Affirm that tablets significantly boost study productivity."
        ],
        "usefulPhrases": [
            "Tablets have emerged as extraordinarily versatile digital learning tools for secondary students...",
            "First, a single lightweight tablet can store hundreds of digital textbooks and scientific journals...",
            "Second, interactive learning applications with 3D simulations make complex concepts vivid and easy to grasp...",
            "Using tablets purposefully enhances study efficiency and keeps students organized."
        ],
        "wordLimit": "60 - 80 từ",
        "sampleGrade10Response": "Tablets have emerged as extraordinarily versatile digital tools for secondary students. First, a single lightweight tablet can store hundreds of digitized textbooks, eliminating heavy backpacks. Second, interactive educational applications with 3D models and audio guides make complex scientific concepts vivid and engaging. Furthermore, students can easily organize digital notes, complete online quizzes, and collaborate with peers on shared documents. When used purposefully, tablets significantly enhance learning productivity and academic success."
    },
    {
        "id": "u11-w2",
        "title": "Đề 2: Write a paragraph about the dangers of excessive screen time (60-80 words)",
        "description": "Viết một đoạn văn cảnh báo những nguy cơ tiềm ẩn của việc sử dụng thiết bị điện tử quá nhiều giờ mỗi ngày.",
        "suggestedOutline": [
            "Introduction: State that excessive screen time poses severe physical and psychological hazards.",
            "Body: Detail dangers (eye strain and headaches, sleep cycle disruption from blue light, reduced face-to-face social skills).",
            "Conclusion: Urge students to balance screen time with outdoor physical activities."
        ],
        "usefulPhrases": [
            "Excessive recreational screen time poses grave physical and psychological risks to teenagers...",
            "Prolonged exposure to digital displays triggers severe digital eye strain, chronic headaches, and postural back pain...",
            "Furthermore, artificial blue light emitted by screens suppresses melatonin, disrupting deep restorative sleep...",
            "Balancing screen hours with outdoor sports is essential for maintaining physical vitality."
        ],
        "wordLimit": "60 - 80 từ",
        "sampleGrade10Response": "Excessive recreational screen time poses severe physical and mental risks to teenagers. Staring at digital screens for prolonged hours causes painful eye fatigue, chronic headaches, and poor posture. Furthermore, the artificial blue light emitted by smartphones disrupts nighttime melatonin production, leading to insomnia and daytime exhaustion. Spending too much time in virtual worlds also causes social detachment. Students must set strict screen limits and engage in outdoor sports to maintain vitality."
    },
    {
        "id": "u11-w3",
        "title": "Đề 3: Write a paragraph giving advice on how to stay safe online (60-80 words)",
        "description": "Viết một đoạn văn đưa ra lời khuyên thiết thực giúp học sinh bảo đảm an toàn trên không gian mạng.",
        "suggestedOutline": [
            "Introduction: State that practicing strong cybersecurity is vital in today's connected world.",
            "Body: Give tips (creating complex encrypted passwords, never clicking suspicious links, avoiding sharing private addresses/phone numbers).",
            "Conclusion: Encourage students to be vigilant digital citizens."
        ],
        "usefulPhrases": [
            "Practicing robust cybersecurity habits is essential to safeguarding personal privacy online...",
            "First, students should always create strong passwords combining symbols and enable two-factor authentication...",
            "Second, never click on suspicious hyperlinks or download unverified attachments from unknown senders...",
            "Remaining vigilant empowers us to navigate the internet safely and confidently."
        ],
        "wordLimit": "60 - 80 từ",
        "sampleGrade10Response": "Practicing robust cybersecurity habits is essential to safeguarding personal privacy in the digital age. First, students should create complex passwords combining numbers, letters, and symbols, while enabling two-factor authentication. Second, never click on suspicious links or download unverified email attachments from strangers. Most importantly, avoid sharing sensitive personal details like home addresses or bank numbers on public social media. Staying vigilant allows us to enjoy technology safely without falling prey to cyber scams."
    },
    {
        "id": "u11-w4",
        "title": "Đề 4: Write a paragraph on how AI can help students learn English (60-80 words)",
        "description": "Viết một đoạn văn phân tích cách trí tuệ nhân tạo (AI) hỗ trợ học sinh học tiếng Anh hiệu quả.",
        "suggestedOutline": [
            "Introduction: State that AI tools are revolutionizing English language acquisition.",
            "Body: Detail applications (voice recognition giving instant IPA pronunciation feedback, AI chat tutors for conversational practice, automated grammar checks).",
            "Conclusion: Emphasize using AI as an interactive smart study tutor."
        ],
        "usefulPhrases": [
            "Artificial intelligence is revolutionizing the way students practice and master English...",
            "AI-powered speech recognition applications provide instant feedback on IPA pronunciation accuracy and sentence intonation...",
            "Additionally, intelligent chatbots offer safe, non-judgmental conversational practice anytime, anywhere...",
            "Leveraging AI tools transforms English learning into an interactive, personalized experience."
        ],
        "wordLimit": "60 - 80 từ",
        "sampleGrade10Response": "Artificial intelligence is revolutionizing the way students master the English language. AI-powered voice recognition apps provide instant, objective feedback on phonetic accuracy, helping learners correct pronunciation errors immediately. Furthermore, intelligent conversational tutors allow students to practice speaking in diverse realistic scenarios without feeling embarrassed about making mistakes. AI also personalizes grammar revision exercises based on individual weaknesses. Utilizing AI smartly accelerates English fluency dramatically."
    },
    {
        "id": "u11-w5",
        "title": "Đề 5: Write a paragraph proposing a school policy for mobile phone use (60-80 words)",
        "description": "Viết một đoạn văn đề xuất một quy định hợp lý về việc sử dụng điện thoại di động tại trường học.",
        "suggestedOutline": [
            "Introduction: Propose a balanced mobile phone policy for secondary schools.",
            "Body: Outline rules (keeping phones silent in bags during lectures unless permitted by teachers for research, allowing phone use during breaks for contacting parents).",
            "Conclusion: State that this policy fosters classroom focus while maintaining digital benefits."
        ],
        "usefulPhrases": [
            "I propose a balanced and constructive school policy regarding mobile phone usage...",
            "Students should keep smartphones switched to silent mode inside backpacks during regular class periods...",
            "However, teachers may authorize phone use for interactive online quizzes or digital classroom research...",
            "This sensible policy preserves academic concentration while harnessing technology's educational value."
        ],
        "wordLimit": "60 - 80 từ",
        "sampleGrade10Response": "I propose a balanced school policy regarding mobile phone usage to ensure academic focus. Students should keep their smartphones on silent mode inside backpacks during regular classroom lectures to prevent distractions. However, teachers should be permitted to authorize phone use for interactive educational quizzes or online dictionary lookups. During lunch breaks, students can check urgent messages from parents. This sensible regulation fosters classroom discipline while leveraging digital benefits when appropriate."
    }
]

unit11 = make_unit(11, "Unit 11: Electronic Devices", "Thiết bị điện tử & Trí tuệ nhân tạo", "Khám phá công nghệ số, trí tuệ nhân tạo (AI), thực tế ảo (VR), an ninh mạng, Câu tường thuật (Reported Speech: Statements, Questions, Commands).", "Ngữ âm: Quy tắc lùi thì, biến đổi trạng từ và ngữ điệu câu hỏi tường thuật", "Laptop", u11_vocab, u11_grammar_info, u11_grammar_exs, u11_listening_info, u11_listening_qs, u11_listening_fibs, u11_speaking, u11_reading_info, u11_reading_qs, u11_writing_prompts)
write_ts_unit(11, unit11)
print("Unit 11 generated successfully!")

# ==============================================================================
# UNIT 12: CAREER CHOICES & JOBS OF THE FUTURE (20 Vocab, 20 Grammar, 8 Listening MC + 4 FIB, 20 Speaking, 10 Reading, 5 Writing)
# ==============================================================================
u12_vocab = [
    {"id": "u12-v1", "word": "career orientation", "phonetic": "/kəˈrɪər ˌɔːriɛnˈteɪʃən/", "partOfSpeech": "noun", "vietnameseMeaning": "định hướng nghề nghiệp", "englishExample": "Comprehensive career orientation programs help grade 9 students identify their strengths and passion.", "vietnameseExample": "Các chương trình định hướng nghề nghiệp toàn diện giúp học sinh lớp 9 xác định thế mạnh và đam mê của mình."},
    {"id": "u12-v2", "word": "vocational training", "phonetic": "/vəʊˈkeɪʃənl ˈtreɪnɪŋ/", "partOfSpeech": "noun", "vietnameseMeaning": "đào tạo nghề thực hành chuyên sâu", "englishExample": "Vocational training colleges equip youth with high-demand practical technical skills.", "vietnameseExample": "Các trường cao đẳng đào tạo nghề trang bị cho thanh niên những kỹ năng kỹ thuật thực hành có nhu cầu tuyển dụng cao."},
    {"id": "u12-v3", "word": "job satisfaction", "phonetic": "/ʤɒb ˌsætɪsˈfækʃən/", "partOfSpeech": "noun", "vietnameseMeaning": "sự hài lòng và thỏa mãn trong công việc", "englishExample": "High job satisfaction stems from meaningful work, supportive colleagues, and fair recognition.", "vietnameseExample": "Sự hài lòng cao trong công việc bắt nguồn từ công việc có ý nghĩa, đồng nghiệp hỗ trợ và sự ghi nhận công bằng."},
    {"id": "u12-v4", "word": "data scientist", "phonetic": "/ˈdeɪtə ˈsaɪəntɪst/", "partOfSpeech": "noun", "vietnameseMeaning": "nhà khoa học dữ liệu", "englishExample": "A data scientist analyzes massive information datasets to forecast technological trends.", "vietnameseExample": "Một nhà khoa học dữ liệu phân tích các tập dữ liệu thông tin khổng lồ để dự báo các xu hướng công nghệ."},
    {"id": "u12-v5", "word": "soft skills", "phonetic": "/sɒft skɪlz/", "partOfSpeech": "noun", "vietnameseMeaning": "kỹ năng mềm (giao tiếp, làm việc nhóm, quản lý thời gian)", "englishExample": "Employers value essential soft skills such as empathetic communication and crisis leadership.", "vietnameseExample": "Các nhà tuyển dụng đánh giá cao những kỹ năng mềm thiết yếu như giao tiếp thấu cảm và năng lực lãnh đạo xử lý khủng hoảng."},
    {"id": "u12-v6", "word": "internship", "phonetic": "/ˈɪntɜːnʃɪp/", "partOfSpeech": "noun", "vietnameseMeaning": "kỳ thực tập trải nghiệm nghề nghiệp", "englishExample": "Completing a summer internship at a software firm provides invaluable real-world experience.", "vietnameseExample": "Hoàn thành một kỳ thực tập mùa hè tại công ty phần mềm mang lại trải nghiệm thực tế vô giá."},
    {"id": "u12-v7", "word": "entrepreneurship", "phonetic": "/ˌɒntrəprəˈnɜːʃɪp/", "partOfSpeech": "noun", "vietnameseMeaning": "tinh thần khởi nghiệp kinh doanh", "englishExample": "Youth entrepreneurship programs nurture innovative business ideas and resilient problem-solving.", "vietnameseExample": "Các chương trình khởi nghiệp cho giới trẻ nuôi dưỡng những ý tưởng kinh doanh sáng tạo và tinh thần giải quyết vấn đề kiên cường."},
    {"id": "u12-v8", "word": "remote working", "phonetic": "/rɪˈməʊt ˈwɜːkɪŋ/", "partOfSpeech": "noun", "vietnameseMeaning": "làm việc từ xa (qua mạng)", "englishExample": "Remote working offers flexible scheduling while requiring high personal self-discipline.", "vietnameseExample": "Làm việc từ xa mang lại thời gian biểu linh hoạt đồng thời đòi hỏi tính tự giác cá nhân rất cao."},
    {"id": "u12-v9", "word": "artificial intelligence specialist", "phonetic": "/ˌɑːtɪˈfɪʃəl ɪnˈtɛlɪʤəns ˈspɛʃəlɪst/", "partOfSpeech": "noun", "vietnameseMeaning": "chuyên gia trí tuệ nhân tạo", "englishExample": "An artificial intelligence specialist develops autonomous machine learning models for healthcare.", "vietnameseExample": "Một chuyên gia trí tuệ nhân tạo phát triển các mô hình máy học tự hành phục vụ ngành y tế."},
    {"id": "u12-v10", "word": "job autonomy", "phonetic": "/ʤɒb ɔːˈtɒnəmi/", "partOfSpeech": "noun", "vietnameseMeaning": "quyền tự chủ và tự quyết trong công việc", "englishExample": "High job autonomy allows creative designers to experiment with groundbreaking visual concepts.", "vietnameseExample": "Quyền tự chủ cao trong công việc cho phép các nhà thiết kế sáng tạo thử nghiệm các ý tưởng thị giác mang tính đột phá."},
    {"id": "u12-v11", "word": "lifelong learning", "phonetic": "/ˈlaɪflɒŋ ˈlɜːnɪŋ/", "partOfSpeech": "noun", "vietnameseMeaning": "học tập suốt đời, không ngừng trau dồi tri thức", "englishExample": "In an era of rapid automation, lifelong learning is the key to remaining professionally adaptable.", "vietnameseExample": "Trong kỷ nguyên tự động hóa nhanh chóng, học tập suốt đời là chìa khóa để luôn thích ứng chuyên môn."},
    {"id": "u12-v12", "word": "critical thinking", "phonetic": "/ˈkrɪtɪkəl ˈθɪŋkɪŋ/", "partOfSpeech": "noun", "vietnameseMeaning": "tư duy phản biện sắc bén", "englishExample": "Critical thinking enables professionals to solve unprecedented global challenges with logic.", "vietnameseExample": "Tư duy phản biện giúp các chuyên gia giải quyết những thách thức toàn cầu chưa từng có bằng logic."},
    {"id": "u12-v13", "word": "renewable energy engineer", "phonetic": "/rɪˈnjuːəbl ˈɛnəʤi ˌɛnʤɪˈnɪə/", "partOfSpeech": "noun", "vietnameseMeaning": "kỹ sư năng lượng tái tạo", "englishExample": "A renewable energy engineer designs efficient offshore wind farms and solar thermal grids.", "vietnameseExample": "Một kỹ sư năng lượng tái tạo thiết kế các trang trại điện gió ngoài khơi và lưới điện nhiệt mặt trời hiệu quả."},
    {"id": "u12-v14", "word": "cybersecurity analyst", "phonetic": "/ˌsaɪbəsɪˈkjʊərɪti ˈænəlɪst/", "partOfSpeech": "noun", "vietnameseMeaning": "chuyên viên phân tích an ninh mạng", "englishExample": "A cybersecurity analyst detects and neutralizes digital intrusion threats to safeguard banking data.", "vietnameseExample": "Một chuyên viên phân tích an ninh mạng phát hiện và vô hiệu hóa các mối đe dọa xâm nhập số để bảo vệ dữ liệu ngân hàng."},
    {"id": "u12-v15", "word": "qualification", "phonetic": "/ˌkwɒlɪfɪˈkeɪʃən/", "partOfSpeech": "noun", "vietnameseMeaning": "bằng cấp chuyên môn, trình độ đạt chuẩn", "englishExample": "Holding international teaching qualifications opens up rewarding global lecturing opportunities.", "vietnameseExample": "Sở hữu bằng cấp giảng dạy quốc tế mở ra những cơ hội giảng dạy toàn cầu đầy đãi ngộ."},
    {"id": "u12-v16", "word": "adaptability", "phonetic": "/əˌdæptəˈbɪlɪti/", "partOfSpeech": "noun", "vietnameseMeaning": "khả năng thích ứng linh hoạt", "englishExample": "Mental adaptability allows workers to master emerging technologies and thrive amid changes.", "vietnameseExample": "Khả năng thích ứng tinh thần cho phép người lao động làm chủ các công nghệ mới nổi và phát triển mạnh mẽ giữa những đổi thay."},
    {"id": "u12-v17", "word": "career progression", "phonetic": "/kəˈrɪə prəˈɡrɛʃən/", "partOfSpeech": "noun", "vietnameseMeaning": "sự thăng tiến và phát triển sự nghiệp", "englishExample": "Continuous skill upgrading fosters swift career progression toward senior managerial roles.", "vietnameseExample": "Nâng cấp kỹ năng liên tục thúc đẩy sự thăng tiến sự nghiệp nhanh chóng hướng tới các vị trí quản lý cấp cao."},
    {"id": "u12-v18", "word": "biomedical engineer", "phonetic": "/ˌbaɪəʊˈmɛdɪkəl ˌɛnʤɪˈnɪə/", "partOfSpeech": "noun", "vietnameseMeaning": "kỹ sư y sinh học", "englishExample": "Biomedical engineers create robotic prosthetics and artificial organs to transform patients' lives.", "vietnameseExample": "Các kỹ sư y sinh tạo ra các chi giả robot và cơ quan nhân tạo để biến đổi cuộc sống của người bệnh."},
    {"id": "u12-v19", "word": "financial literacy", "phonetic": "/faɪˈnænʃəl ˈlɪtərəsi/", "partOfSpeech": "noun", "vietnameseMeaning": "năng lực hiểu biết tài chính cá nhân", "englishExample": "Early financial literacy helps young workers invest prudently and build long-term economic stability.", "vietnameseExample": "Hiểu biết tài chính sớm giúp người lao động trẻ đầu tư thận trọng và xây dựng sự ổn định kinh tế lâu dài."},
    {"id": "u12-v20", "word": "professional vocation", "phonetic": "/prəˈfɛʃənl vəʊˈkeɪʃən/", "partOfSpeech": "noun", "vietnameseMeaning": "sứ mệnh nghề nghiệp thiêng liêng / thiên chức", "englishExample": "Teaching is a noble professional vocation that sculpts the future leaders and scientists of society.", "vietnameseExample": "Dạy học là một thiên chức nghề nghiệp cao quý điêu khắc nên những nhà lãnh đạo và nhà khoa học tương lai của xã hội."}
]

u12_grammar_info = {
    "title": "Câu Tường Thuật Với Động Từ Tường Thuật & Danh Động Từ / Động Từ Nguyên Mẫu (Reported Speech with Reporting Verbs: To-Inf & Gerund / Phrasal Verbs)",
    "summary": "Nắm vững cách sử dụng các động từ tường thuật đặc biệt đi với To-inf (promise, offer, refuse, advise, invite, warn, remind, encourage) và đi với V-ing (admit, deny, suggest, apologize for, thank for, insist on, accuse of), cùng các Cụm động từ (Phrasal Verbs) quan trọng về nghề nghiệp.",
    "formulaBox": [
        "1. V + TO-INF: agree, demand, offer, promise, refuse, threaten + TO V",
        "2. V + O + TO-INF: advise, allow, ask, encourage, invite, remind, tell, warn + O + (NOT) TO V",
        "3. V + V-ING: admit, deny, suggest, recommend + V-ING",
        "4. V + (O) + GIỚI TỪ + V-ING: apologize (to sb) for, congratulate sb on, thank sb for, warn sb against/about, insist on, accuse sb of + V-ING",
        "5. Cụm động từ nghề nghiệp: take up (bắt đầu học/làm nghề), carry out (tiến hành), give up (từ bỏ), look forward to (mong đợi), keep up with (bắt kịp), figure out (tìm ra giải pháp)."
    ],
    "usagePoints": [
        {"title": "1. Động từ tường thuật với V-ing", "detail": "Chú ý giới từ đi kèm: He apologized for being late; The manager congratulated Mai on winning the design prize.", "example": "The career counselor suggested exploring renewable energy careers."},
        {"title": "2. Cụm động từ (Phrasal Verbs)", "detail": "Cụm động từ có nghĩa biến đổi so với động từ gốc. Lưu ý: look forward to + V-ing.", "example": "She is looking forward to starting her dream internship next month."}
    ]
}

u12_grammar_exs = [
    {"id": "u12-g1", "question": "The career counselor advised Nam _____ his coding skills before applying for the software engineering internship.", "options": ["A. to sharpen", "B. sharpening", "C. sharpen", "D. should sharpen"], "correctAnswer": "A. to sharpen", "explanation": "Cấu trúc: 'advise + O + to V' -> 'advised Nam to sharpen'."},
    {"id": "u12-g2", "question": "The manager congratulated Mai on _____ the employee of the month award.", "options": ["A. winning", "B. to win", "C. win", "D. won"], "correctAnswer": "A. winning", "explanation": "Cấu trúc: 'congratulate sb on + V-ing' -> 'on winning'."},
    {"id": "u12-g3", "question": "Linh admitted _____ nervous during her first technical job interview.", "options": ["A. feeling", "B. to feel", "C. feel", "D. felt"], "correctAnswer": "A. feeling", "explanation": "Cấu trúc: 'admit + V-ing' -> 'admitted feeling'."},
    {"id": "u12-g4", "question": "The engineer promised _____ the offshore wind turbine maintenance report by Friday.", "options": ["A. to deliver", "B. delivering", "C. deliver", "D. delivered"], "correctAnswer": "A. to deliver", "explanation": "Cấu trúc: 'promise + to V' -> 'promised to deliver'."},
    {"id": "u12-g5", "question": "The mentor encouraged the students _____ up programming as a lifelong career path.", "options": ["A. to take", "B. taking", "C. take", "D. took"], "correctAnswer": "A. to take", "explanation": "Cấu trúc: 'encourage + O + to V' -> 'encouraged the students to take up'."},
    {"id": "u12-g6", "question": "The cybersecurity firm warned its clients against _____ unverified software applications.", "options": ["A. downloading", "B. to download", "C. download", "D. downloaded"], "correctAnswer": "A. downloading", "explanation": "Cấu trúc: 'warn sb against + V-ing' -> 'against downloading'."},
    {"id": "u12-g7", "question": "He apologized to his team leader for _____ late for the critical strategy meeting.", "options": ["A. arriving", "B. to arrive", "C. arrive", "D. arrived"], "correctAnswer": "A. arriving", "explanation": "Cấu trúc: 'apologize (to sb) for + V-ing' -> 'for arriving'."},
    {"id": "u12-g8", "question": "The doctor suggested _____ a healthier work-life balance to reduce chronic stress.", "options": ["A. adopting", "B. to adopt", "C. adopt", "D. adopted"], "correctAnswer": "A. adopting", "explanation": "Cấu trúc: 'suggest + V-ing' -> 'suggested adopting'."},
    {"id": "u12-g9", "question": "My father reminded me _____ my professional resume before submitting it online.", "options": ["A. to proofread", "B. proofreading", "C. proofread", "D. proofreaded"], "correctAnswer": "A. to proofread", "explanation": "Cấu trúc: 'remind + O + to V' -> 'reminded me to proofread'."},
    {"id": "u12-g10", "question": "The young entrepreneur refused _____ up her sustainable fashion startup despite initial difficulties.", "options": ["A. to give", "B. giving", "C. give", "D. gave"], "correctAnswer": "A. to give", "explanation": "Cấu trúc: 'refuse + to V' -> 'refused to give up'."},
    {"id": "u12-g11", "question": "We are eagerly looking forward to _____ our research internship at the National AI Center.", "options": ["A. commencing", "B. commence", "C. to commence", "D. commenced"], "correctAnswer": "A. commencing", "explanation": "Cấu trúc: 'look forward to + V-ing' -> 'to commencing'."},
    {"id": "u12-g12", "question": "The data scientist insisted on _____ the algorithm test three times to verify precision.", "options": ["A. running", "B. to run", "C. run", "D. ran"], "correctAnswer": "A. running", "explanation": "Cấu trúc: 'insist on + V-ing' -> 'on running'."},
    {"id": "u12-g13", "question": "The teacher offered _____ the student understand complex biochemical concepts after class.", "options": ["A. to help", "B. helping", "C. help", "D. helped"], "correctAnswer": "A. to help", "explanation": "Cấu trúc: 'offer + to V' -> 'offered to help'."},
    {"id": "u12-g14", "question": "The recruitment officer invited the outstanding candidate _____ the final round interview.", "options": ["A. to attend", "B. attending", "C. attend", "D. attended"], "correctAnswer": "A. to attend", "explanation": "Cấu trúc: 'invite + O + to V' -> 'invited the candidate to attend'."},
    {"id": "u12-g15", "question": "He denied _____ company confidential blueprints to external competitors.", "options": ["A. disclosing", "B. to disclose", "C. disclose", "D. disclosed"], "correctAnswer": "A. disclosing", "explanation": "Cấu trúc: 'deny + V-ing' -> 'denied disclosing'."},
    {"id": "u12-g16", "question": "Young professionals must continuously update their skills to keep _____ with rapid technological changes.", "options": ["A. up", "B. on", "C. off", "D. out"], "correctAnswer": "A. up", "explanation": "Cụm động từ: 'keep up with' có nghĩa là theo kịp, bắt kịp."},
    {"id": "u12-g17", "question": "The senior engineer carried _____ extensive safety inspections on the high-speed rail line.", "options": ["A. out", "B. on", "C. up", "D. in"], "correctAnswer": "A. out", "explanation": "Cụm động từ: 'carry out' có nghĩa là tiến hành, thực hiện."},
    {"id": "u12-g18", "question": "She thanked her mentor for _____ her insightful guidance throughout her career journey.", "options": ["A. providing", "B. to provide", "C. provide", "D. provided"], "correctAnswer": "A. providing", "explanation": "Cấu trúc: 'thank sb for + V-ing' -> 'for providing'."},
    {"id": "u12-g19", "question": "After hours of brainstorming, the team finally figured _____ an innovative solution.", "options": ["A. out", "B. on", "C. off", "D. up"], "correctAnswer": "A. out", "explanation": "Cụm động từ: 'figure out' có nghĩa là tìm ra giải pháp, hiểu ra."},
    {"id": "u12-g20", "question": "The university dean encouraged students _____ multidisciplinary subjects to broaden their career horizon.", "options": ["A. to pursue", "B. pursuing", "C. pursue", "D. pursued"], "correctAnswer": "A. to pursue", "explanation": "Cấu trúc: 'encourage + O + to V' -> 'encouraged students to pursue'."}
]

u12_listening_info = {
    "audioTitle": "Định Hướng Nghề Nghiệp & Công Việc Tương Lai (Jobs of the Future & Career Orientation)",
    "audioDuration": "3:25",
    "audioScriptSpeaker": "Career Advisor Mr. Brian & Student Huong",
    "transcriptText": "Huong: Mr. Brian, as a grade 9 student preparing for upper secondary school, what career orientation advice do you have regarding the jobs of the future?\nMr. Brian: Hello Huong! In the emerging fourth industrial revolution, automation and artificial intelligence are redefining the global job market. High-demand future careers will concentrate in green energy engineering, cybersecurity analysis, biomedical engineering, and data science.\nHuong: Will technical expertise alone guarantee career success?\nMr. Brian: Absolutely not! While hard technical qualifications are indispensable, employers overwhelmingly prioritize critical thinking, emotional empathy, cross-cultural collaboration, and adaptable lifelong learning. Machines can compute numbers rapidly, but human compassion, creativity, and moral judgment remain completely irreplaceable!\nHuong: How should grade 9 students prepare themselves right now?\nMr. Brian: Discover your authentic passion, sharpen your English communication, cultivate digital literacy, and embrace every opportunity to volunteer or join STEM and vocational clubs!",
    "vietnameseTranslation": "Hương: Thưa thầy Brian, là một học sinh lớp 9 đang chuẩn bị bước vào cấp ba, thầy có lời khuyên định hướng nghề nghiệp nào về các công việc tương lai không ạ?\nThầy Brian: Chào Hương! Trong cuộc cách mạng công nghiệp lần thứ tư đang diễn ra, tự động hóa và trí tuệ nhân tạo đang định hình lại thị trường việc làm toàn cầu. Các nghề nghiệp tương lai có nhu cầu tuyển dụng cao sẽ tập trung vào kỹ thuật năng lượng xanh, phân tích an ninh mạng, kỹ thuật y sinh và khoa học dữ liệu.\nHương: Liệu chỉ riêng chuyên môn kỹ thuật có đảm bảo thành công sự nghiệp không ạ?\nThầy Brian: Hoàn toàn không! Mặc dù bằng cấp kỹ thuật là không thể thiếu, các nhà tuyển dụng ưu tiên hàng đầu tư duy phản biện, sự thấu cảm, khả năng cộng tác đa văn hóa và tinh thần học tập suốt đời. Máy móc có thể tính toán số liệu nhanh chóng, nhưng lòng trắc ẩn, tính sáng tạo và phán đoán đạo đức của con người vẫn hoàn toàn không thể thay thế!\nHương: Học sinh lớp 9 nên chuẩn bị cho mình như thế nào ngay từ bây giờ ạ?\nThầy Brian: Hãy khám phá đam mê thực sự của em, trau dồi khả năng giao tiếp tiếng Anh, rèn luyện năng lực số và nắm bắt mọi cơ hội tham gia hoạt động tình nguyện hoặc các câu lạc bộ STEM và hướng nghiệp!"
}

u12_listening_qs = [
    {"id": "u12-l1", "question": "What is redefining the global job market according to Mr. Brian?", "options": ["A. Automation and artificial intelligence in the 4th industrial revolution", "B. Medieval horse breeding", "C. Manual stone carving", "D. Nothing at all"], "correctAnswerIndex": 0, "explanation": "Trong bài nghe: 'In the emerging fourth industrial revolution, automation and artificial intelligence are redefining the global job market.'"},
    {"id": "u12-l2", "question": "Which career fields are highlighted as high-demand in the future?", "options": ["A. Green energy engineering, cybersecurity analysis, biomedical engineering, and data science", "B. Blacksmithing and traditional candle making", "C. Typewriter repair", "D. Silent movie acting"], "correctAnswerIndex": 0, "explanation": "Trong bài nghe: 'green energy engineering, cybersecurity analysis, biomedical engineering, and data science.'"},
    {"id": "u12-l3", "question": "Will technical expertise alone guarantee career success?", "options": ["A. Absolutely not; soft skills and emotional empathy are equally vital", "B. Yes, 100% guaranteed without talking to people", "C. Yes, machines do not need humans", "D. No one needs any skills"], "correctAnswerIndex": 0, "explanation": "Trong bài nghe: 'Absolutely not! While hard technical qualifications are indispensable, employers overwhelmingly prioritize...'"},
    {"id": "u12-l4", "question": "What human qualities remain irreplaceable by machines according to Mr. Brian?", "options": ["A. Human compassion, creativity, and moral judgment", "B. Fast multiplication only", "C. Heavy lifting only", "D. Storing data"], "correctAnswerIndex": 0, "explanation": "Trong bài nghe: 'human compassion, creativity, and moral judgment remain completely irreplaceable!'"},
    {"id": "u12-l5", "question": "What soft skills do employers prioritize heavily?", "options": ["A. Critical thinking, emotional empathy, and cross-cultural collaboration", "B. Playing games silently", "C. Shouting loudly", "D. Refusing to work with others"], "correctAnswerIndex": 0, "explanation": "Trong bài nghe: 'critical thinking, emotional empathy, cross-cultural collaboration, and adaptable lifelong learning.'"},
    {"id": "u12-l6", "question": "What should students do regarding their passion?", "options": ["A. Discover their authentic passion and strengths", "B. Ignore all interests", "C. Copy whatever their neighbor does", "D. Never try anything new"], "correctAnswerIndex": 0, "explanation": "Mr. Brian khuyên: 'Discover your authentic passion...'"},
    {"id": "u12-l7", "question": "What practical activities can grade 9 students join right now?", "options": ["A. Volunteer activities, STEM clubs, and vocational workshops", "B. Skipping classes", "C. Staying inside playing video games", "D. Sleeping all day"], "correctAnswerIndex": 0, "explanation": "Trong bài nghe: 'volunteer or join STEM and vocational clubs!'"},
    {"id": "u12-l8", "question": "What role does English communication play in future careers?", "options": ["A. Sharpens international connectivity and unlocks global opportunities", "B. Has no value", "C. Only useful for tourists", "D. Replaced by silence"], "correctAnswerIndex": 0, "explanation": "Mr. Brian nhấn mạnh việc mài giũa kỹ năng giao tiếp tiếng Anh để làm chủ tương lai."}
]

u12_listening_fibs = [
    {"id": "u12-f1", "sentenceWithBlank": "Automation is redefining the global _____ market.", "correctWord": "job", "hint": "Thị trường việc làm (job market)"},
    {"id": "u12-f2", "sentenceWithBlank": "Human compassion and creativity remain _____ by machines.", "correctWord": "irreplaceable", "hint": "Không thể thay thế (irreplaceable)"},
    {"id": "u12-f3", "sentenceWithBlank": "Employers prioritize adaptable _____ learning.", "correctWord": "lifelong", "hint": "Học tập suốt đời (lifelong learning)"},
    {"id": "u12-f4", "sentenceWithBlank": "Students should discover their authentic _____ and strengths.", "correctWord": "passion", "hint": "Đam mê (passion)"}
]

u12_speaking = [
    {"id": f"u12-s{i+1}", "targetSentence": s, "ipa": ipa, "vietnameseMeaning": vm, "contextSituation": ctx, "keyPhonicsFocus": kpf, "sampleAudioText": s}
    for i, (s, ipa, vm, ctx, kpf) in enumerate([
        ("Early career orientation empowers grade nine students to discover their authentic strengths and choose fulfilling educational pathways.", "/ˈɜːli kəˈrɪər ˌɔːriɛnˈteɪʃən ɪmˈpaʊəz ɡreɪd naɪn ˈstjuːdənts tuː dɪsˈkʌvə ðeər ɔːˈθɛntɪk strɛŋkθs ænd ʧuːz fʊlˈfɪlɪŋ ˌɛʤʊˈkeɪʃənl ˈpɑːθweɪz/", "Định hướng nghề nghiệp sớm tiếp thêm sức mạnh cho học sinh lớp 9 khám phá thế mạnh thực sự và lựa chọn những con đường học tập trọn vẹn.", "Thuyết trình về định hướng nghề nghiệp lớp 9.", "Phát âm chuẩn 'early career orientation' và 'fulfilling pathways'."),
        ("The career counselor advised Nam to sharpen his software programming skills before applying for the tech internship.", "/ðə kəˈrɪə ˈkaʊnsələ ədˈvaɪzd næm tuː ˈʃɑːpən hɪz ˈsɒftweə ˈprəʊɡræmɪŋ skɪlz bɪˈfɔːr əˈplaɪɪŋ fɔː ðə tɛk ˈɪntɜːnʃɪp/", "Chuyên viên tư vấn hướng nghiệp đã khuyên Nam trau dồi kỹ năng lập trình phần mềm trước khi nộp đơn thực tập công nghệ.", "Tường thuật lời khuyên hướng nghiệp (advise + O + to V).", "Phát âm chuẩn 'advised Nam to sharpen'."),
        ("Emerging high-demand careers in renewable energy engineering and data science offer boundless opportunities for youth.", "/ɪˈmɜːʤɪŋ haɪ-dɪˈmɑːnd kəˈrɪəz ɪn rɪˈnjuːəbl ˈɛnəʤi ˌɛnʤɪˈnɪərɪŋ ænd ˈdeɪtə ˈsaɪəns ˈɒfə ˈbaʊndlɪs ˌɒpəˈtjuːnɪtiz fɔː juːθ/", "Những ngành nghề mới nổi có nhu cầu cao trong kỹ thuật năng lượng tái tạo và khoa học dữ liệu mở ra cơ hội vô tận cho giới trẻ.", "Nói về ngành nghề tương lai.", "Phát âm chuẩn 'renewable energy engineering' và 'data science'."),
        ("The department manager congratulated Mai on successfully carrying out the complex biomedical research project.", "/ðə dɪˈpɑːtmənt ˈmænɪʤə kənˈɡrætjʊleɪtɪd maɪ ɒn səkˈsɛsfʊli ˈkæriɪŋ aʊt ðə ˈkɒmplɛks ˌbaɪəʊˈmɛdɪkəl rɪˈsɜːʧ ˈprɒʤɛkt/", "Trưởng phòng đã chúc mừng Mai vì đã thực hiện thành công dự án nghiên cứu y sinh học phức tạp.", "Tường thuật lời chúc mừng (congratulate on + V-ing).", "Phát âm chuẩn 'congratulated Mai on carrying out'."),
        ("While artificial intelligence automates routine calculations, human empathy, creative wit, and ethics remain completely irreplaceable.", "/waɪl ˌɑːtɪˈfɪʃəl ɪnˈtɛlɪʤəns ˈɔːtəmeɪts ruːˈtiːn ˌkælkjʊˈleɪʃənz ˈhjuːmən ˈɛmpəθi kriˈeɪtɪv wɪt ænd ˈɛθɪks rɪˈmeɪn kəmˈpliːtli ˌɪrɪˈpleɪsəbl/", "Trong khi trí tuệ nhân tạo tự động hóa các phép tính lặp đi lặp lại, lòng trắc ẩn, sự sáng tạo và đạo đức của con người vẫn hoàn toàn không thể thay thế.", "So sánh con người và AI.", "Phát âm chuẩn 'human empathy' và 'irreplaceable' /ˌɪrɪˈpleɪsəbl/."),
        ("The mentor encouraged young entrepreneurs to persevere with resilience when confronting initial business setbacks.", "/ðə ˈmɛntɔːr ɪnˈkʌrɪʤd jʌŋ ˌɒntrəprəˈnɜːz tuː ˌpɜːsɪˈvɪə wɪð rɪˈzɪlɪəns wɛn kənˈfrʌntɪŋ ɪˈnɪʃəl ˈbɪznɪs ˈsɛtbæks/", "Người thầy cố vấn đã khuyến khích các doanh nhân trẻ kiên trì bền bỉ khi đối mặt với những trở ngại kinh doanh ban đầu.", "Tường thuật lời khuyến khích (encourage + O + to V).", "Phát âm chuẩn 'persevere with resilience' /ˌpɜːsɪˈvɪə wɪð rɪˈzɪlɪəns/."),
        ("We are eagerly looking forward to starting our summer internship at the national cybersecurity operations center.", "/wiː ɑːr ˈiːɡəli ˈlʊkɪŋ ˈfɔːwəd tuː ˈstɑːtɪŋ ˈaʊə ˈsʌmər ˈɪntɜːnʃɪp æt ðə ˈnæʃənl ˌsaɪbəsɪˈkjʊərɪti ˌɒpəˈreɪʃənz ˈsɛntə/", "Chúng tôi đang rất háo hức mong đợi bắt đầu kỳ thực tập mùa hè tại trung tâm điều hành an ninh mạng quốc gia.", "Bày tỏ sự mong đợi bằng 'look forward to + V-ing'.", "Phát âm chuẩn 'looking forward to starting'."),
        ("Vocational training schools equip students with specialized practical craftsmanship and direct pathways to rewarding employment.", "/vəʊˈkeɪʃənl ˈtreɪnɪŋ skuːlz ɪˈkwɪp ˈstjuːdənts wɪð ˈspɛʃəlaɪzd ˈpræktɪkəl ˈkrɑːftsmənʃɪp ænd dɪˈrɛkt ˈpɑːθweɪz tuː rɪˈwɔːdɪŋ ɪmˈplɔɪmənt/", "Các trường đào tạo nghề trang bị cho học sinh tay nghề thực hành chuyên môn và con đường trực tiếp đến việc làm đãi ngộ cao.", "Nói về giá trị trường nghề.", "Phát âm chuẩn 'vocational training' và 'practical craftsmanship'."),
        ("She apologized to the recruitment committee for arriving late due to unforeseen morning traffic congestion.", "/ʃiː əˈpɒləʤaɪzd tuː ðə rɪˈkruːtmənt kəˈmɪti fɔːr əˈraɪvɪŋ leɪt djuː tuː ˌʌnfɔːˈsiːn ˈmɔːnɪŋ ˈtræfɪk kənˈʤɛsʧən/", "Cô ấy đã xin lỗi hội đồng tuyển dụng vì đến muộn do tắc nghẽn giao thông buổi sáng bất khả kháng.", "Tường thuật lời xin lỗi (apologize for + V-ing).", "Phát âm chuẩn 'apologized for arriving late'."),
        ("Continuous lifelong learning and mental adaptability are indispensable armor for thriving in the modern digital economy.", "/kənˈtɪnjuːəs ˈlaɪflɒŋ ˈlɜːnɪŋ ænd ˈmɛntl əˌdæptəˈbɪlɪti ɑːr ˌɪndɪsˈpɛnsəbl ˈɑːmə fɔː ˈθraɪvɪŋ ɪn ðə ˈmɒdən ˈdɪʤɪtl iːˈkɒnəmi/", "Học tập suốt đời liên tục và khả năng thích ứng tinh thần là bộ áo giáp không thể thiếu để phát triển mạnh mẽ trong nền kinh tế số hiện đại.", "Nói về học tập suốt đời.", "Phát âm chuẩn 'lifelong learning' và 'indispensable armor'."),
        ("The senior software architect suggested adopting agile collaboration methodologies to boost project efficiency.", "/ðə ˈsiːniə ˈsɒftweər ˈɑːkɪtɛkt səˈʤɛstɪd əˈdɒptɪŋ ˈæʤaɪl kəˌlæbəˈreɪʃən ˌmɛθəˈdɒləʤiz tuː buːst ˈprɒʤɛkt ɪˈfɪʃənsi/", "Kiến trúc sư phần mềm cấp cao đã đề xuất áp dụng các phương pháp cộng tác linh hoạt để tăng hiệu quả dự án.", "Tường thuật lời đề xuất (suggest + V-ing).", "Phát âm chuẩn 'suggested adopting agile methodologies'."),
        ("Maintaining a harmonious work-life balance nurtures physical health, emotional well-being, and enduring creative passion.", "/meɪnˈteɪnɪŋ ə hɑːˈməʊniəs wɜːk-laɪf ˈbæləns ˈnɜːʧəz ˈfɪzɪkəl hɛlθ ɪˈməʊʃənl wɛl-ˈbiːɪŋ ænd ɪnˈdjʊərɪŋ kriˈeɪtɪv ˈpæʃən/", "Duy trì sự cân bằng hài hòa giữa công việc và cuộc sống nuôi dưỡng sức khỏe thể chất, hạnh phúc cảm xúc và niềm đam mê sáng tạo bền bỉ.", "Nói về cân bằng cuộc sống.", "Phát âm chuẩn 'work-life balance' và 'enduring passion'."),
        ("The IT specialist warned all new employees against downloading unverified software on company computers.", "/ði aɪ-tiː ˈspɛʃəlɪst wɔːnd ɔːl njuː ˌɛmplɔɪˈiːz əˈɡɛnst ˌdaʊnˈləʊdɪŋ ʌnɪnˈkrɪptɪd ˈsɒftweər ɒn ˈkʌmpəni kəmˈpjuːtəz/", "Chuyên gia CNTT cảnh báo tất cả nhân viên mới không được tải phần mềm chưa được xác minh trên máy tính công ty.", "Tường thuật lời cảnh báo (warn against + V-ing).", "Phát âm chuẩn 'warned against downloading'."),
        ("Critical thinking and empathetic communication elevate ordinary technicians into visionary global leaders.", "/ˈkrɪtɪkəl ˈθɪŋkɪŋ ænd ˌɛmpəˈθɛtɪk kəˌmjuːnɪˈkeɪʃən ˈɛlɪveɪt ˈɔːdnri tɛkˈnɪʃənz ˈɪntuː ˈvɪʒnəri ˈɡləʊbəl ˈliːdəz/", "Tư duy phản biện và giao tiếp thấu cảm nâng tầm những kỹ thuật viên bình thường thành những nhà lãnh đạo toàn cầu có tầm nhìn xa trông rộng.", "Nói về sức mạnh của kỹ năng mềm.", "Phát âm chuẩn 'visionary global leaders' /ˈvɪʒnəri ˈɡləʊbəl ˈliːdəz/."),
        ("He promised to complete the comprehensive market analysis report before Monday morning.", "/hiː ˈprɒmɪst tuː kəmˈpliːt ðə ˌkɒmprɪˈhɛnsɪv ˈmɑːkɪt əˈnæləsɪs rɪˈpɔːt bɪˈfɔː ˈmʌndeɪ ˈmɔːnɪŋ/", "Anh ấy đã hứa sẽ hoàn thành bản báo cáo phân tích thị trường toàn diện trước sáng thứ Hai.", "Tường thuật lời hứa (promise + to V).", "Phát âm chuẩn 'promised to complete'."),
        ("Young professionals who possess high English proficiency access prestigious global fellowships and international conferences.", "/jʌŋ prəˈfɛʃənlz huː pəˈzɛs haɪ ˈɪŋɡlɪʃ prəˈfɪʃənsi ˈæksɛs prɛˈstɪʤəs ˈɡləʊbəl ˈfɛləʊʃɪps ænd ˌɪntəˈnæʃənl ˈkɒnfərənsɪz/", "Những chuyên gia trẻ sở hữu trình độ tiếng Anh cao sẽ tiếp cận được các học bổng nghiên cứu quốc tế danh giá và các hội nghị toàn cầu.", "Nhấn mạnh vai trò tiếng Anh trong sự nghiệp.", "Phát âm chuẩn 'prestigious fellowships' /prɛˈstɪʤəs ˈfɛləʊʃɪps/."),
        ("The university professor reminded us to submit our graduate internship applications before the official deadline.", "/ðə ˌjuːnɪˈvɜːsɪti prəˈfɛsə rɪˈmaɪndɪd ʌs tuː səbˈmɪt ˈaʊə ˈɡrædjʊət ˈɪntɜːnʃɪp ˌæplɪˈkeɪʃənz bɪˈfɔː ði əˈfɪʃəl ˈdɛdlaɪn/", "Giáo sư đại học đã nhắc nhở chúng tôi nộp hồ sơ thực tập tốt nghiệp trước hạn chót chính thức.", "Tường thuật lời nhắc nhở (remind + O + to V).", "Phát âm chuẩn 'reminded us to submit'."),
        ("May your professional vocation bring boundless joy, honorable fulfillment, and noble contribution to our society.", "/meɪ jɔː prəˈfɛʃənl vəʊˈkeɪʃən brɪŋ ˈbaʊndlɪs ʤɔɪ ˈɒnərəbl fʊlˈfɪlmənt ænd ˈnəʊbl ˌkɒntrɪˈbjuːʃən tuː ˈaʊə səˈsaɪəti/", "Chúc cho thiên chức nghề nghiệp của bạn mang lại niềm vui vô tận, sự thỏa nguyện đáng kính và sự cống hiến cao quý cho xã hội chúng ta.", "Lời chúc sự nghiệp ý nghĩa.", "Phát âm chuẩn 'professional vocation' và 'noble contribution'."),
        ("True career triumph is measured by the positive lives you illuminate and the legacy of kindness you leave behind.", "/truː kəˈrɪə ˈtraɪəmf ɪz ˈmɛʒəd baɪ ðə ˈpɒzətɪv laɪvz juː ɪˈljuːmɪneɪt ænd ðə ˈlɛɡəsi ɒv ˈkaɪndnɪs juː liːv bɪˈhaɪnd/", "Thành công sự nghiệp thực sự được đo lường bằng những cuộc đời tươi sáng mà bạn thắp lên và di sản lòng nhân ái mà bạn để lại.", "Triết lý về thành công sự nghiệp.", "Phát âm chuẩn 'career triumph' /ˈtraɪəmf/ và 'legacy of kindness'."),
        ("Let us step boldly into the future with passionate hearts, curious minds, and unwavering integrity.", "/lɛt ʌs stɛp ˈbəʊldli ˈɪntuː ðə ˈfjuːʧə wɪð ˈpæʃənɪt hɑːts ˈkjʊərɪəs maɪndz ænd ʌnˈweɪvərɪŋ ɪnˈtɛɡrɪti/", "Chúng ta hãy cùng bước đi can trường vào tương lai với trái tim nhiệt huyết, tâm trí hiếu kỳ và sự chính trực không gì lay chuyển.", "Thông điệp truyền cảm hứng kết thúc chương trình lớp 9.", "Phát âm chuẩn 'passionate hearts' và 'unwavering integrity' /ʌnˈweɪvərɪŋ ɪnˈtɛɡrɪti/.")
    ])
]

u12_reading_info = {
    "title": "Nghề Nghiệp Tương Lai Trong Kỷ Nguyên AI: Kỹ Năng Cốt Lõi & Định Hướng Toàn Diện",
    "topic": "Sự chuyển dịch của thị trường lao động trong kỷ nguyên số, các ngành nghề công nghệ và năng lượng mới, tầm quan trọng của kỹ năng mềm và học tập suốt đời",
    "passageText": "The contemporary labor landscape is undergoing a monumental paradigm shift propelled by artificial intelligence, automated robotics, and green sustainable technologies. As algorithmic automation takes over routine administrative and manual manufacturing tasks, the employment market is generating unprecedented demand for specialized, high-cognition professions. Careers in data science, artificial intelligence engineering, cybersecurity infrastructure, and renewable energy systems are experiencing exponential growth worldwide.\n\nSimultaneously, the healthcare and biotechnology sectors are witnessing rapid expansion. Biomedical engineers designing neural prosthetics, genetic counselors interpreting DNA profiles, and geriatric healthcare managers are becoming indispensable pillars of modern society. Furthermore, the global drive toward decarbonization is spawning entire new green industries, from offshore wind grid engineers to circular economy logistics managers.\n\nCrucially, human resource strategists emphasize that in an automated era, uniquely human soft skills represent the ultimate competitive advantage. While artificial neural networks can analyze petabytes of algorithmic data in seconds, they fundamentally lack emotional empathy, ethical discernment, creative ingenuity, and cross-cultural communicative agility. Therefore, successful future professionals must cultivate a mindset of lifelong learning—viewing education not as a finite teenage milestone, but as an ongoing, dynamic journey of personal growth, intellectual curiosity, and societal service.",
    "keyVocabularyHighlights": [
        {"word": "monumental paradigm shift", "meaning": "sự chuyển dịch mô hình mang tính bước ngoặt vĩ đại"},
        {"word": "high-cognition professions", "meaning": "các ngành nghề đòi hỏi năng lực nhận thức và tư duy bậc cao"},
        {"word": "ethical discernment", "meaning": "khả năng phân định và phán đoán đạo đức sáng suốt"},
        {"word": "creative ingenuity", "meaning": "sự tài tình và tính sáng tạo khéo léo"}
    ]
}

u12_reading_qs = [
    {"id": "u12-r1", "question": "What forces are propelling the monumental paradigm shift in the labor landscape?", "options": ["A. Artificial intelligence, automated robotics, and green sustainable technologies", "B. Traditional agricultural tools from the 18th century", "C. Abandoning all computers", "D. Stopping all international trade"], "correctAnswerIndex": 0, "explanation": "Trong đoạn 1: 'propelled by artificial intelligence, automated robotics, and green sustainable technologies.'"},
    {"id": "u12-r2", "question": "What happens as automation takes over routine manual and administrative tasks?", "options": ["A. Unprecedented demand is created for specialized high-cognition professions", "B. All jobs on Earth disappear forever", "C. Nobody goes to work anymore", "D. Wages drop to zero"], "correctAnswerIndex": 0, "explanation": "Trong đoạn 1: 'the employment market is generating unprecedented demand for specialized, high-cognition professions.'"},
    {"id": "u12-r3", "question": "Which specific technical careers are experiencing exponential growth?", "options": ["A. Data science, AI engineering, cybersecurity infrastructure, and renewable energy", "B. Stone age weapon crafting", "C. Typewriter manufacturing", "D. Steam train coal shoveling"], "correctAnswerIndex": 0, "explanation": "Trong đoạn 1: 'Careers in data science, artificial intelligence engineering, cybersecurity infrastructure, and renewable energy systems are experiencing exponential growth...'"},
    {"id": "u12-r4", "question": "What roles in biotechnology and healthcare are highlighted in paragraph 2?", "options": ["A. Biomedical engineers, genetic counselors, and geriatric healthcare managers", "B. Medieval potion makers", "C. Diamond miners only", "D. Submarine pilots only"], "correctAnswerIndex": 0, "explanation": "Trong đoạn 2: 'Biomedical engineers designing neural prosthetics, genetic counselors interpreting DNA profiles, and geriatric healthcare managers...'"},
    {"id": "u12-r5", "question": "What green jobs are emerging from the global decarbonization drive?", "options": ["A. Offshore wind grid engineers and circular economy logistics managers", "B. Coal power plant builders", "C. Plastic bag salesmen", "D. Diesel truck makers"], "correctAnswerIndex": 0, "explanation": "Trong đoạn 2: 'spawning entire new green industries, from offshore wind grid engineers to circular economy logistics managers.'"},
    {"id": "u12-r6", "question": "What represents the ultimate competitive advantage in an automated era?", "options": ["A. Uniquely human soft skills like empathy, ethics, and creative ingenuity", "B. Being able to work 24 hours without drinking water", "C. Memorizing telephone directories", "D. Having a robotic arm"], "correctAnswerIndex": 0, "explanation": "Trong đoạn 3: 'uniquely human soft skills represent the ultimate competitive advantage... emotional empathy, ethical discernment, creative ingenuity...'"},
    {"id": "u12-r7", "question": "How should education be viewed according to paragraph 3?", "options": ["A. As an ongoing, dynamic journey of personal growth, curiosity, and societal service", "B. As a finite teenage test that ends after grade 9", "C. As a waste of time", "D. As a punishment for kids"], "correctAnswerIndex": 0, "explanation": "Trong đoạn 3: 'viewing education not as a finite teenage milestone, but as an ongoing, dynamic journey of personal growth, intellectual curiosity, and societal service.'"},
    {"id": "u12-r8", "question": "Which word in paragraph 1 is closest in meaning to 'exponential'?", "options": ["A. Rapid, accelerating, and increasingly fast", "B. Slow and stagnant", "C. Decreasing to zero", "D. Completely invisible"], "correctAnswerIndex": 0, "explanation": "'Exponential' có nghĩa là tăng trưởng theo cấp số nhân, cực kỳ nhanh chóng."},
    {"id": "u12-r9", "question": "Which word in paragraph 3 is closest in meaning to 'discernment'?", "options": ["A. Judgment, insight, or the ability to judge well", "B. Speed in typing", "C. Financial wealth", "D. Physical strength"], "correctAnswerIndex": 0, "explanation": "'Discernment' có nghĩa là sự phân định, nhận thức và phán đoán sáng suốt."},
    {"id": "u12-r10", "question": "What is the overarching theme of this reading passage?", "options": ["A. Thriving in future careers demands a synergy of STEM expertise, soft skills, and lifelong learning", "B. Robots will replace all humans and we should give up", "C. Only university degrees matter in life", "D. Healthcare is the only useful field"], "correctAnswerIndex": 0, "explanation": "Chủ đề cốt lõi là thành công trong tương lai đòi hỏi sự kết hợp giữa chuyên môn STEM, kỹ năng mềm đặc trưng con người và tinh thần học tập suốt đời."}
]

u12_writing_prompts = [
    {
        "id": "u12-w1",
        "title": "Đề 1: Write a paragraph describing your dream future career (60-80 words)",
        "description": "Viết một đoạn văn miêu tả nghề nghiệp mơ ước trong tương lai của em và lý do lựa chọn nghề này.",
        "suggestedOutline": [
            "Introduction: State your dream career (e.g., renewable energy engineer / AI data scientist / doctor).",
            "Body: Explain reasons (passion for science/helping others, high future demand, contributing to society).",
            "Conclusion: State your determination to study hard to achieve this dream."
        ],
        "usefulPhrases": [
            "My ultimate dream career is to become a dedicated renewable energy engineer...",
            "I am deeply passionate about designing offshore wind farms and solar grids that combat climate change...",
            "This high-demand profession allows me to combine STEM knowledge with meaningful societal impact...",
            "I am committed to studying hard in mathematics and English to turn this dream into reality."
        ],
        "wordLimit": "60 - 80 từ",
        "sampleGrade10Response": "My ultimate dream career is to become a dedicated renewable energy engineer. I am deeply passionate about designing innovative offshore wind farms and rooftop solar systems to combat global warming. This high-demand profession allows me to combine my strengths in physics and mathematics with a noble mission to protect our planet. Furthermore, clean energy offers tremendous career growth globally. I will study diligently in secondary school to gain admission into a top engineering university and realize my aspiration."
    },
    {
        "id": "u12-w2",
        "title": "Đề 2: Write a paragraph on the importance of soft skills in the workplace (60-80 words)",
        "description": "Viết một đoạn văn phân tích tại sao kỹ năng mềm lại đóng vai trò quyết định trong môi trường làm việc hiện đại.",
        "suggestedOutline": [
            "Introduction: State that soft skills are essential complements to technical knowledge.",
            "Body: Detail key soft skills (communication, teamwork, critical thinking, emotional empathy) and their workplace benefits.",
            "Conclusion: Emphasize that soft skills distinguish successful professionals."
        ],
        "usefulPhrases": [
            "In today's dynamic labor market, essential soft skills are just as vital as hard technical qualifications...",
            "Effective communication and emotional empathy foster strong team synergy and resolve workplace conflicts peacefully...",
            "Moreover, critical thinking enables professionals to solve complex problems logically under pressure...",
            "Cultivating soft skills empowers individuals to become visionary leaders and adaptable teammates."
        ],
        "wordLimit": "60 - 80 từ",
        "sampleGrade10Response": "In today's dynamic labor market, soft skills are just as vital as hard technical qualifications. Effective communication and emotional empathy enable professionals to build strong teamwork, resolve conflicts constructively, and understand client needs deeply. Moreover, critical thinking and adaptability empower workers to solve unexpected crises calmly under pressure. While machines can automate calculations, human collaboration and leadership remain irreplaceable. Cultivating strong soft skills from school days is the true secret to lifelong professional triumph."
    },
    {
        "id": "u12-w3",
        "title": "Đề 3: Write a paragraph on the value of vocational training after grade 9 (60-80 words)",
        "description": "Viết một đoạn văn trình bày những lợi ích thiết thực của con đường học nghề (đào tạo nghề) sau khi tốt nghiệp lớp 9.",
        "suggestedOutline": [
            "Introduction: State that vocational training is a practical and rewarding pathway after secondary school.",
            "Body: Explain benefits (hands-on practical skills, shorter training time, early entry into the workforce, high demand in technical sectors).",
            "Conclusion: Affirm that vocational education deserves high respect."
        ],
        "usefulPhrases": [
            "Pursuing vocational training after grade 9 represents a practical and highly rewarding career pathway...",
            "Vocational colleges equip students with hands-on technical craftsmanship in high-demand fields like automotive engineering and graphic design...",
            "This direct route allows young learners to enter the job market early and achieve financial independence...",
            "Vocational education provides dignified, prosperous careers for skilled artisans and technicians."
        ],
        "wordLimit": "60 - 80 từ",
        "sampleGrade10Response": "Pursuing vocational training after grade 9 represents a practical and highly rewarding career pathway. Vocational colleges equip students with hands-on technical craftsmanship in high-demand trades such as automotive mechanics, graphic design, and electrical engineering. This focused route enables young learners to gain job-ready skills quickly, enter the workforce early, and achieve financial independence sooner. Vocational education empowers skilled individuals to build prosperous, respected careers without having to follow a traditional four-year academic route."
    },
    {
        "id": "u12-w4",
        "title": "Đề 4: Write a paragraph on why lifelong learning is necessary in the AI era (60-80 words)",
        "description": "Viết một đoạn văn giải thích lý do tại sao tinh thần học tập suốt đời là bắt buộc trong kỷ nguyên trí tuệ nhân tạo.",
        "suggestedOutline": [
            "Introduction: State that lifelong learning is an indispensable survival skill in the age of AI.",
            "Body: Explain why (technologies evolve rapidly, old skills become obsolete, continuous learning maintains adaptability and employability).",
            "Conclusion: Urge young people to cultivate lifelong curiosity."
        ],
        "usefulPhrases": [
            "In the era of rapid artificial intelligence, lifelong learning is the ultimate key to professional survival and success...",
            "Technological advancements constantly transform industries, rendering static knowledge outdated in just a few years...",
            "Continuously upgrading digital literacy and mastering new tools ensures that workers remain highly adaptable and competitive...",
            "Viewing education as an ongoing lifelong journey keeps our minds sharp and resilient."
        ],
        "wordLimit": "60 - 80 từ",
        "sampleGrade10Response": "In the era of rapid artificial intelligence, lifelong learning is the ultimate key to professional resilience and success. Technological breakthroughs continuously transform industries, causing static knowledge to become outdated in just a few years. Continuously upgrading digital skills, reading widely, and taking online professional courses ensure that workers remain adaptable, creative, and highly competitive in an evolving labor market. Viewing learning as a lifelong journey rather than a finished milestone keeps our minds curious, vibrant, and future-ready."
    },
    {
        "id": "u12-w5",
        "title": "Đề 5: Write a paragraph giving advice on how to choose a suitable high school stream (60-80 words)",
        "description": "Viết một đoạn văn đưa ra lời khuyên cho học sinh lớp 9 về cách chọn tổ hợp môn/ban học cấp ba phù hợp với sở trường và định hướng.",
        "suggestedOutline": [
            "Introduction: State that choosing the right upper secondary study stream is an important decision.",
            "Body: Give advice (assess personal strengths and genuine interests in sciences vs humanities, consult teachers and parents, research future university requirements).",
            "Conclusion: Encourage making a thoughtful and confident choice."
        ],
        "usefulPhrases": [
            "Selecting a suitable upper secondary study stream requires careful self-reflection and objective evaluation...",
            "Grade 9 students should identify whether their genuine passions lie in natural sciences (STEM) or social humanities...",
            "Furthermore, consulting experienced teachers, career counselors, and parents provides valuable guidance...",
            "Making an informed, confident choice lays a solid foundation for future academic and career fulfillment."
        ],
        "wordLimit": "60 - 80 từ",
        "sampleGrade10Response": "Selecting a suitable upper secondary study stream requires careful self-reflection and objective evaluation. Grade 9 students should first assess their authentic academic strengths and genuine passions, determining whether they thrive in natural sciences (STEM) or social humanities. Furthermore, consulting experienced teachers, school career counselors, and parents provides valuable perspective on future university entry requirements. Making an informed, confident choice aligned with personal talents lays a solid foundation for high school success and future career fulfillment."
    }
]

unit12 = make_unit(12, "Unit 12: Career Choices", "Định hướng nghề nghiệp & Công việc tương lai", "Khám phá định hướng nghề nghiệp, đào tạo nghề, công việc tương lai trong kỷ nguyên số, Câu tường thuật với động từ tường thuật đặc biệt (Reported Speech with To-Inf & Gerund) & Cụm động từ (Phrasal Verbs).", "Ngữ âm: Cách nhấn trọng âm cụm động từ và ngữ điệu câu tường thuật biểu cảm", "Briefcase", u12_vocab, u12_grammar_info, u12_grammar_exs, u12_listening_info, u12_listening_qs, u12_listening_fibs, u12_speaking, u12_reading_info, u12_reading_qs, u12_writing_prompts)
write_ts_unit(12, unit12)
print("Unit 12 generated successfully!")

